var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'OUTPATIENT_REGISTRATION_ID',
'displayName' : '院内门诊流水号',
'type' : 'varchar(40)',
'javaName' : 'outpatientRegistrationId',
'note' : '本次门诊就诊在院内系统中的唯一标识',
'nullable':false,
'check':''},
{
'name' : 'PATIENT_ID',
'displayName' : '患者id',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '引用患者信息表T_PATIENT院内患者id',
'nullable':false,
'check':''},
{
'name' : 'PATIENT_NAME',
'displayName' : '患者姓名',
'type' : 'varchar(40)',
'javaName' : 'patientName',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'RECEIVE_EMPLOYEE_ID',
'displayName' : '接诊医生id',
'type' : 'varchar(40)',
'javaName' : 'receiveEmployeeId',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'RECEIVE_AUTOGRAPH_DATE',
'displayName' : '接诊医师签名日期',
'type' : 'date',
'javaName' : 'receiveAutographDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'REGISTER_ID',
'displayName' : '挂号id',
'type' : 'varchar(40)',
'javaName' : 'registerId',
'note' : '引用门诊挂号表T_APPOINTMENT挂号号',
'nullable':false,
'check':''},
{
'name' : 'RECEIVE_DATE',
'displayName' : '接诊时间',
'type' : 'date',
'javaName' : 'receiveDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'SERVICEPROVIDER',
'displayName' : '接诊科室',
'type' : 'varchar(40)',
'javaName' : 'serviceprovider',
'note' : '引用科室信息表T_DEPARTMENT院内科室id',
'nullable':false,
'check':''},
{
'name' : 'IF_OBSERVE',
'displayName' : '是否留观标志',
'type' : 'number(5)',
'javaName' : 'ifObserve',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'IF_RESCUE',
'displayName' : '是否抢救标志',
'type' : 'number(5)',
'javaName' : 'ifRescue',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'CHIEF',
'displayName' : '主诉',
'type' : 'text',
'javaName' : 'chief',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ILLNESS',
'displayName' : '现病史',
'type' : 'text',
'javaName' : 'illness',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HISTORY',
'displayName' : '既往史',
'type' : 'text',
'javaName' : 'history',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PER_HISTORY',
'displayName' : '个人史',
'type' : 'text',
'javaName' : 'perHistory',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MAR_HISTORY',
'displayName' : '婚姻史',
'type' : 'text',
'javaName' : 'marHistory',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CHILD_HISTORY',
'displayName' : '生育史',
'type' : 'text',
'javaName' : 'childHistory',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FAM_HISTORY',
'displayName' : '家族史',
'type' : 'text',
'javaName' : 'famHistory',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PHY_CHECKUP',
'displayName' : '体格检查',
'type' : 'text',
'javaName' : 'phyCheckup',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MANAGEMENT',
'displayName' : '处置',
'type' : 'text',
'javaName' : 'management',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IS_LOCAL_MARK',
'displayName' : '是否本地标志',
'type' : 'number(5)',
'javaName' : 'isLocalMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'NEWLY_MARK',
'displayName' : '初诊标志代码',
'type' : 'varchar(20)',
'javaName' : 'newlyMark',
'note' : '',
'nullable':false,
'check':'CV9900267'},
{
'name' : 'REFERRAL_MARK',
'displayName' : '是否转诊标志',
'type' : 'number(5)',
'javaName' : 'referralMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'GENERAL_HEALTH_MARK',
'displayName' : '患者既往健康状况代码',
'type' : 'varchar(20)',
'javaName' : 'generalHealthMark',
'note' : '',
'nullable':true,
'check':'GBT22613'},
{
'name' : 'PAST_DIS_HIS',
'displayName' : '既往健康状况及重要相关病史的描述',
'type' : 'text',
'javaName' : 'pastDisHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_CHRONIC_MARK',
'displayName' : '患者有无慢性病史',
'type' : 'varchar(20)',
'javaName' : 'inpatChronicMark',
'note' : '',
'nullable':true,
'check':'CV9900024'},
{
'name' : 'INPAT_INFECT_MARK',
'displayName' : '患者有无传染病史',
'type' : 'varchar(20)',
'javaName' : 'inpatInfectMark',
'note' : '',
'nullable':true,
'check':'CV9900024'},
{
'name' : 'INFECT_HISTORY',
'displayName' : '患者既往所患各种急性或慢性传染性疾病名称',
'type' : 'text',
'javaName' : 'infectHistory',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_TRAUMA_MARK',
'displayName' : '患者有无外伤史',
'type' : 'varchar(20)',
'javaName' : 'inpatTraumaMark',
'note' : '',
'nullable':true,
'check':'CV9900024'},
{
'name' : 'TRAUMA_HIS',
'displayName' : '对患者外伤史的描述',
'type' : 'text',
'javaName' : 'traumaHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIS_HIS',
'displayName' : '患者既往健康状况和疾病(含外伤) 的详细描述',
'type' : 'text',
'javaName' : 'disHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_VACCINATION_MARK',
'displayName' : '患者有无预防接种史',
'type' : 'varchar(20)',
'javaName' : 'inpatVaccinationMark',
'note' : '',
'nullable':true,
'check':'CV9900024'},
{
'name' : 'VACC_HIS',
'displayName' : '患者预防接种情况的详细描述',
'type' : 'text',
'javaName' : 'vaccHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_OP_MARK',
'displayName' : '患者有无手术史',
'type' : 'varchar(20)',
'javaName' : 'inpatOpMark',
'note' : '',
'nullable':true,
'check':'CV9900024'},
{
'name' : 'OP_HIS',
'displayName' : '患者既往接受手术/操作经历的详细描述',
'type' : 'text',
'javaName' : 'opHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_TRANSFUSION_MARK',
'displayName' : '患者有无输血史',
'type' : 'varchar(20)',
'javaName' : 'inpatTransfusionMark',
'note' : '',
'nullable':true,
'check':'CV9900024'},
{
'name' : 'TRANSFUSION_HIS',
'displayName' : '患者既往输血史的详细描述',
'type' : 'text',
'javaName' : 'transfusionHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_ALLE_MARK',
'displayName' : '患者有无过敏史',
'type' : 'varchar(20)',
'javaName' : 'inpatAlleMark',
'note' : '',
'nullable':true,
'check':'CV9900024'},
{
'name' : 'ALLE_HIS',
'displayName' : '患者既往发生过敏情况的详细描述',
'type' : 'text',
'javaName' : 'alleHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MENSES_HIS',
'displayName' : '月经史',
'type' : 'text',
'javaName' : 'mensesHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BODY_TEMPERATURE',
'displayName' : '体格检查：体温',
'type' : 'number(8)',
'javaName' : 'bodyTemperature',
'note' : '体温的测量值，计量单位为℃',
'nullable':true,
'check':''},
{
'name' : 'PR_FREQ',
'displayName' : '体格检查：脉搏',
'type' : 'number(8)',
'javaName' : 'prFreq',
'note' : '患者每分钟脉搏次数的测量值，计量单位为次/min',
'nullable':true,
'check':''},
{
'name' : 'BREATHE_FREQ',
'displayName' : '体格检查：呼吸',
'type' : 'number(8)',
'javaName' : 'breatheFreq',
'note' : '患者每分钟呼吸次数的测量值，计量单位为次/min',
'nullable':true,
'check':''},
{
'name' : 'SBP',
'displayName' : '体格检查：收缩压',
'type' : 'number(8)',
'javaName' : 'sbp',
'note' : '收缩压的测量值，计量单位为mmHg',
'nullable':true,
'check':''},
{
'name' : 'DBP',
'displayName' : '体格检查：舒张压',
'type' : 'number(8)',
'javaName' : 'dbp',
'note' : '舒张压的测量值，计量单位为mmHg',
'nullable':true,
'check':''},
{
'name' : 'BODY_HEIGHT',
'displayName' : '体格检查：身高',
'type' : 'number(8)',
'javaName' : 'bodyHeight',
'note' : '患者身高的测量值，计量单位为cm',
'nullable':true,
'check':''},
{
'name' : 'BODY_WEIGHT',
'displayName' : '体格检查：体重',
'type' : 'number(8)',
'javaName' : 'bodyWeight',
'note' : '患者体重的测量值，计量单位为kg',
'nullable':true,
'check':''},
{
'name' : 'GENERAL_SITU_EXAM_RESULT',
'displayName' : '体格检查：一般状况',
'type' : 'text',
'javaName' : 'generalSituExamResult',
'note' : '对患者一般状况检查结果的详细描述，包括其发育状况、营养状况、体味、步态、面容与表情、意识，检查能否合作等等',
'nullable':true,
'check':''},
{
'name' : 'SKIN',
'displayName' : '体格检查：皮肤粘膜',
'type' : 'text',
'javaName' : 'skin',
'note' : '对患者皮肤和黏膜检查结果的详细描述',
'nullable':true,
'check':''},
{
'name' : 'LN',
'displayName' : '体格检查：淋巴结',
'type' : 'text',
'javaName' : 'ln',
'note' : '对患者全身浅表淋巴检查结果的详细描述',
'nullable':true,
'check':''},
{
'name' : 'HEAD',
'displayName' : '体格检查：头部',
'type' : 'text',
'javaName' : 'head',
'note' : '对患者头部及其器官检查结果的详细描述',
'nullable':true,
'check':''},
{
'name' : 'NECK',
'displayName' : '体格检查：颈部',
'type' : 'text',
'javaName' : 'neck',
'note' : '对患者颈部检查结果的详细描述',
'nullable':true,
'check':''},
{
'name' : 'CHEST',
'displayName' : '体格检查：胸部',
'type' : 'text',
'javaName' : 'chest',
'note' : '对患者胸部(胸廊、肺部、心脏、血管)检查结果的详细描述，包括视触叩听的检查结呆',
'nullable':true,
'check':''},
{
'name' : 'LUNG_DIAG',
'displayName' : '体格检查：肺',
'type' : 'text',
'javaName' : 'lungDiag',
'note' : '患者肺部诊断结果的详细描述',
'nullable':true,
'check':''},
{
'name' : 'BELLY',
'displayName' : '体格检查：腹部',
'type' : 'text',
'javaName' : 'belly',
'note' : '对患者腹部(肝脾等)检查结果的详细描述，包括视触叩听的检查结果',
'nullable':true,
'check':''},
{
'name' : 'DRE_RESULT_DESCR',
'displayName' : '体格检查：肛门直肠',
'type' : 'text',
'javaName' : 'dreResultDescr',
'note' : '对患者肛门指诊检查结果的详细描述',
'nullable':true,
'check':''},
{
'name' : 'ANUS_PUDENDUM',
'displayName' : '体格检查：生殖器',
'type' : 'text',
'javaName' : 'anusPudendum',
'note' : '对患者外生殖器检查结果的详细描述',
'nullable':true,
'check':''},
{
'name' : 'SPINE',
'displayName' : '-体格检查：脊椎',
'type' : 'text',
'javaName' : 'spine',
'note' : '对患者脊柱检查结果的详细描述',
'nullable':true,
'check':''},
{
'name' : 'LIMBS',
'displayName' : '体格检查：四肢',
'type' : 'text',
'javaName' : 'limbs',
'note' : '对患者四肢检查结果的详细描述',
'nullable':true,
'check':''},
{
'name' : 'MENTAL',
'displayName' : '体格检查：神经系统',
'type' : 'text',
'javaName' : 'mental',
'note' : '对患者神经系统检查结果的详细描述',
'nullable':true,
'check':''},
{
'name' : 'RESPIRATORY_SYS',
'displayName' : '体格检查：呼吸系统',
'type' : 'text',
'javaName' : 'respiratorySys',
'note' : '对患者呼吸系统疾病的描述，如有无症状，有无呼吸系统慢性疾病',
'nullable':true,
'check':''},
{
'name' : 'CIRCULATION_SYS',
'displayName' : '体格检查：循环系统',
'type' : 'text',
'javaName' : 'circulationSys',
'note' : '对患者循环系统疾病的描述，如有无症状，有无病史',
'nullable':true,
'check':''},
{
'name' : 'DIGESTIVE_SYS',
'displayName' : '体格检查：消化系统',
'type' : 'text',
'javaName' : 'digestiveSys',
'note' : '对患者消化系统疾病的描述，如有无症状，有无病史',
'nullable':true,
'check':''},
{
'name' : 'URINARY_SYS',
'displayName' : '体格检查：泌尿系统',
'type' : 'text',
'javaName' : 'urinarySys',
'note' : '对患者泌尿系统疾病的描述，如有无症状，有无泌尿系统疾病',
'nullable':true,
'check':''},
{
'name' : 'HEMOPOIETIC_SYS',
'displayName' : '体格检查：造血系统',
'type' : 'text',
'javaName' : 'hemopoieticSys',
'note' : '对患者造血系统疾病的描述，如有无症状，有无病史',
'nullable':true,
'check':''},
{
'name' : 'ENDOCRINE_METABOLISM',
'displayName' : '体格检查：内分泌及代谢',
'type' : 'text',
'javaName' : 'endocrineMetabolism',
'note' : '对患者内分泌及代谢疾病的描述，如有无症状，有无内分泌疾病',
'nullable':true,
'check':''},
{
'name' : 'MUSCULOSKELETAL_SYS',
'displayName' : '体格检查：肌肉骨骼系统',
'type' : 'text',
'javaName' : 'musculoskeletalSys',
'note' : '对患者肌肉骨骼系统疾病的描述，如有无症状，有无肌肉骨骼疾病',
'nullable':true,
'check':''},
{
'name' : 'AC',
'displayName' : '患者腹部周长的测量值',
'type' : 'number(8)',
'javaName' : 'ac',
'note' : '计量单位为cm',
'nullable':true,
'check':''},
{
'name' : 'SPECIALIST_CHECKS',
'displayName' : '专科情况检查',
'type' : 'text',
'javaName' : 'specialistChecks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'THERAPEUTIC_PRINCIPLES',
'displayName' : '治则治法',
'type' : 'text',
'javaName' : 'therapeuticPrinciples',
'note' : '根据辨证结果采用的治则治法名称术语',
'nullable':true,
'check':''},
{
'name' : 'DIALECT_PROOF',
'displayName' : '辨证依据',
'type' : 'text',
'javaName' : 'dialectProof',
'note' : '中医证候辨证分型主要依据的详细描述',
'nullable':true,
'check':''},
{
'name' : 'CN_FOUR_RESULT',
'displayName' : '中医&quot;四诊&quot;观察结果',
'type' : 'text',
'javaName' : 'cnFourResult',
'note' : '中医四诊观察结果的详细描述，包括望、闻、问、切四诊内容',
'nullable':true,
'check':''},
{
'name' : 'OTHER_MEDICAL_TREATMENT',
'displayName' : '其他医学处置',
'type' : 'text',
'javaName' : 'otherMedicalTreatment',
'note' : '临床医师对患者实施的除检查/检验、用药、手术/操作以外的医学处置的描述',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_PROBLEM_EVAL',
'displayName' : '健康问题评估',
'type' : 'text',
'javaName' : 'healthProblemEval',
'note' : '根据患者疾病临床表现、实验室检查结果等作出的健康问题评估结果的详细描述',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_SERVICE_DEMAND',
'displayName' : '卫生服务要求',
'type' : 'text',
'javaName' : 'healthServiceDemand',
'note' : '患者就诊时对本人所患疾病提出的卫生服务要求的详细描述',
'nullable':true,
'check':''},
{
'name' : 'CONSULT_QUESTION',
'displayName' : '咨询问题',
'type' : 'text',
'javaName' : 'consultQuestion',
'note' : '对个体所患疾病提出的咨询问题的详细描述',
'nullable':true,
'check':''},
{
'name' : 'OUT_CODE',
'displayName' : '患者去向代码',
'type' : 'varchar(20)',
'javaName' : 'outCode',
'note' : '',
'nullable':true,
'check':'CV9900291'}
];