var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'ADULT_HEALTH_EXAMINATION_ID',
'displayName' : '成人健康体检id',
'type' : 'varchar(40)',
'javaName' : 'adultHealthExaminationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PHONE',
'displayName' : '联系方式',
'type' : 'varchar(20)',
'javaName' : 'phone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_STATE',
'displayName' : '家庭住址-省（自治区、直辖市）代码',
'type' : 'varchar(10)',
'javaName' : 'homeState',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_CITY',
'displayName' : '家庭住址-市（地区）代码',
'type' : 'varchar(10)',
'javaName' : 'homeCity',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_DISTRICT',
'displayName' : '家庭住址-县（区）代码',
'type' : 'varchar(10)',
'javaName' : 'homeDistrict',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_LINE',
'displayName' : '家庭住址-乡（镇、街道办事处）',
'type' : 'varchar(100)',
'javaName' : 'homeLine',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_ROAD',
'displayName' : '家庭住址-村（街、路、弄等）',
'type' : 'varchar(100)',
'javaName' : 'homeRoad',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_HOUSE_NO',
'displayName' : '家庭住址-门牌号码',
'type' : 'varchar(50)',
'javaName' : 'homeHouseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_TEXT',
'displayName' : '家庭住址-详细信息',
'type' : 'varchar(500)',
'javaName' : 'homeText',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SYMPTOM_DESCRIPTION',
'displayName' : '症状描述',
'type' : 'varchar(500)',
'javaName' : 'symptomDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SYMPTOM_CD',
'displayName' : '症状代码',
'type' : 'varchar(20)',
'javaName' : 'symptomCd',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'SYMPTOM_NAME',
'displayName' : '症状名称',
'type' : 'varchar(40)',
'javaName' : 'symptomName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ADMISSION_DIAGNOSIS_DATE',
'displayName' : '症状-诊断日期',
'type' : 'date',
'javaName' : 'admissionDiagnosisDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'BODY_TEMPERATURE',
'displayName' : '体温（℃）',
'type' : 'number(8)',
'javaName' : 'bodyTemperature',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PULSES',
'displayName' : '脉率（次/min）',
'type' : 'number(8)',
'javaName' : 'pulses',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BREATHING_RATE',
'displayName' : '呼吸频率（次/min）',
'type' : 'number(8)',
'javaName' : 'breathingRate',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LEFT_SYSTOLIC_PRESSURE',
'displayName' : '左侧收缩压（mmHg）',
'type' : 'number(8)',
'javaName' : 'leftSystolicPressure',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LEFT_DIASTOLIC_PRESSURE',
'displayName' : '左侧舒张压（mmHg）',
'type' : 'number(8)',
'javaName' : 'leftDiastolicPressure',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RIGHT_SYSTOLIC_PRESSURE',
'displayName' : '右侧收缩压（mmHg）',
'type' : 'number(8)',
'javaName' : 'rightSystolicPressure',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RIGHT_DIASTOLIC_PRESSURE',
'displayName' : '右侧舒张压（mmHg）',
'type' : 'number(8)',
'javaName' : 'rightDiastolicPressure',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PRENATAL_HEIGHT',
'displayName' : '身高（cm）',
'type' : 'number(8)',
'javaName' : 'prenatalHeight',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WEIGHT',
'displayName' : '体重（kg）',
'type' : 'number(8)',
'javaName' : 'weight',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WAIST',
'displayName' : '腰围（cm）',
'type' : 'number(8)',
'javaName' : 'waist',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BODY_MASS_INDEX',
'displayName' : '体质指数',
'type' : 'varchar(40)',
'javaName' : 'bodyMassIndex',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEART_RATE',
'displayName' : '心率（次/min）',
'type' : 'number(8)',
'javaName' : 'heartRate',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LIP_APPEARANCE_CODE',
'displayName' : '口唇外观检查结果代码',
'type' : 'varchar(20)',
'javaName' : 'lipAppearanceCode',
'note' : '',
'nullable':true,
'check':'CV0410007'},
{
'name' : 'DENTITION_CLASS_CODE',
'displayName' : '齿列类别代码',
'type' : 'varchar(20)',
'javaName' : 'dentitionClassCode',
'note' : '',
'nullable':true,
'check':'CV0410010'},
{
'name' : 'DENTITION_DESCRIPTION',
'displayName' : '齿列描述',
'type' : 'varchar(40)',
'javaName' : 'dentitionDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PHARYNGEAL_EXAMINATION_RESULT_CODE',
'displayName' : '咽部检查结果代码',
'type' : 'varchar(20)',
'javaName' : 'pharyngealExaminationResultCode',
'note' : '',
'nullable':true,
'check':'CV9900015'},
{
'name' : 'FAR_VISUAL_ACUITY',
'displayName' : '左眼裸眼远视力值',
'type' : 'number(8)',
'javaName' : 'farVisualAcuity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LEFT_CORRECTED_VISUAL_ACUITY',
'displayName' : '左眼矫正远视力值',
'type' : 'number(8)',
'javaName' : 'leftCorrectedVisualAcuity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RIGHT_CORRECTED_VISUAL_ACUITY',
'displayName' : '右眼矫正远视力值',
'type' : 'number(8)',
'javaName' : 'rightCorrectedVisualAcuity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FUNDUS_EXAMINATION_RESULTS_ABNORMAL_MARK',
'displayName' : '眼底检查结果异常标志',
'type' : 'number(5)',
'javaName' : 'fundusExaminationResultsAbnormalMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'FUNDUS_EXAMINATION_RESULTS_ABNORMAL_DESCRIBE',
'displayName' : '眼底检查结果异常描述',
'type' : 'varchar(40)',
'javaName' : 'fundusExaminationResultsAbnormalDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SCLERAL_EXAMINATION_RESULT_CODE',
'displayName' : '巩膜检查结果代码',
'type' : 'varchar(20)',
'javaName' : 'scleralExaminationResultCode',
'note' : '',
'nullable':true,
'check':'CV0410006'},
{
'name' : 'HEARING_TEST_RESULT_CODE',
'displayName' : '听力检测结果代码',
'type' : 'varchar(20)',
'javaName' : 'hearingTestResultCode',
'note' : '',
'nullable':true,
'check':'CV9900016'},
{
'name' : 'ABDOMINAL_TENDERNESS_SIGN',
'displayName' : '腹部压痛标志',
'type' : 'number(5)',
'javaName' : 'abdominalTendernessSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ABDOMINAL_TENDERNESS_DESCRIBE',
'displayName' : '腹部压痛描述',
'type' : 'varchar(40)',
'javaName' : 'abdominalTendernessDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ABDOMINAL_MASS_SIGN',
'displayName' : '腹部包块标志',
'type' : 'number(5)',
'javaName' : 'abdominalMassSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ABDOMINAL_MASS_DESCRIBE',
'displayName' : '腹部包块描述',
'type' : 'varchar(40)',
'javaName' : 'abdominalMassDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LIVER_SIGN',
'displayName' : '肝大标志',
'type' : 'number(5)',
'javaName' : 'liverSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'LIVER_DESCRIBE',
'displayName' : '肝大描述',
'type' : 'varchar(40)',
'javaName' : 'liverDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SPLENOMEGALY_SIGN',
'displayName' : '脾大标志',
'type' : 'number(5)',
'javaName' : 'splenomegalySign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'SPLENOMEGALY_DESCRIBE',
'displayName' : '脾大描述',
'type' : 'varchar(40)',
'javaName' : 'splenomegalyDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ABDOMINAL_SHIFTING_DULLNESS_SIGN',
'displayName' : '腹部移动性浊音标志',
'type' : 'number(5)',
'javaName' : 'abdominalShiftingDullnessSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ABDOMINAL_SHIFTING_DULLNESS_DESCRIBE',
'displayName' : '腹部移动性浊音描述',
'type' : 'varchar(40)',
'javaName' : 'abdominalShiftingDullnessDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MOTION_FUNCTION_STATUS_CODE',
'displayName' : '运动功能状态代码',
'type' : 'varchar(20)',
'javaName' : 'motionFunctionStatusCode',
'note' : '',
'nullable':true,
'check':'CV9900007'},
{
'name' : 'HEART_TYPE_CODE',
'displayName' : '心律类别代码',
'type' : 'varchar(20)',
'javaName' : 'heartTypeCode',
'note' : '',
'nullable':true,
'check':'CV9900008'},
{
'name' : 'CARDIAC_MURMUR_SIGN',
'displayName' : '心脏杂音标志',
'type' : 'number(5)',
'javaName' : 'cardiacMurmurSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'CARDIAC_MURMUR_DESCRIBE',
'displayName' : '心脏杂音描述',
'type' : 'varchar(40)',
'javaName' : 'cardiacMurmurDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DORSALIS_PEDIS_PULSE_CODE',
'displayName' : '足背动脉搏动代码',
'type' : 'varchar(20)',
'javaName' : 'dorsalisPedisPulseCode',
'note' : '',
'nullable':true,
'check':'CV0410015'},
{
'name' : 'LUNG_ABNORMAL_BREATH_SOUNDS_SIGN',
'displayName' : '肺部异常呼吸音标志',
'type' : 'number(5)',
'javaName' : 'lungAbnormalBreathSoundsSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'LUNG_ABNORMAL_BREATH_SOUNDS_DESCRIBE',
'displayName' : '肺部异常呼吸音描述',
'type' : 'varchar(40)',
'javaName' : 'lungAbnormalBreathSoundsDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LUNG_RALE_SIGN',
'displayName' : '肺部罗音标志',
'type' : 'number(5)',
'javaName' : 'lungRaleSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'LUNG_RALE_DESCRIBE',
'displayName' : '肺部罗音描述',
'type' : 'varchar(40)',
'javaName' : 'lungRaleDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BARREL_CHEST_SIGN',
'displayName' : '桶状胸标志',
'type' : 'number(5)',
'javaName' : 'barrelChestSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'SKIN_TEST_RESULT_CODE',
'displayName' : '皮肤检查结果代码',
'type' : 'varchar(20)',
'javaName' : 'skinTestResultCode',
'note' : '',
'nullable':true,
'check':'CV0410004'},
{
'name' : 'LYMPH_NODE_EXAMINATION_RESULT_CODE',
'displayName' : '淋巴结检查结果代码',
'type' : 'varchar(20)',
'javaName' : 'lymphNodeExaminationResultCode',
'note' : '',
'nullable':true,
'check':'CV0410011'},
{
'name' : 'LOWER_EXTREMITY_EDEMA_TEST_RESULT_CODE',
'displayName' : '下肢水肿检查结果代码',
'type' : 'varchar(20)',
'javaName' : 'lowerExtremityEdemaTestResultCode',
'note' : '',
'nullable':true,
'check':'CV0410014'},
{
'name' : 'ANAL_EXAMINATION_RESULTS_CODE',
'displayName' : '肛门指诊检查结果类别代码',
'type' : 'varchar(20)',
'javaName' : 'analExaminationResultsCode',
'note' : '',
'nullable':true,
'check':'CV0410013'},
{
'name' : 'BREAST_EXAMINATION_RESULTS_CODE',
'displayName' : '乳腺检查结果代码',
'type' : 'varchar(20)',
'javaName' : 'breastExaminationResultsCode',
'note' : '',
'nullable':true,
'check':'CV0410012'},
{
'name' : 'VULVA_ABNORMALITY_SIGN',
'displayName' : '外阴异常标志',
'type' : 'number(5)',
'javaName' : 'vulvaAbnormalitySign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'VULVA_ABNORMALITY_DESCRIBE',
'displayName' : '外阴异常描述',
'type' : 'varchar(40)',
'javaName' : 'vulvaAbnormalityDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ABNORMAL_VAGINA_SIGN',
'displayName' : '阴道异常标志',
'type' : 'number(5)',
'javaName' : 'abnormalVaginaSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ABNORMAL_VAGINA_DESCRIBE',
'displayName' : '阴道异常描述',
'type' : 'varchar(40)',
'javaName' : 'abnormalVaginaDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CERVICAL_ABNORMALITY_SIGN',
'displayName' : '宫颈异常标志',
'type' : 'number(5)',
'javaName' : 'cervicalAbnormalitySign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'CERVICAL_ABNORMALITY_DESCRIBE',
'displayName' : '宫颈异常描述',
'type' : 'varchar(40)',
'javaName' : 'cervicalAbnormalityDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UTERINE_BODY_ABNORMAL_SIGN',
'displayName' : '宫体异常标志',
'type' : 'number(5)',
'javaName' : 'uterineBodyAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'UTERINE_BODY_ABNORMAL_DESCRIBE',
'displayName' : '宫体异常描述',
'type' : 'varchar(40)',
'javaName' : 'uterineBodyAbnormalDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ENCLOSURE_ABNORMAL_SIGN',
'displayName' : '附件异常标志',
'type' : 'number(5)',
'javaName' : 'enclosureAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ENCLOSURE_ABNORMAL_DESCRIBE',
'displayName' : '附件异常描述',
'type' : 'varchar(40)',
'javaName' : 'enclosureAbnormalDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEMOGLOBIN',
'displayName' : '血红蛋白',
'type' : 'number(8)',
'javaName' : 'hemoglobin',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WHITE_BLOOD_CELL',
'displayName' : '白细胞',
'type' : 'number(8)',
'javaName' : 'whiteBloodCell',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PLATELET',
'displayName' : '血小板',
'type' : 'number(8)',
'javaName' : 'platelet',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'URINE_PROTEIN_QUALITATIVE_TEST_RESULT_CODE',
'displayName' : '尿蛋白定性检测结果代码',
'type' : 'varchar(20)',
'javaName' : 'urineProteinQualitativeTestResultCode',
'note' : '',
'nullable':true,
'check':'CV0450015'},
{
'name' : 'NIAOTANG_QUALITATIVE_TEST_RESULT_CODE',
'displayName' : '尿糖定性检测结果代码',
'type' : 'varchar(20)',
'javaName' : 'niaotangQualitativeTestResultCode',
'note' : '',
'nullable':true,
'check':'CV0450015'},
{
'name' : 'URINE_KETONE_QUALITATIVE_TEST_RESULT_CODE',
'displayName' : '尿酮体定性检测结果代码',
'type' : 'varchar(20)',
'javaName' : 'urineKetoneQualitativeTestResultCode',
'note' : '',
'nullable':true,
'check':'CV0450015'},
{
'name' : 'BLD_QUALITATIVE_TEST_RESULT_CODE',
'displayName' : '尿潜血定性检测结果代码',
'type' : 'varchar(20)',
'javaName' : 'bldQualitativeTestResultCode',
'note' : '',
'nullable':true,
'check':'CV0450015'},
{
'name' : 'BLOOD_SUGAR',
'displayName' : '血糖检测值（mmol/L）',
'type' : 'number(8)',
'javaName' : 'bloodSugar',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'URINE_MICROALBUMIN',
'displayName' : '尿微量白蛋白(mg/dL)',
'type' : 'number(8)',
'javaName' : 'urineMicroalbumin',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FECAL_OCCULT_BLOOD',
'displayName' : '大便潜血',
'type' : 'number(8)',
'javaName' : 'fecalOccultBlood',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'GLYCOSYLATED_HEMOGLOBIN',
'displayName' : '糖化血红蛋白(%)',
'type' : 'number(8)',
'javaName' : 'glycosylatedHemoglobin',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SERUM_ALANINE_AMINOTRANSFERASE',
'displayName' : '血清谷丙转氨酶',
'type' : 'number(8)',
'javaName' : 'serumAlanineAminotransferase',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SERUM_ASPARTATE_AMINOTRANSFERASE',
'displayName' : '血清谷草转氨酶',
'type' : 'number(8)',
'javaName' : 'serumAspartateAminotransferase',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ALBUMIN',
'displayName' : '白蛋白(mg/dL)',
'type' : 'number(8)',
'javaName' : 'albumin',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TOTAL_BILIRUBIN',
'displayName' : '总胆红素',
'type' : 'number(8)',
'javaName' : 'totalBilirubin',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONJUGATED_BILIRUBIN',
'displayName' : '结合胆红素',
'type' : 'number(8)',
'javaName' : 'conjugatedBilirubin',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SCR',
'displayName' : '血清肌酐',
'type' : 'number(8)',
'javaName' : 'scr',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BLOOD_UREA_NITROGEN',
'displayName' : '血尿素氮',
'type' : 'number(8)',
'javaName' : 'bloodUreaNitrogen',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BLOOD_POTASSIUM_CONCENTRATION',
'displayName' : '血钾浓度(mmol/L)',
'type' : 'number(8)',
'javaName' : 'bloodPotassiumConcentration',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SERUM_SODIUM_CONCENTRATION',
'displayName' : '血钠浓度(mmol/L)',
'type' : 'number(8)',
'javaName' : 'serumSodiumConcentration',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TOTAL_CHOLESTEROL',
'displayName' : '总胆固醇(mmol/L)',
'type' : 'number(8)',
'javaName' : 'totalCholesterol',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRIGLYCERIDE',
'displayName' : '甘油三酯(mmol/L)',
'type' : 'number(8)',
'javaName' : 'triglyceride',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SERUM_LOW_DENSITY_LIPOPROTEIN_CHOLESTEROL',
'displayName' : '血清低密度酯蛋白胆固醇(mmol/L)',
'type' : 'number(8)',
'javaName' : 'serumLowDensityLipoproteinCholesterol',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEPATITIS_B_SURFACE_ANTIGEN',
'displayName' : '乙型肝炎表面抗原定性检测结果分类代码',
'type' : 'varchar(20)',
'javaName' : 'hepatitisBSurfaceAntigen',
'note' : '',
'nullable':true,
'check':'CV990107'},
{
'name' : 'HEPATITIS_B_SURFACE_ANTIBODY',
'displayName' : '乙型肝炎表面抗体定性检测结果分类代码',
'type' : 'varchar(20)',
'javaName' : 'hepatitisBSurfaceAntibody',
'note' : '',
'nullable':true,
'check':'CV990107'},
{
'name' : 'HEPATITIS_B_E_ANTIGEN',
'displayName' : '乙型肝炎e抗原定性检测结果分类代码',
'type' : 'varchar(20)',
'javaName' : 'hepatitisBEAntigen',
'note' : '',
'nullable':true,
'check':'CV990107'},
{
'name' : 'HEPATITIS_B_E_ANTIBODY',
'displayName' : '乙型肝炎e抗体定性检测结果分类代码',
'type' : 'varchar(20)',
'javaName' : 'hepatitisBEAntibody',
'note' : '',
'nullable':true,
'check':'CV990107'},
{
'name' : 'HEPATITIS_B_CORE_ANTIBODY',
'displayName' : '乙型肝炎核心抗体定性检测结果分类代码',
'type' : 'varchar(20)',
'javaName' : 'hepatitisBCoreAntibody',
'note' : '',
'nullable':true,
'check':'CV990107'},
{
'name' : 'ABNORMAL_CHEST_X_RAY_SIGN',
'displayName' : '胸部X线检查异常标志',
'type' : 'number(5)',
'javaName' : 'abnormalChestXRaySign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ABNORMAL_CHEST_X_RAY_DESCRIBE',
'displayName' : '胸部X线检查异常描述',
'type' : 'varchar(40)',
'javaName' : 'abnormalChestXRayDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ECG_ABNORMALITY_SIGN',
'displayName' : '心电图异常标志',
'type' : 'number(5)',
'javaName' : 'ecgAbnormalitySign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ECG_ABNORMALITY_DESCRIBE',
'displayName' : '心电图异常描述',
'type' : 'varchar(40)',
'javaName' : 'ecgAbnormalityDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ABNORMAL_ULTRASONOGRAPHY_SIGN',
'displayName' : 'B超检查异常标志',
'type' : 'number(5)',
'javaName' : 'abnormalUltrasonographySign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ABNORMAL_ULTRASONOGRAPHY_DESCRIBE',
'displayName' : 'B超检查异常描述',
'type' : 'varchar(40)',
'javaName' : 'abnormalUltrasonographyDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CERVICAL_SMEAR_ABNORMALITY_SIGN',
'displayName' : '宫颈涂片异常标志',
'type' : 'number(5)',
'javaName' : 'cervicalSmearAbnormalitySign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'CERVICAL_SMEAR_ABNORMALITY_DESCRIBE',
'displayName' : '宫颈涂片异常描述',
'type' : 'varchar(40)',
'javaName' : 'cervicalSmearAbnormalityDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FAMILY_DISEASE_NAME_CODE',
'displayName' : '家族性疾病名称代码',
'type' : 'varchar(20)',
'javaName' : 'familyDiseaseNameCode',
'note' : '',
'nullable':true,
'check':'CV0210005'},
{
'name' : 'REGISTERED_MEDICAL_INSTITUTION_NAME',
'displayName' : '曾住院医疗机构名称',
'type' : 'varchar(40)',
'javaName' : 'registeredMedicalInstitutionName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_MEDICAL_RECORD_NUMBER',
'displayName' : '曾住院病案号',
'type' : 'varchar(40)',
'javaName' : 'inpatientMedicalRecordNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOSPITALIZATION_CAUSES',
'displayName' : '住院原因',
'type' : 'varchar(200)',
'javaName' : 'hospitalizationCauses',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ONCE_ESTABLISH_FAMILY_BED_ORG_NAME',
'displayName' : '曾建立家庭病床医疗机构名称',
'type' : 'varchar(40)',
'javaName' : 'onceEstablishFamilyBedOrgName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ONCE_ESTABLISH_FAMILY_BED_MEDICAL_RECORD_NUMBER',
'displayName' : '曾建立家庭病床病案号',
'type' : 'varchar(40)',
'javaName' : 'onceEstablishFamilyBedMedicalRecordNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ESTABLISH_FAMILY_BEDS_REASON',
'displayName' : '家庭病床建立原因',
'type' : 'varchar(200)',
'javaName' : 'establishFamilyBedsReason',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INOCULATION_TIME',
'displayName' : '接种时间',
'type' : 'date',
'javaName' : 'inoculationTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'IMMUNE_DOSE',
'displayName' : '免疫剂次',
'type' : 'number(8)',
'javaName' : 'immuneDose',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACCINE_NAME_CODE',
'displayName' : '疫苗编码',
'type' : 'varchar(20)',
'javaName' : 'vaccineNameCode',
'note' : '',
'nullable':true,
'check':'CV0850001'},
{
'name' : 'VACCINE_BATCH',
'displayName' : '疫苗批次',
'type' : 'varchar(40)',
'javaName' : 'vaccineBatch',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACCINE_MANUFACTURERS',
'displayName' : '疫苗的生产厂家',
'type' : 'varchar(40)',
'javaName' : 'vaccineManufacturers',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACCINATION_PHYSICIAN',
'displayName' : '免疫接种医师',
'type' : 'varchar(40)',
'javaName' : 'vaccinationPhysician',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INOCULATION_MECHANISM',
'displayName' : '接种机构师',
'type' : 'varchar(40)',
'javaName' : 'inoculationMechanism',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OCCUPATIONAL_EXPOSURE_TO_HAZARDOUS_FACTORS',
'displayName' : '有危害因素接触职业描述',
'type' : 'varchar(500)',
'javaName' : 'occupationalExposureToHazardousFactors',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ENGAGED_IN_HAZARDOUS_FACTORS',
'displayName' : '从事有危害因素职业时长(年)',
'type' : 'number(8)',
'javaName' : 'engagedInHazardousFactors',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OCCUPATIONAL_HAZARD_FACTORS_CODE',
'displayName' : '职业病危害因素类别代码',
'type' : 'varchar(20)',
'javaName' : 'occupationalHazardFactorsCode',
'note' : '',
'nullable':true,
'check':'CV0300203'},
{
'name' : 'OCCUPATIONAL_EXPOSURE_RISK_FACTORS_NAME',
'displayName' : '职业暴露危险因素名称',
'type' : 'varchar(200)',
'javaName' : 'occupationalExposureRiskFactorsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OCCUPATIONAL_PROTECTION_MEASURES',
'displayName' : '职业防护措施标志',
'type' : 'number(5)',
'javaName' : 'occupationalProtectionMeasures',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'PHYSICAL_ACTIVITY_FREQUENCY_CODE',
'displayName' : '身体活动频率代码',
'type' : 'varchar(20)',
'javaName' : 'physicalActivityFrequencyCode',
'note' : '',
'nullable':true,
'check':'CV0300111'},
{
'name' : 'EACH_EXERCISE_TIME',
'displayName' : '每次锻炼时间（min）',
'type' : 'number(8)',
'javaName' : 'eachExerciseTime',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ADHERE_TO_EXERCISE_TIME',
'displayName' : '坚持锻炼时间（年）',
'type' : 'number(8)',
'javaName' : 'adhereToExerciseTime',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EXERCISE_MODE',
'displayName' : '锻炼方式',
'type' : 'varchar(200)',
'javaName' : 'exerciseMode',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIET_CODE',
'displayName' : '饮食习惯代码',
'type' : 'varchar(20)',
'javaName' : 'dietCode',
'note' : '',
'nullable':true,
'check':'CV0300107'},
{
'name' : 'SMOKING_STATUS',
'displayName' : '吸烟状况',
'type' : 'varchar(200)',
'javaName' : 'smokingStatus',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DAY_SMOKING_AMOUNT',
'displayName' : '日吸烟量',
'type' : 'number(8)',
'javaName' : 'daySmokingAmount',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'START_SMOKING_AGE',
'displayName' : '开始吸烟年龄（岁）',
'type' : 'number(8)',
'javaName' : 'startSmokingAge',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SMOKING_CESSATION_AGE',
'displayName' : '戒烟年龄（岁）',
'type' : 'number(8)',
'javaName' : 'smokingCessationAge',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRINKING_FREQUENCY',
'displayName' : '饮酒频率代码',
'type' : 'varchar(20)',
'javaName' : 'drinkingFrequency',
'note' : '',
'nullable':true,
'check':'CV0300104'},
{
'name' : 'DRINKING_PER_DAY',
'displayName' : '日饮酒量（mL）',
'type' : 'number(8)',
'javaName' : 'drinkingPerDay',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IF_DRINKING',
'displayName' : '饮酒标志',
'type' : 'number(5)',
'javaName' : 'ifDrinking',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ABSTINENCE_AGE',
'displayName' : '戒酒年龄（岁）',
'type' : 'number(8)',
'javaName' : 'abstinenceAge',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRINKING_AGE',
'displayName' : '开始饮酒年龄（岁）',
'type' : 'number(8)',
'javaName' : 'drinkingAge',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ABSTINENCE_SIGN',
'displayName' : '戒酒标志',
'type' : 'number(5)',
'javaName' : 'abstinenceSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'DRINKING_TYPE_CODE',
'displayName' : '饮酒种类代码',
'type' : 'varchar(20)',
'javaName' : 'drinkingTypeCode',
'note' : '',
'nullable':true,
'check':'CV0300105'},
{
'name' : 'ELDERLY_HEALTH_STATUS_ASSESSMENT_CODE',
'displayName' : '老年人健康状态自我评估代码',
'type' : 'varchar(20)',
'javaName' : 'elderlyHealthStatusAssessmentCode',
'note' : '',
'nullable':true,
'check':'CV0401013'},
{
'name' : 'ELDERLY_SELF_ASSESSMENT_CODE',
'displayName' : '老年人生活自理能力自我评估代码',
'type' : 'varchar(20)',
'javaName' : 'elderlySelfAssessmentCode',
'note' : '',
'nullable':true,
'check':'CV0401014'},
{
'name' : 'SCREENING_COGNITIVE_STATE_CLASSIFICATION_CODE',
'displayName' : '认知状态粗筛结果分类代码',
'type' : 'varchar(20)',
'javaName' : 'screeningCognitiveStateClassificationCode',
'note' : '',
'nullable':true,
'check':'CV9900010'},
{
'name' : 'COGNITIVE_FUNCTION_SCORE',
'displayName' : '老年人认知功能评分',
'type' : 'number(8)',
'javaName' : 'cognitiveFunctionScore',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'THE_EMOTIONAL_STATE_OF_COARSE_CODE',
'displayName' : '情感状态粗筛结果代码',
'type' : 'varchar(20)',
'javaName' : 'theEmotionalStateOfCoarseCode',
'note' : '',
'nullable':true,
'check':'CV9900010'},
{
'name' : 'GERIATRIC_DEPRESSION_SCORE',
'displayName' : '老年人抑郁评分',
'type' : 'number(8)',
'javaName' : 'geriatricDepressionScore',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_EVALUATION_ABNORMAL_SIGNS',
'displayName' : '健康评价异常标志',
'type' : 'number(5)',
'javaName' : 'healthEvaluationAbnormalSigns',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'HEALTH_EVALUATION_EXCEPTION_DESCRIPTION',
'displayName' : '健康评价异常描述',
'type' : 'varchar(40)',
'javaName' : 'healthEvaluationExceptionDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_INSTRUCTION_CODE',
'displayName' : '健康指导代码',
'type' : 'varchar(20)',
'javaName' : 'healthInstructionCode',
'note' : '',
'nullable':true,
'check':'CV9900017'},
{
'name' : 'RISK_FACTOR_CONTROL_CODE',
'displayName' : '危险因素控制建议代码',
'type' : 'varchar(20)',
'javaName' : 'riskFactorControlCode',
'note' : '',
'nullable':true,
'check':'CV0600218'},
{
'name' : 'DIAGNOSIS',
'displayName' : '诊断编码',
'type' : 'varchar(20)',
'javaName' : 'diagnosis',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'DIAGNOSIS_NAME',
'displayName' : '诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'diagnosisName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIAGNOSIS_DATE',
'displayName' : '诊断日期',
'type' : 'date',
'javaName' : 'diagnosisDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'TCM_CONSTITUTION_CLASSIFICATION_CODE',
'displayName' : '中医体质分类代码',
'type' : 'varchar(20)',
'javaName' : 'tcmConstitutionClassificationCode',
'note' : '',
'nullable':true,
'check':'CV0501005'},
{
'name' : 'TCM_CONSTITUTION_CLASSIFICATION_RESULT_CODE',
'displayName' : '中医体质分类判定结果代码',
'type' : 'varchar(20)',
'javaName' : 'tcmConstitutionClassificationResultCode',
'note' : '',
'nullable':true,
'check':'CV9900018'},
{
'name' : 'FREQ_CODE',
'displayName' : '频率代码',
'type' : 'varchar(20)',
'javaName' : 'freqCode',
'note' : '',
'nullable':true,
'check':'CV9900341'},
{
'name' : 'MEDICATION_COMPLIANCE_CODE',
'displayName' : '服药依从性代码',
'type' : 'varchar(20)',
'javaName' : 'medicationComplianceCode',
'note' : '',
'nullable':true,
'check':'CV9900004'},
{
'name' : 'MEDICATION_CD',
'displayName' : '院内药物编码',
'type' : 'varchar(20)',
'javaName' : 'medicationCd',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEDICATION_NAME',
'displayName' : '院内药物名称',
'type' : 'varchar(40)',
'javaName' : 'medicationName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRUG_DOSAGE_FORMS',
'displayName' : '药物剂型代码',
'type' : 'varchar(20)',
'javaName' : 'drugDosageForms',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRUG_DOSAGE_FORMS_NAME',
'displayName' : '药物剂型名称',
'type' : 'varchar(40)',
'javaName' : 'drugDosageFormsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'START',
'displayName' : '医嘱开始时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DURATION',
'displayName' : '执行天数',
'type' : 'number(8)',
'javaName' : 'duration',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOSAGE_CODE',
'displayName' : '用药途径代码',
'type' : 'varchar(20)',
'javaName' : 'dosageCode',
'note' : '',
'nullable':true,
'check':'CV0600102'},
{
'name' : 'C_MED_CODE',
'displayName' : '特殊用法代码',
'type' : 'varchar(20)',
'javaName' : 'cMedCode',
'note' : '',
'nullable':true,
'check':'CV9900285'},
{
'name' : 'ONCE_VALUE',
'displayName' : '用药次剂量',
'type' : 'number(8)',
'javaName' : 'onceValue',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ONCE_UNIT',
'displayName' : '用药次剂量单位',
'type' : 'varchar(20)',
'javaName' : 'onceUnit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];