var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'SEVERE_PSYCHOSIS_PATIENTS_FOLLOW_UP_SERVICE_ID',
'displayName' : '重性精神病患者随访服务id',
'type' : 'varchar(40)',
'javaName' : 'severePsychosisPatientsFollowUpServiceId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PHONE',
'displayName' : '联系方式',
'type' : 'varchar(20)',
'javaName' : 'phone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_STATE',
'displayName' : '家庭住址-省（自治区、直辖市）代码',
'type' : 'varchar(10)',
'javaName' : 'homeState',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_CITY',
'displayName' : '家庭住址-市（地区）代码',
'type' : 'varchar(10)',
'javaName' : 'homeCity',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_DISTRICT',
'displayName' : '家庭住址-县（区）代码',
'type' : 'varchar(10)',
'javaName' : 'homeDistrict',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_LINE',
'displayName' : '家庭住址-乡（镇、街道办事处）',
'type' : 'varchar(100)',
'javaName' : 'homeLine',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_ROAD',
'displayName' : '家庭住址-村（街、路、弄等）',
'type' : 'varchar(100)',
'javaName' : 'homeRoad',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_HOUSE_NO',
'displayName' : '家庭住址-门牌号码',
'type' : 'varchar(50)',
'javaName' : 'homeHouseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_TEXT',
'displayName' : '家庭住址-详细信息',
'type' : 'varchar(500)',
'javaName' : 'homeText',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SEVERE_MENTAL_ILLNESS_PATIENTS_VISIT_SIGNS',
'displayName' : '重性精神疾病患者访到标志',
'type' : 'number(5)',
'javaName' : 'severeMentalIllnessPatientsVisitSigns',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'STD_SMI_DANGER_LEVEL',
'displayName' : '重性精神疾病患者危险性分级代码',
'type' : 'varchar(20)',
'javaName' : 'stdSmiDangerLevel',
'note' : '',
'nullable':true,
'check':'CV0510013'},
{
'name' : 'MENTAL_SYMPTOM_CODE',
'displayName' : '精神症状代码',
'type' : 'varchar(20)',
'javaName' : 'mentalSymptomCode',
'note' : '',
'nullable':true,
'check':'CV0401009'},
{
'name' : 'INSIGHT_EVALUATION_RESULT_CODE',
'displayName' : '自知力评价结果代码',
'type' : 'varchar(20)',
'javaName' : 'insightEvaluationResultCode',
'note' : '',
'nullable':true,
'check':'CV9900013'},
{
'name' : 'SLEEP_CODE',
'displayName' : '睡眠情况代码',
'type' : 'varchar(20)',
'javaName' : 'sleepCode',
'note' : '',
'nullable':true,
'check':'CV9900031'},
{
'name' : 'DIETARY_STATUS',
'displayName' : '饮食情况代码',
'type' : 'varchar(20)',
'javaName' : 'dietaryStatus',
'note' : '',
'nullable':true,
'check':'CV9900003'},
{
'name' : 'SOCIAL_FUNCTION_CLASSIFICATION_CODE',
'displayName' : '社会功能情况分类代码',
'type' : 'varchar(20)',
'javaName' : 'socialFunctionClassificationCode',
'note' : '',
'nullable':true,
'check':'CV0510003'},
{
'name' : 'SOCIAL_FUNCTION_EVALUATION_CODE',
'displayName' : '社会功能情况评价代码',
'type' : 'varchar(20)',
'javaName' : 'socialFunctionEvaluationCode',
'note' : '',
'nullable':true,
'check':'CV9900031'},
{
'name' : 'MENTAL_ILLNESS_ON_FAMILY_SOCIETY_IMPACT',
'displayName' : '患重性精神疾病对家庭社会的影响代码',
'type' : 'varchar(20)',
'javaName' : 'mentalIllnessOnFamilySocietyImpact',
'note' : '',
'nullable':true,
'check':'CV0300112'},
{
'name' : 'ILLNESS_ON_FAMILY_SOCIETY_INFLUENCE_TIMES',
'displayName' : '患病对家庭社会的影响次数',
'type' : 'number(4)',
'javaName' : 'illnessOnFamilySocietyInfluenceTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LOCK_CASE_CODE',
'displayName' : '关锁情况代码',
'type' : 'varchar(20)',
'javaName' : 'lockCaseCode',
'note' : '',
'nullable':true,
'check':'CV9900020'},
{
'name' : 'INPATIENT_CODE',
'displayName' : '住院情况的代码',
'type' : 'varchar(20)',
'javaName' : 'inpatientCode',
'note' : '',
'nullable':true,
'check':'CV9900125'},
{
'name' : 'AUXILIARY_INSPECTION_MARK',
'displayName' : '辅助检查标志',
'type' : 'number(5)',
'javaName' : 'auxiliaryInspectionMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'AUXILIARY_EXAMINATION_PROJECT',
'displayName' : '辅助检查项目',
'type' : 'varchar(200)',
'javaName' : 'auxiliaryExaminationProject',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TEST_DATE',
'displayName' : '检测日期',
'type' : 'date',
'javaName' : 'testDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AUXILIARY_EXAMINATION_RESULTS',
'displayName' : '辅助检查结果',
'type' : 'varchar(40)',
'javaName' : 'auxiliaryExaminationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FOLLOWUP_EVALUATION_RESULTS_CODE',
'displayName' : '随访评价结果代码',
'type' : 'varchar(20)',
'javaName' : 'followupEvaluationResultsCode',
'note' : '',
'nullable':true,
'check':'CV0510012'},
{
'name' : 'PSYCHIATRIC_REHABILITATION_CODE',
'displayName' : '精神康复措施代码',
'type' : 'varchar(20)',
'javaName' : 'psychiatricRehabilitationCode',
'note' : '',
'nullable':true,
'check':'CV0600209'},
{
'name' : 'REFERRAL_MARK',
'displayName' : '转诊标志',
'type' : 'number(5)',
'javaName' : 'referralMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'REFERRAL_REASONS',
'displayName' : '转诊原因',
'type' : 'varchar(40)',
'javaName' : 'referralReasons',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REFERRAL_IN_ORG',
'displayName' : '转入机构的名称',
'type' : 'varchar(40)',
'javaName' : 'referralInOrg',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REFERRAL_IN_DEP',
'displayName' : '转入科室的名称',
'type' : 'varchar(40)',
'javaName' : 'referralInDep',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NEXT_FOLLOW_UP_DATE',
'displayName' : '下次随访日期',
'type' : 'date',
'javaName' : 'nextFollowUpDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CN_MEDICATION_TYPE_CODE',
'displayName' : '中药使用类别代码',
'type' : 'varchar(20)',
'javaName' : 'cnMedicationTypeCode',
'note' : '',
'nullable':true,
'check':'CV0600101'},
{
'name' : 'FREQ_CODE',
'displayName' : '频率代码',
'type' : 'varchar(20)',
'javaName' : 'freqCode',
'note' : '',
'nullable':true,
'check':'CV9900341'},
{
'name' : 'MEDICATION_COMPLIANCE_CODE',
'displayName' : '服药依从性代码',
'type' : 'varchar(20)',
'javaName' : 'medicationComplianceCode',
'note' : '',
'nullable':true,
'check':'CV9900004'},
{
'name' : 'DRUG_ADVERSE_REACTION',
'displayName' : '药物不良反应情况',
'type' : 'varchar(200)',
'javaName' : 'drugAdverseReaction',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRUG_TOTAL_DOSE',
'displayName' : '药物使用总剂量',
'type' : 'number(8)',
'javaName' : 'drugTotalDose',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRUG_TOTAL_DOSE_UTIL',
'displayName' : '药物使用总剂量单位',
'type' : 'varchar(40)',
'javaName' : 'drugTotalDoseUtil',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEDICATION_CD',
'displayName' : '院内药物编码',
'type' : 'varchar(20)',
'javaName' : 'medicationCd',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEDICATION_NAME',
'displayName' : '院内药物名称',
'type' : 'varchar(40)',
'javaName' : 'medicationName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRUG_DOSAGE_FORMS',
'displayName' : '药物剂型代码',
'type' : 'varchar(20)',
'javaName' : 'drugDosageForms',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRUG_DOSAGE_FORMS_NAME',
'displayName' : '药物剂型名称',
'type' : 'varchar(40)',
'javaName' : 'drugDosageFormsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'START',
'displayName' : '医嘱开始时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DURATION',
'displayName' : '执行天数',
'type' : 'number(8)',
'javaName' : 'duration',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOSAGE_CODE',
'displayName' : '用药途径代码',
'type' : 'varchar(20)',
'javaName' : 'dosageCode',
'note' : '',
'nullable':true,
'check':'CV0600102'},
{
'name' : 'C_MED_CODE',
'displayName' : '特殊用法代码',
'type' : 'varchar(20)',
'javaName' : 'cMedCode',
'note' : '',
'nullable':true,
'check':'CV9900285'},
{
'name' : 'ONCE_VALUE',
'displayName' : '用药次剂量',
'type' : 'number(8)',
'javaName' : 'onceValue',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ONCE_UNIT',
'displayName' : '用药次剂量单位',
'type' : 'varchar(20)',
'javaName' : 'onceUnit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];