var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'ANAESTHESIA_RECORD_ID',
'displayName' : '院内麻醉记录id',
'type' : 'varchar(40)',
'javaName' : 'anaesthesiaRecordId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'TELECOM',
'displayName' : '电话号码',
'type' : 'varchar(20)',
'javaName' : 'telecom',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_TYPE',
'displayName' : '患者类型',
'type' : 'varchar(20)',
'javaName' : 'patientType',
'note' : '',
'nullable':true,
'check':'CV0900404'},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISIT_MARK',
'displayName' : '门诊或住院标识',
'type' : 'varchar(10)',
'javaName' : 'visitMark',
'note' : '',
'nullable':false,
'check':'CUS00010'},
{
'name' : 'REGISTRATION_ID',
'displayName' : '就诊流水号',
'type' : 'varchar(40)',
'javaName' : 'registrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_TIME',
'displayName' : '就诊时间',
'type' : 'date',
'javaName' : 'visitingTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'VISITING_TYPE',
'displayName' : '就诊类型',
'type' : 'varchar(20)',
'javaName' : 'visitingType',
'note' : '',
'nullable':true,
'check':'CV9900340'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANAESTHETIC',
'displayName' : '麻醉医师id',
'type' : 'varchar(40)',
'javaName' : 'anaesthetic',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANAESTHETIC_NAME',
'displayName' : '麻醉医师姓名',
'type' : 'varchar(20)',
'javaName' : 'anaestheticName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANAESTHETIC_SIGN_DATE',
'displayName' : '麻醉医师签名日期',
'type' : 'date',
'javaName' : 'anaestheticSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ABO_CD',
'displayName' : 'ABO血型代码',
'type' : 'varchar(20)',
'javaName' : 'aboCd',
'note' : '',
'nullable':true,
'check':'CV0450005'},
{
'name' : 'RH_CD',
'displayName' : 'RH血型代码',
'type' : 'varchar(20)',
'javaName' : 'rhCd',
'note' : '',
'nullable':true,
'check':'CV0450020'},
{
'name' : 'PREOPERATIVE_DIAGNOSIS',
'displayName' : '术前诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'preoperativeDiagnosis',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'PREOPERATIVE_DIAGNOSIS_NAME',
'displayName' : '术前诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'preoperativeDiagnosisName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PREOPERATIVE_DIAGNOSIS_DATE',
'displayName' : '术前诊断-诊断日期',
'type' : 'date',
'javaName' : 'preoperativeDiagnosisDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AFTER_OPERATION_DIAGNOSIS',
'displayName' : '术后诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'afterOperationDiagnosis',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'AFTER_OPERATION_DIAGNOSIS_NAME',
'displayName' : '术后诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'afterOperationDiagnosisName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AFTER_OPERATION_DIAGNOSIS_DATE',
'displayName' : '术后诊断-诊断日期',
'type' : 'date',
'javaName' : 'afterOperationDiagnosisDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DRUGS_USAGE',
'displayName' : '药物用法',
'type' : 'varchar(100)',
'javaName' : 'drugsUsage',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FREQ_CODE',
'displayName' : '频率代码',
'type' : 'varchar(20)',
'javaName' : 'freqCode',
'note' : '',
'nullable':true,
'check':'CV9900341'},
{
'name' : 'DRUG_TOTAL_DOSE',
'displayName' : '药物使用总剂量',
'type' : 'number(8)',
'javaName' : 'drugTotalDose',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRUG_TOTAL_DOSE_UTIL',
'displayName' : '药物使用总剂量单位',
'type' : 'varchar(20)',
'javaName' : 'drugTotalDoseUtil',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ALIAS_NAME',
'displayName' : '商品名',
'type' : 'varchar(40)',
'javaName' : 'aliasName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEDICATION_CD',
'displayName' : '院内药品编码',
'type' : 'varchar(40)',
'javaName' : 'medicationCd',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEDICATION_NAME',
'displayName' : '院内药品名称',
'type' : 'varchar(40)',
'javaName' : 'medicationName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOSAGE_CODE',
'displayName' : '用药途径代码',
'type' : 'varchar(20)',
'javaName' : 'dosageCode',
'note' : '',
'nullable':true,
'check':'CV0600102'},
{
'name' : 'ONCE_VALUE',
'displayName' : '用药次剂量',
'type' : 'number(8)',
'javaName' : 'onceValue',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ONCE_UNIT',
'displayName' : '用药次剂量单位',
'type' : 'varchar(20)',
'javaName' : 'onceUnit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OP_INFUSION_ITEM',
'displayName' : '术中输液项目',
'type' : 'varchar(100)',
'javaName' : 'opInfusionItem',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BLOOD_TRANSF_DTIME',
'displayName' : '输血日期时间',
'type' : 'date',
'javaName' : 'bloodTransfDtime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'TRANSFUSION_ITEM_AMOUNT',
'displayName' : '输血量',
'type' : 'number(8)',
'javaName' : 'transfusionItemAmount',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRANSFUSION_ITEM_UNIT',
'displayName' : '输血量计量单位',
'type' : 'varchar(20)',
'javaName' : 'transfusionItemUnit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRANSFUSE_REACTION_FLAG',
'displayName' : '输血反应标志',
'type' : 'number(5)',
'javaName' : 'transfuseReactionFlag',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ASA_GRADING_STANDARD_CODE',
'displayName' : 'ASA分级标准代码',
'type' : 'varchar(20)',
'javaName' : 'asaGradingStandardCode',
'note' : '',
'nullable':true,
'check':'CV9900329'},
{
'name' : 'TRACHEA_CANNULA_CLASS',
'displayName' : '气管插管分类',
'type' : 'varchar(40)',
'javaName' : 'tracheaCannulaClass',
'note' : '标识全身麻醉时气管插管分类的描述',
'nullable':true,
'check':''},
{
'name' : 'ANES_DRUG_NAME',
'displayName' : '麻醉药物名称',
'type' : 'varchar(40)',
'javaName' : 'anesDrugName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BREATHE_TYPE_CD',
'displayName' : '呼吸类型代码',
'type' : 'varchar(20)',
'javaName' : 'breatheTypeCd',
'note' : '',
'nullable':true,
'check':'CV9900347'},
{
'name' : 'ANES_DESCR',
'displayName' : '麻醉描述',
'type' : 'varchar(40)',
'javaName' : 'anesDescr',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANES_COMP_CD',
'displayName' : '麻醉合并症标志代码',
'type' : 'varchar(20)',
'javaName' : 'anesCompCd',
'note' : '',
'nullable':true,
'check':'CV9900348'},
{
'name' : 'PUNCTURE_PROCESS',
'displayName' : '穿刺过程',
'type' : 'varchar(100)',
'javaName' : 'punctureProcess',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANES_EFFECT',
'displayName' : '麻醉效果',
'type' : 'varchar(100)',
'javaName' : 'anesEffect',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANES_PRE_DRUG',
'displayName' : '麻醉前用药',
'type' : 'varchar(100)',
'javaName' : 'anesPreDrug',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PROCEDURE_START',
'displayName' : '手术开始时间',
'type' : 'date',
'javaName' : 'procedureStart',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PROCEDURE_END',
'displayName' : '手术结束时间',
'type' : 'date',
'javaName' : 'procedureEnd',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'OP_ROOM',
'displayName' : '手术间编号',
'type' : 'varchar(20)',
'javaName' : 'opRoom',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TREAT_RESCUE_COURSE',
'displayName' : '诊疗过程描述',
'type' : 'varchar(500)',
'javaName' : 'treatRescueCourse',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'E_ORDER_NO',
'displayName' : '电子申请单编号',
'type' : 'varchar(40)',
'javaName' : 'eOrderNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANAESTHESIA_ID',
'displayName' : '麻醉单id',
'type' : 'varchar(40)',
'javaName' : 'anaesthesiaId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANESTHESIA_CODE',
'displayName' : '麻醉方法代码',
'type' : 'varchar(20)',
'javaName' : 'anesthesiaCode',
'note' : '',
'nullable':true,
'check':'CV0600103'},
{
'name' : 'ANESTHESIA_WAY',
'displayName' : '麻醉方法',
'type' : 'varchar(100)',
'javaName' : 'anesthesiaWay',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_CD',
'displayName' : '手术编码',
'type' : 'varchar(20)',
'javaName' : 'operationCd',
'note' : '',
'nullable':true,
'check':'CV990113'},
{
'name' : 'OPERATION_NAME',
'displayName' : '手术名称',
'type' : 'varchar(40)',
'javaName' : 'operationName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRANSFUSION_VARIETY_CODE',
'displayName' : '输血品种编码',
'type' : 'varchar(20)',
'javaName' : 'transfusionVarietyCode',
'note' : '',
'nullable':true,
'check':'CV530201'},
{
'name' : 'TRANSFUSION_VARIETY_NAME',
'displayName' : '输血品种编码名称',
'type' : 'varchar(40)',
'javaName' : 'transfusionVarietyName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANESTHESIA_SITE_CODE',
'displayName' : '麻醉部位代码',
'type' : 'varchar(20)',
'javaName' : 'anesthesiaSiteCode',
'note' : '',
'nullable':true,
'check':'CV0600227'},
{
'name' : 'ANESTHESIA_SITE_NAME',
'displayName' : '麻醉部位代码',
'type' : 'varchar(40)',
'javaName' : 'anesthesiaSiteName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PART_CODE',
'displayName' : '手术操作目标部位代码',
'type' : 'varchar(20)',
'javaName' : 'partCode',
'note' : '',
'nullable':true,
'check':'CV0600227'},
{
'name' : 'PART_NAME',
'displayName' : '手术操作目标部位名称',
'type' : 'varchar(20)',
'javaName' : 'partName',
'note' : '',
'nullable':true,
'check':'CV0600227'},
{
'name' : 'NOTIFY',
'displayName' : '通知者id',
'type' : 'varchar(40)',
'javaName' : 'notify',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATIVE',
'displayName' : '手术者id',
'type' : 'varchar(40)',
'javaName' : 'operative',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATIVE_NAME',
'displayName' : '手术者姓名',
'type' : 'varchar(40)',
'javaName' : 'operativeName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANESTHESIA_START_TIME',
'displayName' : '麻醉开始时间',
'type' : 'date',
'javaName' : 'anesthesiaStartTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ANESTHESIA_END_TIME',
'displayName' : '麻醉结束时间',
'type' : 'date',
'javaName' : 'anesthesiaEndTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ROUTE_MONITOR_ITEM_NAME',
'displayName' : '常规监测项目名称',
'type' : 'varchar(40)',
'javaName' : 'routeMonitorItemName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ROUTE_MONITOR_ITEM_RESULT',
'displayName' : '常规监测项目结果',
'type' : 'varchar(40)',
'javaName' : 'routeMonitorItemResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SPEC_MONITOR_ITEM_NAME',
'displayName' : '特殊监测项目名称',
'type' : 'varchar(40)',
'javaName' : 'specMonitorItemName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SPEC_MONITOR_ITEM_RESULT',
'displayName' : '特殊监测项目结果',
'type' : 'varchar(40)',
'javaName' : 'specMonitorItemResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BODY_TEMPERATURE',
'displayName' : '体温',
'type' : 'number(8)',
'javaName' : 'bodyTemperature',
'note' : '单位：℃',
'nullable':true,
'check':''},
{
'name' : 'HEART_RATE',
'displayName' : '心率',
'type' : 'number(8)',
'javaName' : 'heartRate',
'note' : '次/min',
'nullable':true,
'check':''},
{
'name' : 'PULSES',
'displayName' : '脉率',
'type' : 'number(8)',
'javaName' : 'pulses',
'note' : '次/min',
'nullable':true,
'check':''},
{
'name' : 'BREATHING_RATE',
'displayName' : '呼吸频率',
'type' : 'number(8)',
'javaName' : 'breathingRate',
'note' : '次/min',
'nullable':true,
'check':''},
{
'name' : 'WEIGHT',
'displayName' : '体重',
'type' : 'number(8)',
'javaName' : 'weight',
'note' : 'kg',
'nullable':true,
'check':''},
{
'name' : 'SBP',
'displayName' : '收缩压',
'type' : 'number(8)',
'javaName' : 'sbp',
'note' : 'mmHg',
'nullable':true,
'check':''},
{
'name' : 'DBP',
'displayName' : '舒张压',
'type' : 'number(8)',
'javaName' : 'dbp',
'note' : 'mmHg',
'nullable':true,
'check':''},
{
'name' : 'LOSSBLOOD_AMOUNT',
'displayName' : '出血量',
'type' : 'number(8)',
'javaName' : 'lossbloodAmount',
'note' : 'mL',
'nullable':true,
'check':''},
{
'name' : 'OUT_CODE',
'displayName' : '患者去向代码',
'type' : 'varchar(20)',
'javaName' : 'outCode',
'note' : '',
'nullable':true,
'check':'CV9900291'},
{
'name' : 'REMARKS',
'displayName' : '备注',
'type' : 'text',
'javaName' : 'remarks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUT_OPERATION_ROOM_TIME',
'displayName' : '出手术室日期时间',
'type' : 'date',
'javaName' : 'outOperationRoomTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];