var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'INFECTIOUS_DISEASE_REPORT_ID',
'displayName' : '传染病报告id',
'type' : 'varchar(40)',
'javaName' : 'infectiousDiseaseReportId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RPR_ADDR_PROVINCE',
'displayName' : '户籍登记所在地址的省、自治区或直辖市名称',
'type' : 'varchar(40)',
'javaName' : 'rprAddrProvince',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RPR_ADDR_CITY',
'displayName' : '户籍登记所在地址的市、地区或州的名称',
'type' : 'varchar(40)',
'javaName' : 'rprAddrCity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RPR_ADDR_AREA',
'displayName' : '户籍登记所在地址的县（区）的名称',
'type' : 'varchar(40)',
'javaName' : 'rprAddrArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RPR_ADDR_STREET',
'displayName' : '户籍登记所在地址的乡、镇或城市的街道办事处名称',
'type' : 'varchar(40)',
'javaName' : 'rprAddrStreet',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RPR_ADDR_VILLAGE',
'displayName' : '户籍登记所在地址的村或城市的街、路、里、弄等名称',
'type' : 'varchar(40)',
'javaName' : 'rprAddrVillage',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RPR_ADDR_HOUSE',
'displayName' : '户籍登记所在地址的门牌号码',
'type' : 'varchar(40)',
'javaName' : 'rprAddrHouse',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_STATE',
'displayName' : '家庭住址-省（自治区、直辖市）代码',
'type' : 'varchar(10)',
'javaName' : 'homeState',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_CITY',
'displayName' : '家庭住址-市（地区）代码',
'type' : 'varchar(10)',
'javaName' : 'homeCity',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_DISTRICT',
'displayName' : '家庭住址-县（区）代码',
'type' : 'varchar(10)',
'javaName' : 'homeDistrict',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_LINE',
'displayName' : '家庭住址-乡（镇、街道办事处）',
'type' : 'varchar(100)',
'javaName' : 'homeLine',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_ROAD',
'displayName' : '家庭住址-村（街、路、弄等）',
'type' : 'varchar(100)',
'javaName' : 'homeRoad',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_HOUSE_NO',
'displayName' : '家庭住址-门牌号码',
'type' : 'varchar(50)',
'javaName' : 'homeHouseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_TEXT',
'displayName' : '家庭住址-详细信息',
'type' : 'varchar(500)',
'javaName' : 'homeText',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIAGNOSIS',
'displayName' : '诊断编码',
'type' : 'varchar(20)',
'javaName' : 'diagnosis',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'DIAGNOSIS_NAME',
'displayName' : '诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'diagnosisName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIAGNOSIS_DATE',
'displayName' : '诊断日期',
'type' : 'date',
'javaName' : 'diagnosisDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INFECTIOUS_DISEASE_FIRST_SYMPTOMS_DATE',
'displayName' : '传染病首次出现症状日期',
'type' : 'date',
'javaName' : 'infectiousDiseaseFirstSymptomsDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INFECTIOUS_DISEASES_DEATH_DATE',
'displayName' : '传染病死亡日期',
'type' : 'date',
'javaName' : 'infectiousDiseasesDeathDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'REPORT_CARD_TYPE_CODE',
'displayName' : '报告卡类别代码',
'type' : 'varchar(20)',
'javaName' : 'reportCardTypeCode',
'note' : '',
'nullable':true,
'check':'CV9900063'},
{
'name' : 'INFECTIOUS_DISEASE_ATTRIBUTION_CODE',
'displayName' : '传染病患者归属代码',
'type' : 'varchar(20)',
'javaName' : 'infectiousDiseaseAttributionCode',
'note' : '',
'nullable':true,
'check':'CV0201104'},
{
'name' : 'WITHDRAWAL_REASONS',
'displayName' : '退卡原因',
'type' : 'varchar(200)',
'javaName' : 'withdrawalReasons',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MORBIDITY_TYPE_CODE',
'displayName' : '发病类别代码',
'type' : 'varchar(20)',
'javaName' : 'morbidityTypeCode',
'note' : '',
'nullable':true,
'check':'CV9900064'},
{
'name' : 'INFECTIOUS_DISEASE_CATEGORY_CODE',
'displayName' : '传染病类别代码',
'type' : 'varchar(20)',
'javaName' : 'infectiousDiseaseCategoryCode',
'note' : '',
'nullable':true,
'check':'CV9900114'},
{
'name' : 'INFECTIOUS_DISEASE_NAME_CODE',
'displayName' : '传染病类别代码',
'type' : 'varchar(20)',
'javaName' : 'infectiousDiseaseNameCode',
'note' : '',
'nullable':true,
'check':'CV0501017'},
{
'name' : 'OTHER_INFECTIOUS_DISEASES_NAME',
'displayName' : '其他法定管理及重点监测传染病名称',
'type' : 'varchar(40)',
'javaName' : 'otherInfectiousDiseasesName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REVISED_DISEASE_NAME',
'displayName' : '订正病名',
'type' : 'varchar(40)',
'javaName' : 'revisedDiseaseName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];