var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'CHILDREN_PHYSICAL_EXAMINATION_ID',
'displayName' : '儿童健康体检id',
'type' : 'varchar(40)',
'javaName' : 'childrenPhysicalExaminationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'BIRTH_LENGTH',
'displayName' : '身长（cm）',
'type' : 'number(8)',
'javaName' : 'birthLength',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_WEIGHT',
'displayName' : '体重（g）',
'type' : 'number(8)',
'javaName' : 'birthWeight',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FACE_CODE',
'displayName' : '新生儿面色代码',
'type' : 'varchar(20)',
'javaName' : 'faceCode',
'note' : '',
'nullable':true,
'check':'CV0410008'},
{
'name' : 'RICKETS_SYMPTOM_CODE',
'displayName' : '可疑佝偻病症状代码',
'type' : 'varchar(20)',
'javaName' : 'ricketsSymptomCode',
'note' : '',
'nullable':true,
'check':'CV0410021'},
{
'name' : 'RICKETS_SIGN_CODE',
'displayName' : '可疑佝偻病体征代码',
'type' : 'varchar(20)',
'javaName' : 'ricketsSignCode',
'note' : '',
'nullable':true,
'check':'CV0410022'},
{
'name' : 'SKIN_INSPECT_ABNORMAL_MARK',
'displayName' : '皮肤检查异常标志',
'type' : 'number(5)',
'javaName' : 'skinInspectAbnormalMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ANTERIOR_FONTANELLE_CLOSED_SIGN',
'displayName' : '前囟闭合标志',
'type' : 'number(5)',
'javaName' : 'anteriorFontanelleClosedSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'TRANSVERSE_DIAMETER_ANTERIOR_FONTANEL',
'displayName' : '前囟横径',
'type' : 'number(8)',
'javaName' : 'transverseDiameterAnteriorFontanel',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANTERIOR_LONGITUDINAL_DIAMETER',
'displayName' : '前囟纵径',
'type' : 'number(8)',
'javaName' : 'anteriorLongitudinalDiameter',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANTERIOR_FONTANEL_TENSION_CODE',
'displayName' : '前囟张力代码',
'type' : 'varchar(20)',
'javaName' : 'anteriorFontanelTensionCode',
'note' : '',
'nullable':true,
'check':'CV0410018'},
{
'name' : 'NECK_MASS',
'displayName' : '颈部包块标志',
'type' : 'number(5)',
'javaName' : 'neckMass',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'CERVICAL_MASS_EXAMINATION_RESULTS',
'displayName' : '颈部包块检查结果描述',
'type' : 'varchar(40)',
'javaName' : 'cervicalMassExaminationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FAR_VISUAL_ACUITY',
'displayName' : '左眼裸眼远视力值',
'type' : 'number(8)',
'javaName' : 'farVisualAcuity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LEFT_CORRECTED_VISUAL_ACUITY',
'displayName' : '左眼矫正远视力值',
'type' : 'number(8)',
'javaName' : 'leftCorrectedVisualAcuity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RIGHT_CORRECTED_VISUAL_ACUITY',
'displayName' : '右眼矫正远视力值',
'type' : 'number(8)',
'javaName' : 'rightCorrectedVisualAcuity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EYE_APPEARANCE_CHECK',
'displayName' : '眼外观检查异常标志',
'type' : 'number(5)',
'javaName' : 'eyeAppearanceCheck',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'EYE_APPEARANCE_INSPECTION_RESULTS',
'displayName' : '眼外观检查异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'eyeAppearanceInspectionResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EAR_APPEARANCE_ABNORMAL_SIGN',
'displayName' : '耳外观检查异常标志',
'type' : 'number(5)',
'javaName' : 'earAppearanceAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'EAR_APPEARANCE_RESULT',
'displayName' : '耳外观检查异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'earAppearanceResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEARING_SCREENING_RESULTS_CODE',
'displayName' : '新生儿听力筛查结果代码',
'type' : 'varchar(20)',
'javaName' : 'hearingScreeningResultsCode',
'note' : '',
'nullable':true,
'check':'CV9900025'},
{
'name' : 'ORAL_EXAMINATION_ABNORMAL_SIGN',
'displayName' : '口腔检查异常标志',
'type' : 'number(5)',
'javaName' : 'oralExaminationAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ORAL_EXAMINATION_RESULTS',
'displayName' : '口腔检查异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'oralExaminationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TEETHING_NUM',
'displayName' : '出牙数',
'type' : 'number(8)',
'javaName' : 'teethingNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DENTAL_CARIES_NUM',
'displayName' : '龋齿数',
'type' : 'number(8)',
'javaName' : 'dentalCariesNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CARDIAC_AUSCULTATION_ABNORMAL_SIGN',
'displayName' : '心脏听诊异常标志',
'type' : 'number(5)',
'javaName' : 'cardiacAuscultationAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'CARDIAC_AUSCULTATION_RESULTS',
'displayName' : '心脏听诊异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'cardiacAuscultationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LUNG_AUSCULTATION_ABNORMAL_SIGN',
'displayName' : '肺部听诊异常标志',
'type' : 'number(5)',
'javaName' : 'lungAuscultationAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'LUNG_AUSCULTATION_RESULTS',
'displayName' : '肺部听诊异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'lungAuscultationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ABDOMINAL_PALPATION_ABNORMAL_SIGN',
'displayName' : '腹部触诊异常标志',
'type' : 'number(5)',
'javaName' : 'abdominalPalpationAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ABDOMINAL_PALPATION_RESULTS',
'displayName' : '腹部触诊异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'abdominalPalpationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UMBILICAL_CORD',
'displayName' : '脐带脱落标志',
'type' : 'number(5)',
'javaName' : 'umbilicalCord',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'UMBILICAL_CORD_EXAMINATION_RESULTS_CODE',
'displayName' : '脐带检查结果代码',
'type' : 'varchar(20)',
'javaName' : 'umbilicalCordExaminationResultsCode',
'note' : '',
'nullable':true,
'check':'CV0410019'},
{
'name' : 'LIMB_ACTIVITY_ABNORMAL_SIGN',
'displayName' : '四肢活动度异常标志',
'type' : 'number(5)',
'javaName' : 'limbActivityAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'LIMB_MOBILITY_ABNORMAL_RESULTS',
'displayName' : '四肢活动度异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'limbMobilityAbnormalResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SPINAL_EXAMINATION_ABNORMAL_SIGN',
'displayName' : '脊柱检查异常标志',
'type' : 'number(5)',
'javaName' : 'spinalExaminationAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'SPINAL_EXAMINATION_RESULTS',
'displayName' : '脊柱检查异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'spinalExaminationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EXTERNAL_GENITAL_ORGANS_ABNORMAL_SIGN',
'displayName' : '外生殖器检查异常标志',
'type' : 'number(5)',
'javaName' : 'externalGenitalOrgansAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'EXTERNAL_GENITAL_ORGANS_RESULTS',
'displayName' : '外生殖器检查异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'externalGenitalOrgansResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANUS_ABNORMAL_SIGN',
'displayName' : '肛门检查异常标志',
'type' : 'number(5)',
'javaName' : 'anusAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ANUS_EXAMINATION_RESULTS',
'displayName' : '肛门检查异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'anusExaminationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUTDOOR_ACTIVITY_LENGTH',
'displayName' : '户外活动时长',
'type' : 'number(8)',
'javaName' : 'outdoorActivityLength',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TWO_FOLLOW_UP_VISITS_MARK',
'displayName' : '两次随访间患病标志',
'type' : 'number(5)',
'javaName' : 'twoFollowUpVisitsMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'PNEUMONIA_TIMES',
'displayName' : '两次随访间患肺炎住院次数',
'type' : 'number(4)',
'javaName' : 'pneumoniaTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIARRHEA_TIMES',
'displayName' : '两次随访间患腹泻住院次数',
'type' : 'number(4)',
'javaName' : 'diarrheaTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRAUMA_TIMES',
'displayName' : '两次随访间因外伤住院次数',
'type' : 'number(4)',
'javaName' : 'traumaTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OTHER_DISEASE_CONDITION',
'displayName' : '两次随访间患其他疾病情况',
'type' : 'varchar(40)',
'javaName' : 'otherDiseaseCondition',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEMOGLOBIN',
'displayName' : '血红蛋白(g/L)',
'type' : 'number(8)',
'javaName' : 'hemoglobin',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEIGHT_EVALUATION_RESULT_CODE',
'displayName' : '年龄别身高评价结果代码',
'type' : 'varchar(20)',
'javaName' : 'heightEvaluationResultCode',
'note' : '',
'nullable':true,
'check':'CV0510006'},
{
'name' : 'WEIGHT_EVALUATION_RESULT_CODE',
'displayName' : '年龄别体重评价结果代码',
'type' : 'varchar(20)',
'javaName' : 'weightEvaluationResultCode',
'note' : '',
'nullable':true,
'check':'CV0510006'},
{
'name' : 'PHYSIQUE_EVALUATION_RESULT_CODE',
'displayName' : '体格发育评价代码',
'type' : 'varchar(20)',
'javaName' : 'physiqueEvaluationResultCode',
'note' : '',
'nullable':true,
'check':'CV0510006'},
{
'name' : 'CHILD_EVALUATION_ADOPT_MARK',
'displayName' : '儿童发育评估通过标志',
'type' : 'number(5)',
'javaName' : 'childEvaluationAdoptMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'HEALTH_INSTRUCTION_CODE',
'displayName' : '健康指导代码',
'type' : 'varchar(20)',
'javaName' : 'healthInstructionCode',
'note' : '',
'nullable':true,
'check':'CV9900017'},
{
'name' : 'REFERRAL_MARK',
'displayName' : '转诊标志',
'type' : 'number(5)',
'javaName' : 'referralMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'REFERRAL_REASONS',
'displayName' : '转诊原因',
'type' : 'varchar(40)',
'javaName' : 'referralReasons',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REFERRAL_IN_ORG',
'displayName' : '转入机构的名称',
'type' : 'varchar(40)',
'javaName' : 'referralInOrg',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REFERRAL_IN_DEP',
'displayName' : '转入科室的名称',
'type' : 'varchar(40)',
'javaName' : 'referralInDep',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NEXT_FOLLOW_UP_DATE',
'displayName' : '下次随访日期',
'type' : 'date',
'javaName' : 'nextFollowUpDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'NEXT_VISIT_LOCATION',
'displayName' : '下次访视地点',
'type' : 'varchar(40)',
'javaName' : 'nextVisitLocation',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEDICATION_CD',
'displayName' : '院内药物编码',
'type' : 'varchar(20)',
'javaName' : 'medicationCd',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEDICATION_NAME',
'displayName' : '院内药物名称',
'type' : 'varchar(40)',
'javaName' : 'medicationName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FREQ_CODE',
'displayName' : '频率代码',
'type' : 'varchar(20)',
'javaName' : 'freqCode',
'note' : '',
'nullable':true,
'check':'CV9900341'},
{
'name' : 'ONCE_VALUE',
'displayName' : '用药次剂量',
'type' : 'number(8)',
'javaName' : 'onceValue',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ONCE_UNIT',
'displayName' : '用药次剂量单位',
'type' : 'varchar(20)',
'javaName' : 'onceUnit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];