var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'EMPLOYEE_ID',
'displayName' : '院内人员id',
'type' : 'varchar(40)',
'javaName' : 'employeeId',
'note' : '医务人员在院内系统中的唯一标识',
'nullable':false,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(20)',
'javaName' : 'gender',
'note' : '',
'nullable':true,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DEPARTMENT_ID',
'displayName' : '所在科室id',
'type' : 'varchar(40)',
'javaName' : 'departmentId',
'note' : '引用科室信息表T_DEPARTMENT院内科室id',
'nullable':true,
'check':''},
{
'name' : 'PRACTITIONER_ROLE',
'displayName' : '岗位代码',
'type' : 'varchar(20)',
'javaName' : 'practitionerRole',
'note' : '',
'nullable':true,
'check':'CUS00003'},
{
'name' : 'POST',
'displayName' : '专业技术职务代码',
'type' : 'varchar(20)',
'javaName' : 'post',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'QUALIFICATION_CERTIFICATE_NO',
'displayName' : '从业资格证号',
'type' : 'varchar(40)',
'javaName' : 'qualificationCertificateNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PRA_SCOPE',
'displayName' : '执业范围',
'type' : 'varchar(200)',
'javaName' : 'praScope',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IF_PRESCRIBE',
'displayName' : '是否拥有处方权',
'type' : 'number(5)',
'javaName' : 'ifPrescribe',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'IF_POISON',
'displayName' : '是否可以开立毒麻药品',
'type' : 'number(5)',
'javaName' : 'ifPoison',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'IF_PSYCHOTROPIC',
'displayName' : '是否可以开立精神药品',
'type' : 'number(5)',
'javaName' : 'ifPsychotropic',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ANTIBIOTIC_USE_PERMISSION',
'displayName' : '抗生素使用权限',
'type' : 'varchar(20)',
'javaName' : 'antibioticUsePermission',
'note' : '',
'nullable':true,
'check':'CV9900274'}
];