var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'IPN_SHIFT_RECORD_ID',
'displayName' : '交接班记录id',
'type' : 'varchar(40)',
'javaName' : 'ipnShiftRecordId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'CASE_NO',
'displayName' : '病案号',
'type' : 'varchar(20)',
'javaName' : 'caseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_TIMES',
'displayName' : '住院次数',
'type' : 'number(8)',
'javaName' : 'inpatTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REMARKS',
'displayName' : '备注',
'type' : 'text',
'javaName' : 'remarks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IF_RRITABILITY',
'displayName' : '是否有过敏史',
'type' : 'number(5)',
'javaName' : 'ifRritability',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'RRITABILITY',
'displayName' : '过敏史其他描述',
'type' : 'text',
'javaName' : 'rritability',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'CN_FOUR_RESULT',
'displayName' : '中医&quot;四诊&quot;观察结果',
'type' : 'varchar(200)',
'javaName' : 'cnFourResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SHIFT_P_ID',
'displayName' : '交班者id',
'type' : 'varchar(40)',
'javaName' : 'shiftPId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SHIFT_P_NAME',
'displayName' : '交班者姓名',
'type' : 'varchar(20)',
'javaName' : 'shiftPName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SHIFT_DATE',
'displayName' : '交班时间',
'type' : 'date',
'javaName' : 'shiftDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'SUCCESSOR_P_ID',
'displayName' : '接班者id',
'type' : 'varchar(40)',
'javaName' : 'successorPId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SUCCESSOR_P_NAME',
'displayName' : '接班者姓名',
'type' : 'varchar(20)',
'javaName' : 'successorPName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SUCCESSOR_DATE',
'displayName' : '接班时间',
'type' : 'date',
'javaName' : 'successorDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CHIEF',
'displayName' : '主诉',
'type' : 'text',
'javaName' : 'chief',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IN_CN_SYM_DIAG_CODE',
'displayName' : '入院诊断-中医征候诊断代码',
'type' : 'varchar(20)',
'javaName' : 'inCnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'IN_CN_DIS_DIAG_CODE',
'displayName' : '入院诊断-中医病名诊断代码',
'type' : 'varchar(20)',
'javaName' : 'inCnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'IN_DIAG_CODE',
'displayName' : '入院诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'inDiagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'IN_DIAG_VALUE',
'displayName' : '入院诊断-诊断名称',
'type' : 'varchar(20)',
'javaName' : 'inDiagValue',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IN_DIAG_DATE',
'displayName' : '入院诊断-诊断日期',
'type' : 'date',
'javaName' : 'inDiagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'IN_DIAG_DETAILS',
'displayName' : '入院诊断-入院情况',
'type' : 'varchar(100)',
'javaName' : 'inDiagDetails',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IN_DIAG_RECORD_CURRENT_CIRCUMSTANCES',
'displayName' : '诊断记录-目前情况',
'type' : 'varchar(100)',
'javaName' : 'inDiagRecordCurrentCircumstances',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IN_RECORD_CN_SYM_DIAG_CODE',
'displayName' : '诊断记录-中医征候诊断代码',
'type' : 'varchar(20)',
'javaName' : 'inRecordCnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'IN_RECORD_CN_DIS_DIAG_CODE',
'displayName' : '诊断记录-中医病名诊断代码',
'type' : 'varchar(20)',
'javaName' : 'inRecordCnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'IN_RECORD_DIAG_CODE',
'displayName' : '诊断记录-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'inRecordDiagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'IN_RECORD_DIAG_DATE',
'displayName' : '诊断记录-诊断日期',
'type' : 'date',
'javaName' : 'inRecordDiagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'IN_RECORD_DIAG_VALUE',
'displayName' : '诊断记录-诊断名称',
'type' : 'varchar(20)',
'javaName' : 'inRecordDiagValue',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'THERAPEUTIC_PRINCIPLES',
'displayName' : '治则治法代码',
'type' : 'varchar(10)',
'javaName' : 'therapeuticPrinciples',
'note' : '根据辨证结果采用的治则治法名称术语',
'nullable':true,
'check':'GBT167513'},
{
'name' : 'MATTERS_NEEDING_ATTENTION',
'displayName' : '注意事项',
'type' : 'varchar(500)',
'javaName' : 'mattersNeedingAttention',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SUCCEED_TREATMENT_OPTIONS',
'displayName' : '接班诊疗计划',
'type' : 'varchar(500)',
'javaName' : 'succeedTreatmentOptions',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TREAT_RESCUE_COURSE',
'displayName' : '诊疗过程描述',
'type' : 'varchar(500)',
'javaName' : 'treatRescueCourse',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];