var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'POSTPARTUM_VISIT_ID',
'displayName' : '产后访视id',
'type' : 'varchar(40)',
'javaName' : 'postpartumVisitId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_STATUS_DETAILS',
'displayName' : '健康状况详细描述',
'type' : 'text',
'javaName' : 'healthStatusDetails',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MENTAL_STATE_DETAILED_DESCRIPTION',
'displayName' : '心理状况详细描述',
'type' : 'text',
'javaName' : 'mentalStateDetailedDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BODY_TEMPERATURE',
'displayName' : '体温(体温的测量值，计量单位为℃)',
'type' : 'number(8)',
'javaName' : 'bodyTemperature',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SBP',
'displayName' : '收缩压(收缩压的测量值，计量单位为mmHg)',
'type' : 'number(4)',
'javaName' : 'sbp',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DBP',
'displayName' : '舒张压(舒张压的测量值，计量单位为mmHg)',
'type' : 'number(4)',
'javaName' : 'dbp',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BREAST_EXAMINATION_RESULTS_CODE',
'displayName' : '乳腺检查结果代码',
'type' : 'varchar(20)',
'javaName' : 'breastExaminationResultsCode',
'note' : '',
'nullable':true,
'check':'CV0410012'},
{
'name' : 'LOCHIA_ABNORMAL_SIGN',
'displayName' : '恶露异常标志',
'type' : 'number(5)',
'javaName' : 'lochiaAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'UTERINE_BODY_ABNORMAL_SIGN',
'displayName' : '宫体异常标志',
'type' : 'number(5)',
'javaName' : 'uterineBodyAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'WOUND_HEALING_STATUS_CODE',
'displayName' : '伤口愈合状况代码',
'type' : 'varchar(20)',
'javaName' : 'woundHealingStatusCode',
'note' : '',
'nullable':true,
'check':'CV0501011'},
{
'name' : 'MATERNAL_HEALTH_ASSESSMENT',
'displayName' : '孕产妇健康评估异常标志',
'type' : 'number(5)',
'javaName' : 'maternalHealthAssessment',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'MATERNAL_HEALTH_RESULT_DESCR',
'displayName' : '孕产妇健康评估异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'maternalHealthResultDescr',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_INSTRUCTION_CODE',
'displayName' : '健康指导代码',
'type' : 'varchar(20)',
'javaName' : 'healthInstructionCode',
'note' : '',
'nullable':true,
'check':'CV9900017'},
{
'name' : 'REFERRAL_MARK',
'displayName' : '转诊标志',
'type' : 'number(5)',
'javaName' : 'referralMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'REFERRAL_REASONS',
'displayName' : '转诊原因',
'type' : 'varchar(40)',
'javaName' : 'referralReasons',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REFERRAL_IN_ORG',
'displayName' : '转入机构的名称',
'type' : 'varchar(40)',
'javaName' : 'referralInOrg',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REFERRAL_IN_DEP',
'displayName' : '转入科室的名称',
'type' : 'varchar(40)',
'javaName' : 'referralInDep',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NEXT_FOLLOW_UP_DATE',
'displayName' : '下次随访日期',
'type' : 'date',
'javaName' : 'nextFollowUpDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'NEXT_VISIT_LOCATION',
'displayName' : '下次访视地点',
'type' : 'varchar(40)',
'javaName' : 'nextVisitLocation',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];