var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'OUTPATIENT_PRESCRIPTION_ID',
'displayName' : '院内处方号',
'type' : 'varchar(40)',
'javaName' : 'outpatientPrescriptionId',
'note' : '门诊处方在院内系统中的唯一标识',
'nullable':false,
'check':''},
{
'name' : 'STATUS',
'displayName' : '状态',
'type' : 'varchar(20)',
'javaName' : 'status',
'note' : '',
'nullable':true,
'check':'CUS00008'},
{
'name' : 'OUTPATIENT_REGISTRATION_ID',
'displayName' : '门诊流水号',
'type' : 'varchar(40)',
'javaName' : 'outpatientRegistrationId',
'note' : '引用门诊接诊表T_OUTPATIENT_REGISTRATION院内门诊流水号',
'nullable':false,
'check':''},
{
'name' : 'PATIENT_ID',
'displayName' : '患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '引用患者信息表T_PATIENT院内患者id',
'nullable':false,
'check':''},
{
'name' : 'PATIENT_NAME',
'displayName' : '患者姓名',
'type' : 'varchar(40)',
'javaName' : 'patientName',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATEWRITTEN',
'displayName' : '开立时间',
'type' : 'date',
'javaName' : 'datewritten',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PRESCRIBER',
'displayName' : '开立医生ID',
'type' : 'varchar(40)',
'javaName' : 'prescriber',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'ORDER_DPID',
'displayName' : '开立科室',
'type' : 'varchar(40)',
'javaName' : 'orderDpid',
'note' : '引用科室信息表T_DEPARTMENT院内科室id',
'nullable':true,
'check':''},
{
'name' : 'DATEENDED',
'displayName' : '取消日期时间',
'type' : 'date',
'javaName' : 'dateended',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'STOP_DOCTORID',
'displayName' : '停止医生',
'type' : 'varchar(40)',
'javaName' : 'stopDoctorid',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'CHECK_DATE',
'displayName' : '校对时间',
'type' : 'date',
'javaName' : 'checkDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CHECK_NURID',
'displayName' : '校对护士',
'type' : 'varchar(40)',
'javaName' : 'checkNurid',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'ORDER_AUDITOR_DATE',
'displayName' : '审核时间',
'type' : 'date',
'javaName' : 'orderAuditorDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ORDER_AUDITOR',
'displayName' : '审核人',
'type' : 'varchar(40)',
'javaName' : 'orderAuditor',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'ORDER_CHECK_TIME',
'displayName' : '医嘱核对日期时间',
'type' : 'date',
'javaName' : 'orderCheckTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PERFORM_TIME',
'displayName' : '执行时间',
'type' : 'date',
'javaName' : 'performTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PERFORM_DEPT_CD',
'displayName' : '执行科室',
'type' : 'varchar(40)',
'javaName' : 'performDeptCd',
'note' : '引用科室信息表T_DEPARTMENT院内科室id',
'nullable':true,
'check':''},
{
'name' : 'PERFORMER_CD',
'displayName' : '执行医生',
'type' : 'varchar(40)',
'javaName' : 'performerCd',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'NOTE',
'displayName' : '备注',
'type' : 'varchar(500)',
'javaName' : 'note',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SKINTEST_TYPE',
'displayName' : '皮试类型标志',
'type' : 'varchar(20)',
'javaName' : 'skintestType',
'note' : '',
'nullable':true,
'check':'CV9900287'},
{
'name' : 'SKINTEST_RESULT',
'displayName' : '皮试结果',
'type' : 'varchar(100)',
'javaName' : 'skintestResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SKINTEST_NURID',
'displayName' : '皮试护士',
'type' : 'varchar(40)',
'javaName' : 'skintestNurid',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'SKINTEST_SENURID',
'displayName' : '第二皮试护士',
'type' : 'varchar(40)',
'javaName' : 'skintestSenurid',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'RECIPE_TYPE_CODE',
'displayName' : '处方类型代码',
'type' : 'varchar(20)',
'javaName' : 'recipeTypeCode',
'note' : '',
'nullable':true,
'check':'CV9900264'},
{
'name' : 'APPLY_ID',
'displayName' : '申请单号',
'type' : 'varchar(40)',
'javaName' : 'applyId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'C_MED_NUM',
'displayName' : '中药剂数',
'type' : 'number(8)',
'javaName' : 'cMedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISPENSING_DTIME',
'displayName' : '发药时间',
'type' : 'date',
'javaName' : 'dispensingDtime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CN_PRESCRIBE',
'displayName' : '中药处方',
'type' : 'varchar(100)',
'javaName' : 'cnPrescribe',
'note' : '中药饮片处方的详细描述',
'nullable':true,
'check':''},
{
'name' : 'CN_PRESCRIBE_DESCR',
'displayName' : '中药煎煮法',
'type' : 'varchar(100)',
'javaName' : 'cnPrescribeDescr',
'note' : '中药饮片煎煮方法描述',
'nullable':true,
'check':''},
{
'name' : 'CN_DRUG_WAY_CD',
'displayName' : '中药服用方法代码',
'type' : 'varchar(20)',
'javaName' : 'cnDrugWayCd',
'note' : '',
'nullable':true,
'check':'CV9900304'},
{
'name' : 'CN_TYPE_CD',
'displayName' : '中药剂型',
'type' : 'varchar(20)',
'javaName' : 'cnTypeCd',
'note' : '',
'nullable':true,
'check':'CV9900389'},
{
'name' : 'IF_AGENCY',
'displayName' : '是否代办',
'type' : 'number(5)',
'javaName' : 'ifAgency',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'IF_PRINT',
'displayName' : '是否打印',
'type' : 'number(5)',
'javaName' : 'ifPrint',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'IF_CHANGE',
'displayName' : '是否收费',
'type' : 'number(5)',
'javaName' : 'ifChange',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'AGENCY_REL_CODE',
'displayName' : '代办人关系代码',
'type' : 'varchar(20)',
'javaName' : 'agencyRelCode',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'ID_CARD',
'displayName' : '代办人身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ALLOCATE_PSID',
'displayName' : '调配者ID',
'type' : 'varchar(40)',
'javaName' : 'allocatePsid',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'DRUG_PSID',
'displayName' : '发药者ID',
'type' : 'varchar(40)',
'javaName' : 'drugPsid',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'PREC_AUDIT_PSID',
'displayName' : '审核药剂师ID',
'type' : 'varchar(40)',
'javaName' : 'precAuditPsid',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'PREC_CHECK_PSID',
'displayName' : '核对药剂师ID',
'type' : 'varchar(40)',
'javaName' : 'precCheckPsid',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'PERFORM_DEPT',
'displayName' : '执行科室ID',
'type' : 'varchar(40)',
'javaName' : 'performDept',
'note' : '引用科室信息表T_DEPARTMENT院内科室id',
'nullable':true,
'check':''},
{
'name' : 'PREC_PERFORM',
'displayName' : '执行人ID',
'type' : 'varchar(40)',
'javaName' : 'precPerform',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'TOTAL_AMOUNT',
'displayName' : '处方总金额',
'type' : 'number(8)',
'javaName' : 'totalAmount',
'note' : '',
'nullable':true,
'check':''}
];