var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'HCR_DISCHARGE_RECORD_ID',
'displayName' : '出院记录id',
'type' : 'varchar(40)',
'javaName' : 'hcrDischargeRecordId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ATTENDING_DOCTOR_SIGN_DATE',
'displayName' : '主治医师签名日期',
'type' : 'date',
'javaName' : 'attendingDoctorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ATTENDING_DOCTOR_ID',
'displayName' : '主治医师id',
'type' : 'varchar(40)',
'javaName' : 'attendingDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ATTENDING_DOCTOR_NAME',
'displayName' : '主治医师姓名',
'type' : 'varchar(20)',
'javaName' : 'attendingDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ATTENDING_DOCTOR_POST_CODE',
'displayName' : '主治医师职务代码',
'type' : 'varchar(20)',
'javaName' : 'attendingDoctorPostCode',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'RESIDENT_DOCTOR_SIGN_DATE',
'displayName' : '住院医师签名日期',
'type' : 'date',
'javaName' : 'residentDoctorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RESIDENT_DOCTOR_ID',
'displayName' : '住院医师id',
'type' : 'varchar(40)',
'javaName' : 'residentDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESIDENT_DOCTOR_NAME',
'displayName' : '住院医师姓名',
'type' : 'varchar(20)',
'javaName' : 'residentDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESIDENT_DOCTOR_POST_CODE',
'displayName' : '住院医师职务代码',
'type' : 'varchar(20)',
'javaName' : 'residentDoctorPostCode',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'DIRECTOR_DOCTOR_SIGN_DATE',
'displayName' : '主任医师签名日期',
'type' : 'date',
'javaName' : 'directorDoctorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DIRECTOR_DOCTOR_ID',
'displayName' : '主任医师id',
'type' : 'varchar(40)',
'javaName' : 'directorDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIRECTOR_DOCTOR_NAME',
'displayName' : '主任医师姓名',
'type' : 'varchar(20)',
'javaName' : 'directorDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIRECTOR_DOCTOR_POST_CODE',
'displayName' : '主任医师职务代码',
'type' : 'varchar(20)',
'javaName' : 'directorDoctorPostCode',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'CN_FOUR_RESULT',
'displayName' : '中医&quot;四诊&quot;观察结果',
'type' : 'varchar(100)',
'javaName' : 'cnFourResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'HTH_INPATIENT_DETAILS',
'displayName' : '入院情况',
'type' : 'text',
'javaName' : 'hthInpatientDetails',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUT_CN_SYM_DIAG_CODE',
'displayName' : '出院诊断-中医症候代码',
'type' : 'varchar(20)',
'javaName' : 'outCnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'OUT_CN_DIS_DIAG_CODE',
'displayName' : '出院诊断-中医病名代码',
'type' : 'varchar(20)',
'javaName' : 'outCnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'OUT_DISCHARGE_SYMPTOM_AND_SIGN',
'displayName' : '出院诊断-出院时症状与体征',
'type' : 'varchar(100)',
'javaName' : 'outDischargeSymptomAndSign',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUT_DISCHARGE_CIRCUMSTANCE',
'displayName' : '出院诊断-出院情况',
'type' : 'text',
'javaName' : 'outDischargeCircumstance',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUT_DISCHARGE_ADVICE',
'displayName' : '出院诊断-出院医嘱',
'type' : 'text',
'javaName' : 'outDischargeAdvice',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUT_ADMISSION_DIAGNOSIS',
'displayName' : '出院诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'outAdmissionDiagnosis',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'OUT_ADMISSION_DIAGNOSIS_NAME',
'displayName' : '出院诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'outAdmissionDiagnosisName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUT_DIAGNOSIS_DATE',
'displayName' : '出院诊断-诊断日期',
'type' : 'date',
'javaName' : 'outDiagnosisDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'IN_POSITIVE_AUX_INSPECTION_RESULT',
'displayName' : '入院诊断-阳性辅助检查结果',
'type' : 'varchar(200)',
'javaName' : 'inPositiveAuxInspectionResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IN_THERAPEUTIC_PRINCIPLES',
'displayName' : '入院诊断-治则治法',
'type' : 'varchar(200)',
'javaName' : 'inTherapeuticPrinciples',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IN_ADMISSION_DIAGNOSIS',
'displayName' : '入院诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'inAdmissionDiagnosis',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'IN_ADMISSION_DIAGNOSIS_NAME',
'displayName' : '入院诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'inAdmissionDiagnosisName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IN_DIAGNOSIS_DATE',
'displayName' : '入院诊断-诊断日期',
'type' : 'date',
'javaName' : 'inDiagnosisDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'IN_TREAT_RESCUE_COURSE',
'displayName' : '住院过程-诊疗过程描述',
'type' : 'varchar(500)',
'javaName' : 'inTreatRescueCourse',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CN_PRESCRIBE_DESCR',
'displayName' : '医嘱用药-中药煎煮法',
'type' : 'varchar(100)',
'javaName' : 'cnPrescribeDescr',
'note' : '中药饮片煎煮方法描述',
'nullable':true,
'check':''},
{
'name' : 'CN_DRUG_WAY_CD',
'displayName' : '医嘱用药-中药服用方法代码',
'type' : 'varchar(20)',
'javaName' : 'cnDrugWayCd',
'note' : '',
'nullable':true,
'check':'CV9900304'},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];