var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'DISCHARGE_SUMMARY_ID',
'displayName' : '出院小结id',
'type' : 'varchar(40)',
'javaName' : 'dischargeSummaryId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DISCHARGE_SUMMARY_TYPE',
'displayName' : '出院小结类型',
'type' : 'varchar(20)',
'javaName' : 'dischargeSummaryType',
'note' : '',
'nullable':true,
'check':'CV990108'},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AGE',
'displayName' : '患者年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_TYPE',
'displayName' : '患者类型',
'type' : 'varchar(20)',
'javaName' : 'patientType',
'note' : '',
'nullable':true,
'check':'CV0900404'},
{
'name' : 'OCCUPATION_CD',
'displayName' : '职业代码',
'type' : 'varchar(20)',
'javaName' : 'occupationCd',
'note' : '',
'nullable':true,
'check':'GBT22614'},
{
'name' : 'WORK_UNIT',
'displayName' : '工作单位',
'type' : 'varchar(40)',
'javaName' : 'workUnit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_PRO_CODE',
'displayName' : '出生地住址-省（自治区、直辖市）代码',
'type' : 'varchar(10)',
'javaName' : 'birthProCode',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'BIRTH_CITY_CODE',
'displayName' : '出生地住址-市（地区）代码',
'type' : 'varchar(10)',
'javaName' : 'birthCityCode',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'BIRTH_COU_CODE',
'displayName' : '出生地住址-县（区）代码',
'type' : 'varchar(10)',
'javaName' : 'birthCouCode',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'BIRTH_ADDRESS_VILLAGE',
'displayName' : '出生地住址-村（街、路、弄等）',
'type' : 'varchar(100)',
'javaName' : 'birthAddressVillage',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NATION_CD',
'displayName' : '民族代码',
'type' : 'varchar(20)',
'javaName' : 'nationCd',
'note' : '',
'nullable':true,
'check':'CV9900377'},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'TELECOM',
'displayName' : '联系电话',
'type' : 'varchar(20)',
'javaName' : 'telecom',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'WORK_STATE',
'displayName' : '工作住址-省（自治区、直辖市）代码',
'type' : 'varchar(10)',
'javaName' : 'workState',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'WORK_CITY',
'displayName' : '工作住址-市（地区）代码',
'type' : 'varchar(10)',
'javaName' : 'workCity',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'WORK_DISTRICT',
'displayName' : '工作住址-县（区）代码',
'type' : 'varchar(10)',
'javaName' : 'workDistrict',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'WORK_LINE',
'displayName' : '工作住址-乡（镇、街道办事处）',
'type' : 'varchar(100)',
'javaName' : 'workLine',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WORK_ROAD',
'displayName' : '工作住址-村（街、路、弄等）',
'type' : 'varchar(100)',
'javaName' : 'workRoad',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WORK_HOUSE_NO',
'displayName' : '工作住址-门牌号码',
'type' : 'varchar(50)',
'javaName' : 'workHouseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WORK_POST_CD',
'displayName' : '工作地址邮政编码',
'type' : 'varchar(50)',
'javaName' : 'workPostCd',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WORK_ADDRESS_DETAILS',
'displayName' : '工作地址详细信息',
'type' : 'varchar(50)',
'javaName' : 'workAddressDetails',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TEMP_STATE',
'displayName' : '现居住住址-省（自治区、直辖市）代码',
'type' : 'varchar(10)',
'javaName' : 'tempState',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'TEMP_CITY',
'displayName' : '现居住住址-市（地区）代码',
'type' : 'varchar(10)',
'javaName' : 'tempCity',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'TEMP_DISTRICT',
'displayName' : '现居住住址-县（区）代码',
'type' : 'varchar(10)',
'javaName' : 'tempDistrict',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'TEMP_LINE',
'displayName' : '现居住住址-乡（镇、街道办事处）',
'type' : 'varchar(100)',
'javaName' : 'tempLine',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TEMP_ROAD',
'displayName' : '现居住住址-村（街、路、弄等）',
'type' : 'varchar(100)',
'javaName' : 'tempRoad',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TEMP_HOUSE_NO',
'displayName' : '现居住住址-门牌号码',
'type' : 'varchar(50)',
'javaName' : 'tempHouseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TEMP_POST_CD',
'displayName' : '现居住地址邮政编码',
'type' : 'varchar(50)',
'javaName' : 'tempPostCd',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TEMP_ADDRESS_DETAILS',
'displayName' : '现居住址详细信息',
'type' : 'varchar(50)',
'javaName' : 'tempAddressDetails',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MARITALSTATUS',
'displayName' : '婚姻状况代码',
'type' : 'varchar(20)',
'javaName' : 'maritalstatus',
'note' : '',
'nullable':true,
'check':'GBT22612'},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'STATUTORY_AUDIT_SIGN_DATE',
'displayName' : '法定审核者签名日期',
'type' : 'date',
'javaName' : 'statutoryAuditSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'STATUTORY_AUDIT_ID',
'displayName' : '法定审核者id',
'type' : 'varchar(40)',
'javaName' : 'statutoryAuditId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'STATUTORY_AUDIT_NAME',
'displayName' : '法定审核者姓名',
'type' : 'varchar(20)',
'javaName' : 'statutoryAuditName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOCUMENT_VERIFIER_SIGN_DATE',
'displayName' : '文档审核者签名日期',
'type' : 'date',
'javaName' : 'documentVerifierSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DOCUMENT_VERIFIER_ID',
'displayName' : '文档审核者id',
'type' : 'varchar(40)',
'javaName' : 'documentVerifierId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOCUMENT_VERIFIER_NAME',
'displayName' : '文档审核者姓名',
'type' : 'varchar(20)',
'javaName' : 'documentVerifierName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESIDENT_DOCTOR_SIGN_DATE',
'displayName' : '住院医师签名日期',
'type' : 'date',
'javaName' : 'residentDoctorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RESIDENT_DOCTOR_ID',
'displayName' : '住院医师id',
'type' : 'varchar(40)',
'javaName' : 'residentDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESIDENT_DOCTOR_NAME',
'displayName' : '住院医师姓名',
'type' : 'varchar(20)',
'javaName' : 'residentDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ATTENDING_PHYSICIAN_SIGN_DATE',
'displayName' : '主治医师签名日期',
'type' : 'date',
'javaName' : 'attendingPhysicianSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ATTENDING_PHYSICIAN_ID',
'displayName' : '主治医师id',
'type' : 'varchar(40)',
'javaName' : 'attendingPhysicianId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ATTENDING_PHYSICIAN_NAME',
'displayName' : '主治医师姓名',
'type' : 'varchar(20)',
'javaName' : 'attendingPhysicianName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START_TIME',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'startTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'END_TIME',
'displayName' : '出院时间',
'type' : 'date',
'javaName' : 'endTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(40)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(40)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CN_FOUR_RESULT',
'displayName' : '中医&quot;四诊&quot;观察结果',
'type' : 'varchar(100)',
'javaName' : 'cnFourResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_DAYS',
'displayName' : '住院天数',
'type' : 'number(8)',
'javaName' : 'inpatientDays',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_CIRCUMSTANCE',
'displayName' : '入院情况',
'type' : 'varchar(200)',
'javaName' : 'inpatientCircumstance',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IN_CN_SYM_DIAG_CODE',
'displayName' : '入院诊断-中医征候诊断代码',
'type' : 'varchar(20)',
'javaName' : 'inCnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'IN_CN_DIS_DIAG_CODE',
'displayName' : '入院诊断-中医病名诊断代码',
'type' : 'varchar(20)',
'javaName' : 'inCnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'IN_DIAG_CODE',
'displayName' : '入院诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'inDiagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'IN_DIAG_VALUE',
'displayName' : '入院诊断-诊断名称',
'type' : 'varchar(20)',
'javaName' : 'inDiagValue',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IN_DIAG_DATE',
'displayName' : '入院诊断-诊断日期',
'type' : 'date',
'javaName' : 'inDiagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'OUT_CN_SYM_DIAG_CODE',
'displayName' : '出院诊断-中医征候诊断代码',
'type' : 'varchar(20)',
'javaName' : 'outCnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'OUT_CN_DIS_DIAG_CODE',
'displayName' : '出院诊断-中医病名诊断代码',
'type' : 'varchar(20)',
'javaName' : 'outCnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'OUT_DISCHARGE_SYMPTOM_AND_SIGN',
'displayName' : '出院诊断-出院时症状与体征',
'type' : 'varchar(20)',
'javaName' : 'outDischargeSymptomAndSign',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'OUT_DISCHARGE_CIRCUMSTANCE',
'displayName' : '出院诊断-出院情况',
'type' : 'varchar(100)',
'javaName' : 'outDischargeCircumstance',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'OUT_TREATMENT_RESULT_CODE',
'displayName' : '出院诊断-治疗结果代码',
'type' : 'varchar(40)',
'javaName' : 'outTreatmentResultCode',
'note' : '',
'nullable':true,
'check':'CV0510010'},
{
'name' : 'OUT_DIAG_CODE',
'displayName' : '出院诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'outDiagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'OUT_DIAG_VALUE',
'displayName' : '出院诊断-诊断名称',
'type' : 'varchar(20)',
'javaName' : 'outDiagValue',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUT_DIAG_DATE',
'displayName' : '出院诊断-诊断日期',
'type' : 'date',
'javaName' : 'outDiagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INCISION_TYPE_CODE',
'displayName' : '切口类别代码',
'type' : 'varchar(20)',
'javaName' : 'incisionTypeCode',
'note' : '',
'nullable':true,
'check':'CV0510022'},
{
'name' : 'INCISION_HEALING_RANK_CODE',
'displayName' : '切口愈合级别代码',
'type' : 'varchar(20)',
'javaName' : 'incisionHealingRankCode',
'note' : '',
'nullable':true,
'check':'CV550114'},
{
'name' : 'OPERATION_COURSES',
'displayName' : '手术过程',
'type' : 'varchar(2000)',
'javaName' : 'operationCourses',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_ID',
'displayName' : '手术单号',
'type' : 'varchar(20)',
'javaName' : 'operationId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANESTHESIA_CODE',
'displayName' : '麻醉方法代码',
'type' : 'varchar(20)',
'javaName' : 'anesthesiaCode',
'note' : '',
'nullable':true,
'check':'CV0600103'},
{
'name' : 'ANESTHESIA_WAY',
'displayName' : '麻醉方法',
'type' : 'varchar(100)',
'javaName' : 'anesthesiaWay',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PROCEDURE_START',
'displayName' : '手术开始时间',
'type' : 'date',
'javaName' : 'procedureStart',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PROCEDURE_END',
'displayName' : '手术结束时间',
'type' : 'date',
'javaName' : 'procedureEnd',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'THERAPEUTIC_PRINCIPLES',
'displayName' : '治则治法',
'type' : 'varchar(200)',
'javaName' : 'therapeuticPrinciples',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TREAT_RESCUE_COURSE',
'displayName' : '诊疗过程描述',
'type' : 'varchar(500)',
'javaName' : 'treatRescueCourse',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCHARGE_ADVICE',
'displayName' : '出院医嘱',
'type' : 'varchar(200)',
'javaName' : 'dischargeAdvice',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CN_PRESCRIBE_DESCR',
'displayName' : '中药煎煮法',
'type' : 'varchar(200)',
'javaName' : 'cnPrescribeDescr',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CN_DRUG_WAY_CD',
'displayName' : '中药服用方法代码',
'type' : 'varchar(20)',
'javaName' : 'cnDrugWayCd',
'note' : '',
'nullable':true,
'check':'CV9900304'},
{
'name' : 'POSITIVE_AUX_INSPECTION_RESULT',
'displayName' : '阳性辅助检查结果',
'type' : 'varchar(200)',
'javaName' : 'positiveAuxInspectionResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];