var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'HCR_DEATH_CASE_DISCUSSION_ID',
'displayName' : '死亡病例讨论记录id',
'type' : 'varchar(40)',
'javaName' : 'hcrDeathCaseDiscussionId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DISCUSSION_DATE',
'displayName' : '讨论日期时间',
'type' : 'date',
'javaName' : 'discussionDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DISCUSSION_SITES',
'displayName' : '讨论地点',
'type' : 'varchar(40)',
'javaName' : 'discussionSites',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CASE_NO',
'displayName' : '病案号',
'type' : 'varchar(20)',
'javaName' : 'caseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_TIMES',
'displayName' : '住院次数',
'type' : 'number(8)',
'javaName' : 'inpatTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REMARKS',
'displayName' : '备注',
'type' : 'text',
'javaName' : 'remarks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AGE',
'displayName' : '患者年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_TYPE',
'displayName' : '患者类型',
'type' : 'varchar(20)',
'javaName' : 'patientType',
'note' : '',
'nullable':true,
'check':'CV0900404'},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESIDENT_DOCTOR_SIGN_DATE',
'displayName' : '住院医师签名日期',
'type' : 'date',
'javaName' : 'residentDoctorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RESIDENT_DOCTOR_ID',
'displayName' : '住院医师id',
'type' : 'varchar(40)',
'javaName' : 'residentDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESIDENT_DOCTOR_NAME',
'displayName' : '住院医师姓名',
'type' : 'varchar(20)',
'javaName' : 'residentDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESIDENT_DOCTOR_POST_CODE',
'displayName' : '住院医师职务代码',
'type' : 'varchar(20)',
'javaName' : 'residentDoctorPostCode',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'ATTENDING_DOCTOR_SIGN_DATE',
'displayName' : '主治医师签名日期',
'type' : 'date',
'javaName' : 'attendingDoctorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ATTENDING_DOCTOR_ID',
'displayName' : '主治医师id',
'type' : 'varchar(40)',
'javaName' : 'attendingDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ATTENDING_DOCTOR_NAME',
'displayName' : '主治医师姓名',
'type' : 'varchar(20)',
'javaName' : 'attendingDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ATTENDING_DOCTOR_POST_CODE',
'displayName' : '主治医师职务代码',
'type' : 'varchar(20)',
'javaName' : 'attendingDoctorPostCode',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'DIRECTOR_DOCTOR_SIGN_DATE',
'displayName' : '主任医师签名日期',
'type' : 'date',
'javaName' : 'directorDoctorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DIRECTOR_DOCTOR_ID',
'displayName' : '主任医师id',
'type' : 'varchar(40)',
'javaName' : 'directorDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIRECTOR_DOCTOR_NAME',
'displayName' : '主任医师姓名',
'type' : 'varchar(20)',
'javaName' : 'directorDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIRECTOR_DOCTOR_POST_CODE',
'displayName' : '主任医师职务代码',
'type' : 'varchar(20)',
'javaName' : 'directorDoctorPostCode',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'DISCUSSION_MODERATOR_ID',
'displayName' : '讨论主持人id',
'type' : 'varchar(40)',
'javaName' : 'discussionModeratorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCUSSION_MODERATOR_NAME',
'displayName' : '讨论主持人姓名',
'type' : 'varchar(20)',
'javaName' : 'discussionModeratorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCUSSION_MODERATOR_SIGN_DATE',
'displayName' : '讨论主持人签名日期',
'type' : 'date',
'javaName' : 'discussionModeratorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DISCUSSION_ONE_ID',
'displayName' : '讨论成员1id',
'type' : 'varchar(40)',
'javaName' : 'discussionOneId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCUSSION_ONE_NAME',
'displayName' : '讨论成员1姓名',
'type' : 'varchar(20)',
'javaName' : 'discussionOneName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCUSSION_ONE_SIGN_DATE',
'displayName' : '讨论成员1签名日期',
'type' : 'date',
'javaName' : 'discussionOneSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DISCUSSION_TWO_ID',
'displayName' : '讨论成员2id',
'type' : 'varchar(40)',
'javaName' : 'discussionTwoId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCUSSION_TWO_NAME',
'displayName' : '讨论成员2姓名',
'type' : 'varchar(20)',
'javaName' : 'discussionTwoName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCUSSION_TWO_SIGN_DATE',
'displayName' : '讨论成员2签名日期',
'type' : 'date',
'javaName' : 'discussionTwoSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DISCUSSION_THREE_ID',
'displayName' : '讨论成员3id',
'type' : 'varchar(40)',
'javaName' : 'discussionThreeId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCUSSION_THREE_NAME',
'displayName' : '讨论成员3姓名',
'type' : 'varchar(20)',
'javaName' : 'discussionThreeName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCUSSION_THREE_SIGN_DATE',
'displayName' : '讨论成员3签名日期',
'type' : 'date',
'javaName' : 'discussionThreeSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(40)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(40)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DEATH_CAUSE_CODE',
'displayName' : '死亡原因代码',
'type' : 'varchar(20)',
'javaName' : 'deathCauseCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'DEATH_CAUSE_NAME',
'displayName' : '死亡原因名称',
'type' : 'varchar(40)',
'javaName' : 'deathCauseName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DEATH_DIAG_CODE',
'displayName' : '死亡诊断编码',
'type' : 'varchar(20)',
'javaName' : 'deathDiagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'DEATH_DIAG_NAME',
'displayName' : '死亡诊断名称',
'type' : 'varchar(40)',
'javaName' : 'deathDiagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCUSSION_CONTENT',
'displayName' : '讨论内容',
'type' : 'text',
'javaName' : 'discussionContent',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCUSSION_SUMMARIZE',
'displayName' : '讨论总结',
'type' : 'text',
'javaName' : 'discussionSummarize',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];