var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'VAGINAL_DELIVERY_RECORD_ID',
'displayName' : '院内阴道分娩记录id',
'type' : 'varchar(40)',
'javaName' : 'vaginalDeliveryRecordId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'TELECOM',
'displayName' : '电话号码',
'type' : 'varchar(20)',
'javaName' : 'telecom',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_TYPE',
'displayName' : '患者类型',
'type' : 'varchar(20)',
'javaName' : 'patientType',
'note' : '',
'nullable':true,
'check':'CV0900404'},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISIT_MARK',
'displayName' : '门诊或住院标识',
'type' : 'varchar(10)',
'javaName' : 'visitMark',
'note' : '',
'nullable':false,
'check':'CUS00010'},
{
'name' : 'REGISTRATION_ID',
'displayName' : '就诊流水号',
'type' : 'varchar(40)',
'javaName' : 'registrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_TIME',
'displayName' : '就诊时间',
'type' : 'date',
'javaName' : 'visitingTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_CONTROL_EXAMINER_ID',
'displayName' : '产程检查者id',
'type' : 'varchar(40)',
'javaName' : 'birthControlExaminerId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_CONTROL_EXAMINER_NAME',
'displayName' : '产程检查者姓名',
'type' : 'varchar(40)',
'javaName' : 'birthControlExaminerName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_CONTROL_EXAMINER_DATE',
'displayName' : '产程检查者签名日期',
'type' : 'date',
'javaName' : 'birthControlExaminerDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RECORDER_ID',
'displayName' : '记录人id',
'type' : 'varchar(40)',
'javaName' : 'recorderId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RECORDER_NAME',
'displayName' : '记录人姓名',
'type' : 'varchar(40)',
'javaName' : 'recorderName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RECORDER_DATE',
'displayName' : '记录人签名日期',
'type' : 'date',
'javaName' : 'recorderDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'GRAVIDITY',
'displayName' : '孕次',
'type' : 'number(8)',
'javaName' : 'gravidity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PARITY',
'displayName' : '产次',
'type' : 'number(8)',
'javaName' : 'parity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EXPECTED_CHILDBIRTH_DATE',
'displayName' : '预产期',
'type' : 'date',
'javaName' : 'expectedChildbirthDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DELIVERY_DATETIME',
'displayName' : '临产日期时间',
'type' : 'date',
'javaName' : 'deliveryDatetime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RUPTURE_MEMBRANES_DATETIME',
'displayName' : '胎膜破裂日期时间',
'type' : 'date',
'javaName' : 'ruptureMembranesDatetime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PRE_AMN_FLUID_DESCR',
'displayName' : '前羊水性状',
'type' : 'varchar(100)',
'javaName' : 'preAmnFluidDescr',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PRE_AMN_FLUID_AMOUNT',
'displayName' : '前羊水量',
'type' : 'number(8)',
'javaName' : 'preAmnFluidAmount',
'note' : 'mL',
'nullable':true,
'check':''},
{
'name' : 'UTERINE_CONTRACTION_STDATE',
'displayName' : '宫缩开始日期时间',
'type' : 'date',
'javaName' : 'uterineContractionStdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'FIRST_LABOR_TIME',
'displayName' : '第1产程时长',
'type' : 'number(8)',
'javaName' : 'firstLaborTime',
'note' : 'min',
'nullable':true,
'check':''},
{
'name' : 'CONTRACTION_START_TIME',
'displayName' : '宫口开全日期时间',
'type' : 'date',
'javaName' : 'contractionStartTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'SECOND_LABOR_TIME',
'displayName' : '第2产程时长',
'type' : 'number(8)',
'javaName' : 'secondLaborTime',
'note' : 'min',
'nullable':true,
'check':''},
{
'name' : 'DELIVERY_TIME',
'displayName' : '胎儿娩出日期时间',
'type' : 'date',
'javaName' : 'deliveryTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'THIRD_LABOR_TIME',
'displayName' : '第3产程时长',
'type' : 'number(8)',
'javaName' : 'thirdLaborTime',
'note' : 'min',
'nullable':true,
'check':''},
{
'name' : 'PLACENTA_TIME',
'displayName' : '胎盘娩出日期时间',
'type' : 'date',
'javaName' : 'placentaTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'TOTAL_LABOR_TIME',
'displayName' : '总产程时长',
'type' : 'number(8)',
'javaName' : 'totalLaborTime',
'note' : 'min',
'nullable':true,
'check':''},
{
'name' : 'FETUS_POSITION_CD',
'displayName' : '胎方位代码',
'type' : 'varchar(20)',
'javaName' : 'fetusPositionCd',
'note' : '',
'nullable':true,
'check':'CV0501007'},
{
'name' : 'IF_MIDWIFERY',
'displayName' : '胎儿娩出助产标志',
'type' : 'number(5)',
'javaName' : 'ifMidwifery',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'MIDWIFERY_WAY',
'displayName' : '助产方式',
'type' : 'varchar(100)',
'javaName' : 'midwiferyWay',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PLACENTA_SITU',
'displayName' : '胎盘娩出情况',
'type' : 'varchar(100)',
'javaName' : 'placentaSitu',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AMNIOTIC_COMPLETE_MARK',
'displayName' : '胎膜完整情况标志',
'type' : 'number(5)',
'javaName' : 'amnioticCompleteMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'AMN_FLUID_DESCR',
'displayName' : '羊水性状',
'type' : 'varchar(100)',
'javaName' : 'amnFluidDescr',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AMN_FLUID_AMOUNT',
'displayName' : '羊水量',
'type' : 'number(8)',
'javaName' : 'amnFluidAmount',
'note' : 'mL',
'nullable':true,
'check':''},
{
'name' : 'CHORDA_UMBILICALIS_LENGTH',
'displayName' : '脐带长度',
'type' : 'number(8)',
'javaName' : 'chordaUmbilicalisLength',
'note' : 'cm',
'nullable':true,
'check':''},
{
'name' : 'RAOGENG_BODY',
'displayName' : '绕颈身',
'type' : 'number(8)',
'javaName' : 'raogengBody',
'note' : '周',
'nullable':true,
'check':''},
{
'name' : 'IF_ABNORMAL_UMBILICAL_CORD',
'displayName' : '脐带异常标志',
'type' : 'number(5)',
'javaName' : 'ifAbnormalUmbilicalCord',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'PRODUCTION_DRUGS',
'displayName' : '产时用药',
'type' : 'varchar(40)',
'javaName' : 'productionDrugs',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PREVENTIVE_MEASURE',
'displayName' : '预防措施',
'type' : 'varchar(200)',
'javaName' : 'preventiveMeasure',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EPISIOTOMY_MARK',
'displayName' : '产妇会阴切开标志',
'type' : 'number(5)',
'javaName' : 'episiotomyMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'EPISIOTOMY',
'displayName' : '会阴切开位置',
'type' : 'varchar(200)',
'javaName' : 'episiotomy',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PERINEUM_STITCHES',
'displayName' : '会阴缝合针数',
'type' : 'number(3)',
'javaName' : 'perineumStitches',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PERINEAL_LACER_CD',
'displayName' : '会阴裂伤情况代码',
'type' : 'varchar(20)',
'javaName' : 'perinealLacerCd',
'note' : '',
'nullable':true,
'check':'CV0501010'},
{
'name' : 'PERINEAL_HEMATOMA_MARK',
'displayName' : '会阴血肿标志',
'type' : 'number(5)',
'javaName' : 'perinealHematomaMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'PERINEAL_HEMATOMA_SIZE',
'displayName' : '会阴血肿大小',
'type' : 'varchar(40)',
'javaName' : 'perinealHematomaSize',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PERINEAL_HEMATOMA_DEAL',
'displayName' : '会阴血肿处理',
'type' : 'varchar(100)',
'javaName' : 'perinealHematomaDeal',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANESTHESIA_CODE',
'displayName' : '麻醉方法代码',
'type' : 'varchar(20)',
'javaName' : 'anesthesiaCode',
'note' : '',
'nullable':true,
'check':'CV0600103'},
{
'name' : 'ANES_DRUG_NAME',
'displayName' : '麻醉药物名称',
'type' : 'varchar(40)',
'javaName' : 'anesDrugName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IF_VAGINA_LACER',
'displayName' : '阴道裂伤标志',
'type' : 'number(5)',
'javaName' : 'ifVaginaLacer',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'IF_VAGINA_HEMATOMA',
'displayName' : '阴道血肿标志',
'type' : 'number(5)',
'javaName' : 'ifVaginaHematoma',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'IF_CERVICAL_LACER',
'displayName' : '阴道裂伤标志',
'type' : 'number(5)',
'javaName' : 'ifCervicalLacer',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'CERVICAL_SUTURE',
'displayName' : '宫颈缝合情况',
'type' : 'varchar(100)',
'javaName' : 'cervicalSuture',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'POSTPARTUM_MEDICATION',
'displayName' : '产后用药',
'type' : 'varchar(100)',
'javaName' : 'postpartumMedication',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SUMMARY_DELIVERY_PROCESS',
'displayName' : '分娩过程摘要',
'type' : 'varchar(200)',
'javaName' : 'summaryDeliveryProcess',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UTERINE_CONTRACTION',
'displayName' : '宫缩情况',
'type' : 'varchar(200)',
'javaName' : 'uterineContraction',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UTERINE_CONDITIONS',
'displayName' : '子宫情况',
'type' : 'varchar(500)',
'javaName' : 'uterineConditions',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LOCHIA_SITUATION',
'displayName' : '恶露状况',
'type' : 'varchar(500)',
'javaName' : 'lochiaSituation',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PERINEAL_CONDITION',
'displayName' : '会阴情况',
'type' : 'varchar(500)',
'javaName' : 'perinealCondition',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REPAIR_PROCEDURE',
'displayName' : '修补手术过程',
'type' : 'varchar(500)',
'javaName' : 'repairProcedure',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CORD_BLOOD_MARK',
'displayName' : '存脐带血情况标志',
'type' : 'number(5)',
'javaName' : 'cordBloodMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'OP_POST_DIAG',
'displayName' : '产后诊断',
'type' : 'varchar(40)',
'javaName' : 'opPostDiag',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'POSTPARTUM_OBS_TIME',
'displayName' : '产后观察日期时间',
'type' : 'date',
'javaName' : 'postpartumObsTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'SBP',
'displayName' : '收缩压',
'type' : 'number(8)',
'javaName' : 'sbp',
'note' : 'mmHg',
'nullable':true,
'check':''},
{
'name' : 'DBP',
'displayName' : '舒张压',
'type' : 'number(8)',
'javaName' : 'dbp',
'note' : 'mmHg',
'nullable':true,
'check':''},
{
'name' : 'PULSES',
'displayName' : '脉搏',
'type' : 'number(8)',
'javaName' : 'pulses',
'note' : '次/min',
'nullable':true,
'check':''},
{
'name' : 'POSTPARTUM_HEART_RATE',
'displayName' : '产后心率',
'type' : 'number(8)',
'javaName' : 'postpartumHeartRate',
'note' : '次/min',
'nullable':true,
'check':''},
{
'name' : 'POSTPARTUM_LOSSBLOOD_AMOUNT',
'displayName' : '产后出血量',
'type' : 'number(8)',
'javaName' : 'postpartumLossbloodAmount',
'note' : 'mL',
'nullable':true,
'check':''},
{
'name' : 'POSTPARTUM_UC',
'displayName' : '产后宫缩',
'type' : 'number(8)',
'javaName' : 'postpartumUc',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'POSTPARTUM_FUNDUS_HEIGHT',
'displayName' : '产后宫底高度',
'type' : 'number(8)',
'javaName' : 'postpartumFundusHeight',
'note' : 'cm',
'nullable':true,
'check':''},
{
'name' : 'ANUS_EXAM',
'displayName' : '肛查',
'type' : 'varchar(200)',
'javaName' : 'anusExam',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'GENDER_CODE',
'displayName' : '新生儿性别代码',
'type' : 'varchar(20)',
'javaName' : 'genderCode',
'note' : '',
'nullable':true,
'check':'GBT22611'},
{
'name' : 'BIRTH_WEIGHT',
'displayName' : '新生儿出生体重',
'type' : 'number(8)',
'javaName' : 'birthWeight',
'note' : 'g',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_LENGTH',
'displayName' : '新生儿出生身长',
'type' : 'number(8)',
'javaName' : 'birthLength',
'note' : 'cm',
'nullable':true,
'check':''},
{
'name' : 'TUMOR_SIZE',
'displayName' : '产瘤大小',
'type' : 'varchar(40)',
'javaName' : 'tumorSize',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TUMOR_PART',
'displayName' : '产瘤部位',
'type' : 'varchar(40)',
'javaName' : 'tumorPart',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'APGAR_SCORE_INTERVAL_CD',
'displayName' : 'Apgar评分间隔时间代码',
'type' : 'varchar(20)',
'javaName' : 'apgarScoreIntervalCd',
'note' : '',
'nullable':true,
'check':'CV9900342'},
{
'name' : 'APGAR_SCORE',
'displayName' : 'Apgar评分值',
'type' : 'number(8)',
'javaName' : 'apgarScore',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DELIVERY_OUTCOME_CD',
'displayName' : '分娩结局代码',
'type' : 'varchar(20)',
'javaName' : 'deliveryOutcomeCd',
'note' : '',
'nullable':true,
'check':'CV9900306'},
{
'name' : 'NEWBORN_ABNORMAL_CD',
'displayName' : '新生儿异常情况代码',
'type' : 'varchar(20)',
'javaName' : 'newbornAbnormalCd',
'note' : '',
'nullable':true,
'check':'CV9900343'},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];