var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'FIRST_PRENATAL_FOLLOW_UP_SERVICE_ID',
'displayName' : '首次产前随访服务id',
'type' : 'varchar(40)',
'javaName' : 'firstPrenatalFollowUpServiceId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'GRAVIDITY',
'displayName' : '孕次',
'type' : 'number(8)',
'javaName' : 'gravidity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PARITY',
'displayName' : '产次',
'type' : 'number(8)',
'javaName' : 'parity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VAGINAL_DELIVERY_TIMES',
'displayName' : '阴道分娩次数',
'type' : 'number(8)',
'javaName' : 'vaginalDeliveryTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CESAREAN_SECTION',
'displayName' : '阴道分娩次数',
'type' : 'number(8)',
'javaName' : 'cesareanSection',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IF_LAST_MENSTRUAL',
'displayName' : '末次月经日期明确标志',
'type' : 'number(5)',
'javaName' : 'ifLastMenstrual',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'EXPECTED_CHILDBIRTH_DATE',
'displayName' : '预产期',
'type' : 'date',
'javaName' : 'expectedChildbirthDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ABORTION_TOTAL_NUMBER',
'displayName' : '流产总次数',
'type' : 'number(8)',
'javaName' : 'abortionTotalNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'STILLBIRTH_CASES_NUMBER',
'displayName' : '死产例数',
'type' : 'number(8)',
'javaName' : 'stillbirthCasesNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CASES_NUMBER',
'displayName' : '死胎例数',
'type' : 'number(8)',
'javaName' : 'casesNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NEONATAL_DEATH_RECIPROCAL',
'displayName' : '新生儿死亡倒数',
'type' : 'number(8)',
'javaName' : 'neonatalDeathReciprocal',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_DEFECTS_NUMBER',
'displayName' : '出生缺陷儿例数',
'type' : 'number(8)',
'javaName' : 'birthDefectsNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HISTORY',
'displayName' : '既往史',
'type' : 'text',
'javaName' : 'history',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IF_GYNECOLOGIC_SURGERY_HISTORY',
'displayName' : '妇科手术史标志',
'type' : 'number(5)',
'javaName' : 'ifGynecologicSurgeryHistory',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'GYNECOLOGIC_SURGERY_HISTORY',
'displayName' : '妇科手术史',
'type' : 'text',
'javaName' : 'gynecologicSurgeryHistory',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PREGNANCY_COMPLICATIONS',
'displayName' : '妊娠合并症/并发症史',
'type' : 'text',
'javaName' : 'pregnancyComplications',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EXPOSURE_HAZARDOUS_FACTORS',
'displayName' : '接触有害因素类别代码',
'type' : 'varchar(20)',
'javaName' : 'exposureHazardousFactors',
'note' : '',
'nullable':true,
'check':'CV0300403'},
{
'name' : 'FAMILY_HISTORY_DISEASE',
'displayName' : '家族既往患病种类代码',
'type' : 'varchar(20)',
'javaName' : 'familyHistoryDisease',
'note' : '',
'nullable':true,
'check':'CV0210005'},
{
'name' : 'SBP',
'displayName' : '收缩压(收缩压的测量值，计量单位为mmHg)',
'type' : 'number(4)',
'javaName' : 'sbp',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DBP',
'displayName' : '舒张压(舒张压的测量值，计量单位为mmHg)',
'type' : 'number(4)',
'javaName' : 'dbp',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_LENGTH',
'displayName' : '身长（cm）',
'type' : 'number(8)',
'javaName' : 'birthLength',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_WEIGHT',
'displayName' : '体重（g）',
'type' : 'number(8)',
'javaName' : 'birthWeight',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BODY_MASS_INDEX',
'displayName' : '体质指数',
'type' : 'varchar(40)',
'javaName' : 'bodyMassIndex',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CARDIAC_AUSCULTATION_ABNORMAL_SIGN',
'displayName' : '心脏听诊异常标志',
'type' : 'number(5)',
'javaName' : 'cardiacAuscultationAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'CARDIAC_AUSCULTATION_RESULTS',
'displayName' : '心脏听诊异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'cardiacAuscultationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LUNG_AUSCULTATION_ABNORMAL_SIGN',
'displayName' : '肺部听诊异常标志',
'type' : 'number(5)',
'javaName' : 'lungAuscultationAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'LUNG_AUSCULTATION_RESULTS',
'displayName' : '肺部听诊异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'lungAuscultationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EXTERNAL_GENITAL_ORGANS_ABNORMAL_SIGN',
'displayName' : '外生殖器检查异常标志',
'type' : 'number(5)',
'javaName' : 'externalGenitalOrgansAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'EXTERNAL_GENITAL_ORGANS_RESULTS',
'displayName' : '外生殖器检查异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'externalGenitalOrgansResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VAGINA_ABNORMAL_SIGN',
'displayName' : '阴道异常标志',
'type' : 'number(5)',
'javaName' : 'vaginaAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'VAGINA_ABNORMAL_DESCRIBE',
'displayName' : '阴道异常描述',
'type' : 'varchar(40)',
'javaName' : 'vaginaAbnormalDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CERVICAL_ABNORMAL_SIGN',
'displayName' : '宫颈异常标志',
'type' : 'number(5)',
'javaName' : 'cervicalAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'CERVICAL_ABNORMAL_DESCRIBE',
'displayName' : '宫颈异常描述',
'type' : 'varchar(40)',
'javaName' : 'cervicalAbnormalDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PALACE_ABNORMAL_SIGN',
'displayName' : '宫体异常标志',
'type' : 'number(5)',
'javaName' : 'palaceAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'PALACE_ABNORMAL_DESCRIBE',
'displayName' : '宫体异常描述',
'type' : 'varchar(40)',
'javaName' : 'palaceAbnormalDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ENCLOSURE_ABNORMAL_SIGN',
'displayName' : '附件异常标志',
'type' : 'number(5)',
'javaName' : 'enclosureAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ENCLOSURE_ABNORMAL_DESCRIBE',
'displayName' : '附件异常描述',
'type' : 'varchar(40)',
'javaName' : 'enclosureAbnormalDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEMOGLOBIN',
'displayName' : '血红蛋白',
'type' : 'number(8)',
'javaName' : 'hemoglobin',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WHITE_BLOOD_CELL',
'displayName' : '白细胞',
'type' : 'number(8)',
'javaName' : 'whiteBloodCell',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PLATELET',
'displayName' : '血小板',
'type' : 'number(8)',
'javaName' : 'platelet',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'URINE_PROTEIN',
'displayName' : '尿蛋白定量检测值（mg/24h）',
'type' : 'number(8)',
'javaName' : 'urineProtein',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'URINE_PROTEIN_QUALITATIVE_TEST_RESULT_CODE',
'displayName' : '尿蛋白定性检测结果代码',
'type' : 'varchar(20)',
'javaName' : 'urineProteinQualitativeTestResultCode',
'note' : '',
'nullable':true,
'check':'CV0450015'},
{
'name' : 'NIAOTANG',
'displayName' : '尿糖定量检测（mmol/L）',
'type' : 'number(8)',
'javaName' : 'niaotang',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NIAOTANG_QUALITATIVE_TEST_RESULT_CODE',
'displayName' : '尿糖定性检测结果代码',
'type' : 'varchar(20)',
'javaName' : 'niaotangQualitativeTestResultCode',
'note' : '',
'nullable':true,
'check':'CV0450015'},
{
'name' : 'URINE_KETONE_QUALITATIVE_TEST_RESULT_CODE',
'displayName' : '尿酮体定性检测结果代码',
'type' : 'varchar(20)',
'javaName' : 'urineKetoneQualitativeTestResultCode',
'note' : '',
'nullable':true,
'check':'CV0450015'},
{
'name' : 'BLD_QUALITATIVE_TEST_RESULT_CODE',
'displayName' : '尿潜血定性检测结果代码',
'type' : 'varchar(20)',
'javaName' : 'bldQualitativeTestResultCode',
'note' : '',
'nullable':true,
'check':'CV0450015'},
{
'name' : 'BLOOD_SUGAR',
'displayName' : '血糖检测值（mmol/L）',
'type' : 'number(8)',
'javaName' : 'bloodSugar',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SERUM_ALANINE_AMINOTRANSFERASE',
'displayName' : '血清谷丙转氨酶',
'type' : 'number(8)',
'javaName' : 'serumAlanineAminotransferase',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SERUM_ASPARTATE_AMINOTRANSFERASE',
'displayName' : '血清谷草转氨酶',
'type' : 'number(8)',
'javaName' : 'serumAspartateAminotransferase',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ALBUMIN',
'displayName' : '白蛋白',
'type' : 'number(8)',
'javaName' : 'albumin',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TOTAL_BILIRUBIN',
'displayName' : '总胆红素',
'type' : 'number(8)',
'javaName' : 'totalBilirubin',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONJUGATED_BILIRUBIN',
'displayName' : '结合胆红素',
'type' : 'number(8)',
'javaName' : 'conjugatedBilirubin',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SCR',
'displayName' : '血清肌酐',
'type' : 'number(8)',
'javaName' : 'scr',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BLOOD_UREA_NITROGEN',
'displayName' : '血尿素氮',
'type' : 'number(8)',
'javaName' : 'bloodUreaNitrogen',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ABO_CD',
'displayName' : 'ABO血型代码',
'type' : 'varchar(20)',
'javaName' : 'aboCd',
'note' : '',
'nullable':true,
'check':'CV0450005'},
{
'name' : 'RH_CD',
'displayName' : 'RH血型代码',
'type' : 'varchar(20)',
'javaName' : 'rhCd',
'note' : '',
'nullable':true,
'check':'CV0450020'},
{
'name' : 'VAGINAL_SECRETION_EXAMINATION_RESULT_CODE',
'displayName' : '阴道分泌物检查结果代码',
'type' : 'varchar(20)',
'javaName' : 'vaginalSecretionExaminationResultCode',
'note' : '',
'nullable':true,
'check':'CV0450019'},
{
'name' : 'VAGINAL_CLEANER_CODE',
'displayName' : '阴道分泌物清洁度代码',
'type' : 'varchar(20)',
'javaName' : 'vaginalCleanerCode',
'note' : '',
'nullable':true,
'check':'CV0450010'},
{
'name' : 'BSCAN_RESULT_DESCR',
'displayName' : 'B超检查结果',
'type' : 'varchar(100)',
'javaName' : 'bscanResultDescr',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MATERNAL_HEALTH_ASSESSMENT',
'displayName' : '孕产妇健康评估异常标志',
'type' : 'number(5)',
'javaName' : 'maternalHealthAssessment',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'MATERNAL_HEALTH_RESULT_DESCR',
'displayName' : '孕产妇健康评估异常结果描述',
'type' : 'varchar(100)',
'javaName' : 'maternalHealthResultDescr',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_INSTRUCTION_CODE',
'displayName' : '健康指导代码',
'type' : 'varchar(20)',
'javaName' : 'healthInstructionCode',
'note' : '',
'nullable':true,
'check':'CV9900017'},
{
'name' : 'REFERRAL_MARK',
'displayName' : '转诊标志',
'type' : 'number(5)',
'javaName' : 'referralMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'REFERRAL_REASONS',
'displayName' : '转诊原因',
'type' : 'varchar(40)',
'javaName' : 'referralReasons',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REFERRAL_IN_ORG',
'displayName' : '转入机构的名称',
'type' : 'varchar(40)',
'javaName' : 'referralInOrg',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REFERRAL_IN_DEP',
'displayName' : '转入科室的名称',
'type' : 'varchar(40)',
'javaName' : 'referralInDep',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NEXT_FOLLOW_UP_DATE',
'displayName' : '下次随访日期',
'type' : 'date',
'javaName' : 'nextFollowUpDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'NEXT_VISIT_LOCATION',
'displayName' : '下次访视地点',
'type' : 'varchar(40)',
'javaName' : 'nextVisitLocation',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];