var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'OPERATION_RECORD_ID',
'displayName' : '院内一般手术记录id',
'type' : 'varchar(40)',
'javaName' : 'operationRecordId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'TELECOM',
'displayName' : '电话号码',
'type' : 'varchar(20)',
'javaName' : 'telecom',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_TYPE',
'displayName' : '患者类型',
'type' : 'varchar(20)',
'javaName' : 'patientType',
'note' : '',
'nullable':true,
'check':'CV0900404'},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISIT_MARK',
'displayName' : '门诊或住院标识',
'type' : 'varchar(10)',
'javaName' : 'visitMark',
'note' : '',
'nullable':false,
'check':'CUS00010'},
{
'name' : 'REGISTRATION_ID',
'displayName' : '就诊流水号',
'type' : 'varchar(40)',
'javaName' : 'registrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_TIME',
'displayName' : '就诊时间',
'type' : 'date',
'javaName' : 'visitingTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_OP_MARK',
'displayName' : '手术史标志',
'type' : 'varchar(20)',
'javaName' : 'inpatOpMark',
'note' : '',
'nullable':true,
'check':'CV9900024'},
{
'name' : 'PREOPERATIVE_DIAGNOSIS',
'displayName' : '术前诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'preoperativeDiagnosis',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'PREOPERATIVE_DIAGNOSIS_NAME',
'displayName' : '术前诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'preoperativeDiagnosisName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PREOPERATIVE_DIAGNOSIS_DATE',
'displayName' : '术前诊断-诊断日期',
'type' : 'date',
'javaName' : 'preoperativeDiagnosisDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AFTER_OPERATION_DIAGNOSIS',
'displayName' : '术后诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'afterOperationDiagnosis',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'AFTER_OPERATION_DIAGNOSIS_NAME',
'displayName' : '术后诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'afterOperationDiagnosisName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AFTER_OPERATION_DIAGNOSIS_DATE',
'displayName' : '术后诊断-诊断日期',
'type' : 'date',
'javaName' : 'afterOperationDiagnosisDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'OPERATION_ID',
'displayName' : '手术单id',
'type' : 'varchar(40)',
'javaName' : 'operationId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OP_ROOM',
'displayName' : '手术间编号',
'type' : 'varchar(40)',
'javaName' : 'opRoom',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OP_LEVEL_CD',
'displayName' : '手术级别代码',
'type' : 'varchar(20)',
'javaName' : 'opLevelCd',
'note' : '',
'nullable':true,
'check':'CV9900040'},
{
'name' : 'TRANSFUSION_ITEM_AMOUNT',
'displayName' : '输血量',
'type' : 'number(8)',
'javaName' : 'transfusionItemAmount',
'note' : '单位：mL',
'nullable':true,
'check':''},
{
'name' : 'TRANSFUSE_REACTION_FLAG',
'displayName' : '输血反应标志',
'type' : 'number(5)',
'javaName' : 'transfuseReactionFlag',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'OP_PRE_DRUG',
'displayName' : '术前用药',
'type' : 'varchar(100)',
'javaName' : 'opPreDrug',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OP_DRUG',
'displayName' : '术中用药',
'type' : 'varchar(100)',
'javaName' : 'opDrug',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LOSSBLOOD_AMOUNT',
'displayName' : '出血量',
'type' : 'number(8)',
'javaName' : 'lossbloodAmount',
'note' : '单位：mL',
'nullable':true,
'check':''},
{
'name' : 'INFUSION_AMOUNT',
'displayName' : '输液量',
'type' : 'number(8)',
'javaName' : 'infusionAmount',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_COURSE',
'displayName' : '手术经过',
'type' : 'varchar(1000)',
'javaName' : 'operationCourse',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INTERVENTION',
'displayName' : '介入物名称',
'type' : 'varchar(40)',
'javaName' : 'intervention',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SKIN_THIMEROSAL',
'displayName' : '皮肤消毒描述',
'type' : 'varchar(100)',
'javaName' : 'skinThimerosal',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WOUND_DESCR',
'displayName' : '手术切口描述',
'type' : 'varchar(100)',
'javaName' : 'woundDescr',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IF_DRAIN',
'displayName' : '引流标志代码',
'type' : 'number(5)',
'javaName' : 'ifDrain',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'DRAIN_MATERIAL_AMOUNT',
'displayName' : '引流材料数量',
'type' : 'number(8)',
'javaName' : 'drainMaterialAmount',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRAIN_MATERIAL_NAME',
'displayName' : '引流材料名称',
'type' : 'varchar(100)',
'javaName' : 'drainMaterialName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PLACED_PART',
'displayName' : '放置部位',
'type' : 'varchar(100)',
'javaName' : 'placedPart',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANESTHESIA_METHOD_CD',
'displayName' : '麻醉方法代码',
'type' : 'varchar(20)',
'javaName' : 'anesthesiaMethodCd',
'note' : '',
'nullable':true,
'check':'CV0600103'},
{
'name' : 'ANESTHESIA_METHOD_NAME',
'displayName' : '麻醉方法名称',
'type' : 'varchar(40)',
'javaName' : 'anesthesiaMethodName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_CD',
'displayName' : '手术编码',
'type' : 'varchar(20)',
'javaName' : 'operationCd',
'note' : '',
'nullable':true,
'check':'CV990113'},
{
'name' : 'OPERATION_NAME',
'displayName' : '手术名称',
'type' : 'varchar(40)',
'javaName' : 'operationName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PART_CODE',
'displayName' : '手术操作目标部位代码',
'type' : 'varchar(20)',
'javaName' : 'partCode',
'note' : '',
'nullable':true,
'check':'CV0600227'},
{
'name' : 'PART_NAME',
'displayName' : '手术操作目标部位名称',
'type' : 'varchar(20)',
'javaName' : 'partName',
'note' : '',
'nullable':true,
'check':'CV0600227'},
{
'name' : 'OPERATIVE',
'displayName' : '手术者id',
'type' : 'varchar(40)',
'javaName' : 'operative',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATIVE_NAME',
'displayName' : '手术者姓名',
'type' : 'varchar(40)',
'javaName' : 'operativeName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FIRST_ASSISTANT',
'displayName' : 'I助id',
'type' : 'varchar(40)',
'javaName' : 'firstAssistant',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FIRST_ASSISTANT_NAME',
'displayName' : 'I助姓名',
'type' : 'varchar(40)',
'javaName' : 'firstAssistantName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SECOND_ASSISTANT',
'displayName' : 'II助id',
'type' : 'varchar(40)',
'javaName' : 'secondAssistant',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SECOND_ASSISTANT_NAME',
'displayName' : 'II助姓名',
'type' : 'varchar(40)',
'javaName' : 'secondAssistantName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EQUIPMENT_MANAGER',
'displayName' : '器材管理者id',
'type' : 'varchar(40)',
'javaName' : 'equipmentManager',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EQUIPMENT_MANAGER_NAME',
'displayName' : '器材管理者姓名',
'type' : 'varchar(40)',
'javaName' : 'equipmentManagerName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATROL_NURSE',
'displayName' : '巡台护士id',
'type' : 'varchar(40)',
'javaName' : 'patrolNurse',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATROL_NURSE_NAME',
'displayName' : '巡台护士姓名',
'type' : 'varchar(40)',
'javaName' : 'patrolNurseName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANAESTHETIC',
'displayName' : '麻醉者id',
'type' : 'varchar(40)',
'javaName' : 'anaesthetic',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANAESTHETIC_NAME',
'displayName' : '麻醉者姓名',
'type' : 'varchar(40)',
'javaName' : 'anaestheticName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PERFORMED_START',
'displayName' : '手术开始时间',
'type' : 'date',
'javaName' : 'performedStart',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PERFORMED_END',
'displayName' : '手术结束时间',
'type' : 'date',
'javaName' : 'performedEnd',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];