var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'IPN_SUPERIOR_INSPECTION_RECORDS_ID',
'displayName' : '上级医师查房记录id',
'type' : 'varchar(40)',
'javaName' : 'ipnSuperiorInspectionRecordsId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'CASE_NO',
'displayName' : '病案号',
'type' : 'varchar(20)',
'javaName' : 'caseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_TIMES',
'displayName' : '住院次数',
'type' : 'number(8)',
'javaName' : 'inpatTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REMARKS',
'displayName' : '备注',
'type' : 'text',
'javaName' : 'remarks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'CN_FOUR_RESULT',
'displayName' : '中医&quot;四诊&quot;观察结果',
'type' : 'varchar(200)',
'javaName' : 'cnFourResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ATTENDING_DOCTOR_SIGN_DATE',
'displayName' : '主治医师签名日期',
'type' : 'date',
'javaName' : 'attendingDoctorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ATTENDING_DOCTOR_ID',
'displayName' : '主治医师id',
'type' : 'varchar(40)',
'javaName' : 'attendingDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ATTENDING_DOCTOR_NAME',
'displayName' : '主治医师姓名',
'type' : 'varchar(20)',
'javaName' : 'attendingDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ATTENDING_DOCTOR_POST_CODE',
'displayName' : '主治医师职务代码',
'type' : 'varchar(20)',
'javaName' : 'attendingDoctorPostCode',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'DIRECTOR_DOCTOR_SIGN_DATE',
'displayName' : '主任医师签名日期',
'type' : 'date',
'javaName' : 'directorDoctorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DIRECTOR_DOCTOR_ID',
'displayName' : '主任医师id',
'type' : 'varchar(40)',
'javaName' : 'directorDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIRECTOR_DOCTOR_NAME',
'displayName' : '主任医师姓名',
'type' : 'varchar(20)',
'javaName' : 'directorDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIRECTOR_DOCTOR_POST_CODE',
'displayName' : '主任医师职务代码',
'type' : 'varchar(20)',
'javaName' : 'directorDoctorPostCode',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'RECORD_SIGN_DATE',
'displayName' : '记录人签名日期',
'type' : 'date',
'javaName' : 'recordSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RECORD_ID',
'displayName' : '记录人id',
'type' : 'varchar(40)',
'javaName' : 'recordId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RECORD_NAME',
'displayName' : '记录人姓名',
'type' : 'varchar(20)',
'javaName' : 'recordName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_ROUNDS_DATE',
'displayName' : '查房时间',
'type' : 'date',
'javaName' : 'wardRoundsDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'WARD_ROUNDS_RECORD',
'displayName' : '查房记录',
'type' : 'varchar(100)',
'javaName' : 'wardRoundsRecord',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIALECTICAL_TREATMENT',
'displayName' : '辩证论治',
'type' : 'varchar(100)',
'javaName' : 'dialecticalTreatment',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ASSESSMENT_PLAN',
'displayName' : '诊疗计划',
'type' : 'varchar(500)',
'javaName' : 'assessmentPlan',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CN_PRESCRIBE_DESCR',
'displayName' : '中药煎煮法',
'type' : 'varchar(100)',
'javaName' : 'cnPrescribeDescr',
'note' : '中药饮片煎煮方法描述',
'nullable':true,
'check':''},
{
'name' : 'CN_PRESCRIBE',
'displayName' : '医嘱内容',
'type' : 'varchar(100)',
'javaName' : 'cnPrescribe',
'note' : '中药饮片煎煮方法描述',
'nullable':true,
'check':''},
{
'name' : 'CN_DRUG_WAY_CD',
'displayName' : '中药服用方法代码',
'type' : 'varchar(20)',
'javaName' : 'cnDrugWayCd',
'note' : '',
'nullable':true,
'check':'CV9900304'},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];