var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'SURGICAL_NURSING_RECORD_ID',
'displayName' : '院内手术护理记录id',
'type' : 'varchar(40)',
'javaName' : 'surgicalNursingRecordId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CN_FOUR_RESULT',
'displayName' : '中医&quot;四诊&quot;观察结果',
'type' : 'varchar(200)',
'javaName' : 'cnFourResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IN_MODE_CODE',
'displayName' : '入院途径',
'type' : 'varchar(20)',
'javaName' : 'inModeCode',
'note' : '',
'nullable':true,
'check':'CV0900403'},
{
'name' : 'INHOSPITAL_REASON_CD',
'displayName' : '住院原因代码',
'type' : 'varchar(20)',
'javaName' : 'inhospitalReasonCd',
'note' : '',
'nullable':true,
'check':'CV0600212'},
{
'name' : 'INHOSPITAL_WAY',
'displayName' : '入病房方式',
'type' : 'varchar(40)',
'javaName' : 'inhospitalWay',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRANSFER_NURSE_ID',
'displayName' : '交接护士id',
'type' : 'varchar(40)',
'javaName' : 'transferNurseId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRANSFER_NURSE_NAME',
'displayName' : '交接护士姓名',
'type' : 'varchar(40)',
'javaName' : 'transferNurseName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRANSFER_NURSE_DATE',
'displayName' : '交接护士签名日期',
'type' : 'date',
'javaName' : 'transferNurseDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'TRANSPORTERS_NURSE_ID',
'displayName' : '转运者id',
'type' : 'varchar(40)',
'javaName' : 'transportersNurseId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRANSPORTERS_NURSE_NAME',
'displayName' : '转运者姓名',
'type' : 'varchar(40)',
'javaName' : 'transportersNurseName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRANSPORTERS_NURSE_DATE',
'displayName' : '转运者签名日期',
'type' : 'date',
'javaName' : 'transportersNurseDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CN_SYM_DIAG_CODE',
'displayName' : '中医症候代码',
'type' : 'varchar(20)',
'javaName' : 'cnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'CN_DIS_DIAG_CODE',
'displayName' : '中医病名代码',
'type' : 'varchar(20)',
'javaName' : 'cnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'DIAG_CODE',
'displayName' : '诊断编码',
'type' : 'varchar(20)',
'javaName' : 'diagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'DIAG_NAME',
'displayName' : '诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'diagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIAG_DATE',
'displayName' : '诊断日期',
'type' : 'date',
'javaName' : 'diagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'VISITING_TYPE',
'displayName' : '就诊类型',
'type' : 'varchar(20)',
'javaName' : 'visitingType',
'note' : '',
'nullable':true,
'check':'CV9900340'},
{
'name' : 'WEIGHT',
'displayName' : '体重(kg)',
'type' : 'number(8)',
'javaName' : 'weight',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ABO_CD',
'displayName' : 'ABO血型代码',
'type' : 'varchar(20)',
'javaName' : 'aboCd',
'note' : '',
'nullable':true,
'check':'CV0450005'},
{
'name' : 'RH_CD',
'displayName' : 'RH血型代码',
'type' : 'varchar(20)',
'javaName' : 'rhCd',
'note' : '',
'nullable':true,
'check':'CV0450020'},
{
'name' : 'SKIN_CHECK_DESCRIPTION',
'displayName' : '皮肤检查描述',
'type' : 'text',
'javaName' : 'skinCheckDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_ALLE_MARK',
'displayName' : '患者过敏史标志',
'type' : 'varchar(20)',
'javaName' : 'inpatAlleMark',
'note' : '',
'nullable':true,
'check':'CV9900024'},
{
'name' : 'RRITABILITY',
'displayName' : '过敏史描述',
'type' : 'text',
'javaName' : 'rritability',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PAT_HANDOVER_ITEM',
'displayName' : '病人交接核对项目',
'type' : 'varchar(100)',
'javaName' : 'patHandoverItem',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NURSING_NAME',
'displayName' : '护理操作名称',
'type' : 'varchar(40)',
'javaName' : 'nursingName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NURSING_ITEM_NAME',
'displayName' : '护理操作项目类目名称',
'type' : 'varchar(40)',
'javaName' : 'nursingItemName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NURSING_RESULT_DESCRIPTION',
'displayName' : '护理操作结果描述',
'type' : 'varchar(200)',
'javaName' : 'nursingResultDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NURSING_TYPE',
'displayName' : '护理等级代码',
'type' : 'varchar(20)',
'javaName' : 'nursingType',
'note' : '',
'nullable':true,
'check':'CV9900330'},
{
'name' : 'NURSING_GRADE',
'displayName' : '护理类型代码',
'type' : 'varchar(20)',
'javaName' : 'nursingGrade',
'note' : '',
'nullable':true,
'check':'CV9900331'},
{
'name' : 'OBSERVATION_PROJECT_NAME',
'displayName' : '护理观察项目名称',
'type' : 'varchar(40)',
'javaName' : 'observationProjectName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OBSERVATION_RESULTS_DESCRIPTION',
'displayName' : '护理观察结果',
'type' : 'varchar(200)',
'javaName' : 'observationResultsDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_ITEMS_NAME',
'displayName' : '术中所用物品名称',
'type' : 'varchar(40)',
'javaName' : 'operationItemsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IF_PREOPERATIVE_INVENTORY',
'displayName' : '术前清点标志',
'type' : 'number(5)',
'javaName' : 'ifPreoperativeInventory',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'IF_PRE_MATERIAL_CHECK',
'displayName' : '关前核对标志',
'type' : 'number(5)',
'javaName' : 'ifPreMaterialCheck',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'IF_POST_MATERIAL_CHECK',
'displayName' : '关后核对标志',
'type' : 'number(5)',
'javaName' : 'ifPostMaterialCheck',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'OP_PATHOLOGY_DN',
'displayName' : '术中病理标志',
'type' : 'number(5)',
'javaName' : 'opPathologyDn',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'PRE_OPERATIVE_PREPARATION',
'displayName' : '准备事项',
'type' : 'varchar(200)',
'javaName' : 'preOperativePreparation',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OP_ROOM_NO',
'displayName' : '手术间编号',
'type' : 'varchar(40)',
'javaName' : 'opRoomNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IN_OPERATING_ROOM_TIME',
'displayName' : '入手术室日期时间',
'type' : 'date',
'javaName' : 'inOperatingRoomTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'OUT_OPERATING_ROOM_TIME',
'displayName' : '出手术室日期时间',
'type' : 'date',
'javaName' : 'outOperatingRoomTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INCISION_TYPE_CODE',
'displayName' : '切口类别代码',
'type' : 'varchar(20)',
'javaName' : 'incisionTypeCode',
'note' : '',
'nullable':true,
'check':'CV0510022'},
{
'name' : 'INCISION_HEALING_RANK_CODE',
'displayName' : '切口愈合级别代码',
'type' : 'varchar(20)',
'javaName' : 'incisionHealingRankCode',
'note' : '',
'nullable':true,
'check':'CV550114'},
{
'name' : 'OPERATION_COURSES',
'displayName' : '手术过程',
'type' : 'varchar(2000)',
'javaName' : 'operationCourses',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_ID',
'displayName' : '手术单号',
'type' : 'varchar(40)',
'javaName' : 'operationId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANESTHESIA_CODE',
'displayName' : '麻醉方法代码',
'type' : 'varchar(20)',
'javaName' : 'anesthesiaCode',
'note' : '',
'nullable':true,
'check':'CV0600103'},
{
'name' : 'ANESTHESIA_WAY',
'displayName' : '麻醉方法',
'type' : 'varchar(100)',
'javaName' : 'anesthesiaWay',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_CD',
'displayName' : '手术编码',
'type' : 'varchar(20)',
'javaName' : 'operationCd',
'note' : '',
'nullable':true,
'check':'CV990113'},
{
'name' : 'OPERATION_NAME',
'displayName' : '手术名称',
'type' : 'varchar(40)',
'javaName' : 'operationName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PART_CODE',
'displayName' : '手术操作目标部位代码',
'type' : 'varchar(20)',
'javaName' : 'partCode',
'note' : '',
'nullable':true,
'check':'CV0600227'},
{
'name' : 'PART_NAME',
'displayName' : '手术操作目标部位名称',
'type' : 'varchar(20)',
'javaName' : 'partName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATIVE',
'displayName' : '手术者id',
'type' : 'varchar(40)',
'javaName' : 'operative',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATIVE_NAME',
'displayName' : '手术者姓名',
'type' : 'varchar(40)',
'javaName' : 'operativeName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EQUIPMENT_MANAGER',
'displayName' : '器材管理者id',
'type' : 'varchar(40)',
'javaName' : 'equipmentManager',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EQUIPMENT_MANAGER_NAME',
'displayName' : '器材管理者姓名',
'type' : 'varchar(40)',
'javaName' : 'equipmentManagerName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATROL_NURSE',
'displayName' : '巡台护士id',
'type' : 'varchar(40)',
'javaName' : 'patrolNurse',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATROL_NURSE_NAME',
'displayName' : '巡台护士姓名',
'type' : 'varchar(40)',
'javaName' : 'patrolNurseName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PROCEDURE_START',
'displayName' : '手术开始时间',
'type' : 'date',
'javaName' : 'procedureStart',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PROCEDURE_END',
'displayName' : '手术结束时间',
'type' : 'date',
'javaName' : 'procedureEnd',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];