var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'DIAGNOSIS_PROVE_ID',
'displayName' : '诊断证明id',
'type' : 'varchar(20)',
'javaName' : 'diagnosisProveId',
'note' : '诊断证明在院内系统中的唯一标识',
'nullable':false,
'check':''},
{
'name' : 'RECORD_DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'recordDate',
'note' : '出门（急）诊病历报告的日期时间',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '引用患者信息表T_PATIENT院内患者id',
'nullable':false,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(3)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':true,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '引用住院基础信息表T_INPATIENT院内住院流水号',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'END',
'displayName' : '出院时间',
'type' : 'date',
'javaName' : 'end',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INPAT_DAYS',
'displayName' : '住院天数',
'type' : 'number(3)',
'javaName' : 'inpatDays',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TREAT_RESCUE_COURSE',
'displayName' : '治疗过程描述',
'type' : 'text',
'javaName' : 'treatRescueCourse',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUT_MAIN_DIAGNOSIS_NAME',
'displayName' : '出院主要诊断名称',
'type' : 'varchar(100)',
'javaName' : 'outMainDiagnosisName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUT_ACCOMPANY_DIAGNOSIS_NAME',
'displayName' : '出院伴随诊断名称',
'type' : 'varchar(100)',
'javaName' : 'outAccompanyDiagnosisName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCHARGE_ADVICE_MEDICINE',
'displayName' : '出院建议及带药',
'type' : 'varchar(500)',
'javaName' : 'dischargeAdviceMedicine',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PHYSICIAN',
'displayName' : '医师签名',
'type' : 'varchar(20)',
'javaName' : 'physician',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '医疗机构在爱心医疗云平台中的唯一编码',
'nullable':false,
'check':''}
];