var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'MEDICATION_CD',
'displayName' : '院内药品编码',
'type' : 'varchar(40)',
'javaName' : 'medicationCd',
'note' : '药品在院内系统中的编码',
'nullable':false,
'check':''},
{
'name' : 'MEDICATION_NAME',
'displayName' : '院内药品名称',
'type' : 'varchar(40)',
'javaName' : 'medicationName',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'MEDICAL_INSURANCE',
'displayName' : '医保系统药物编码',
'type' : 'varchar(100)',
'javaName' : 'medicalInsurance',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEDICAL_INSURANCE_NAME',
'displayName' : '医保系统药物名称',
'type' : 'varchar(40)',
'javaName' : 'medicalInsuranceName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AGRICULTURAL',
'displayName' : '农合系统药物编码',
'type' : 'varchar(100)',
'javaName' : 'agricultural',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AGRICULTURAL_NAME',
'displayName' : '农合系统药物名称',
'type' : 'varchar(40)',
'javaName' : 'agriculturalName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'STANDARD_CD',
'displayName' : '国药准字系统药物编码',
'type' : 'varchar(40)',
'javaName' : 'standardCd',
'note' : '药品在市平台中的标准编码',
'nullable':true,
'check':'CV990110'},
{
'name' : 'STANDARD_NAME',
'displayName' : '国药准字系统药物名称',
'type' : 'varchar(100)',
'javaName' : 'standardName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ISBRAND',
'displayName' : '是否是品牌药物',
'type' : 'number(5)',
'javaName' : 'isbrand',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'MANUFACTURER',
'displayName' : '药品生产商名字',
'type' : 'varchar(100)',
'javaName' : 'manufacturer',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRUG_DOSAGE_FORMS',
'displayName' : '药物剂型代码',
'type' : 'varchar(20)',
'javaName' : 'drugDosageForms',
'note' : '',
'nullable':true,
'check':'CV0850002'},
{
'name' : 'DRUG_DOSAGE_NAME',
'displayName' : '药物剂型名称',
'type' : 'varchar(50)',
'javaName' : 'drugDosageName',
'note' : '',
'nullable':true,
'check':'CV0850002'},
{
'name' : 'LOTNUMBER',
'displayName' : '生产批次号',
'type' : 'varchar(40)',
'javaName' : 'lotnumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EXPIRATIONDATE',
'displayName' : '过期时间',
'type' : 'date',
'javaName' : 'expirationdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'MEDICATION_PACKAGE_FORM_CODES',
'displayName' : '包装类型',
'type' : 'varchar(20)',
'javaName' : 'medicationPackageFormCodes',
'note' : '',
'nullable':true,
'check':'CV9900363'},
{
'name' : 'IS_OTC',
'displayName' : '是否OTC',
'type' : 'number(5)',
'javaName' : 'isOtc',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ALIAS_NAME',
'displayName' : '商品名',
'type' : 'varchar(40)',
'javaName' : 'aliasName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SPEC',
'displayName' : '规格',
'type' : 'varchar(40)',
'javaName' : 'spec',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ROUTE_UNIT',
'displayName' : '大包装单位',
'type' : 'varchar(40)',
'javaName' : 'routeUnit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LEAST_UNIT',
'displayName' : '小包装单位',
'type' : 'varchar(40)',
'javaName' : 'leastUnit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PROPORTION',
'displayName' : '大、小包装换算',
'type' : 'number(8)',
'javaName' : 'proportion',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CLI_UNIT_CHECK',
'displayName' : '门诊使用单位',
'type' : 'varchar(10)',
'javaName' : 'cliUnitCheck',
'note' : '',
'nullable':true,
'check':'CV9900268'},
{
'name' : 'INH_UNIT_CHECK',
'displayName' : '住院使用单位',
'type' : 'varchar(10)',
'javaName' : 'inhUnitCheck',
'note' : '',
'nullable':true,
'check':'CV9900268'},
{
'name' : 'IF_BASIC',
'displayName' : '是否基础药',
'type' : 'number(5)',
'javaName' : 'ifBasic',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'IF_IMPORT',
'displayName' : '是否进口药',
'type' : 'number(5)',
'javaName' : 'ifImport',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'IF_POISON',
'displayName' : '是否毒、麻类药物',
'type' : 'number(5)',
'javaName' : 'ifPoison',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'IF_PSYCHOTROPIC',
'displayName' : '是否精神类药物',
'type' : 'number(5)',
'javaName' : 'ifPsychotropic',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'IF_PRECIOUS',
'displayName' : '是否贵重药品',
'type' : 'number(5)',
'javaName' : 'ifPrecious',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'IF_ANTIBIOTIC',
'displayName' : '是否抗菌药物标志',
'type' : 'number(5)',
'javaName' : 'ifAntibiotic',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ANTIBIOTIC_TYPE',
'displayName' : '抗菌药等级',
'type' : 'varchar(20)',
'javaName' : 'antibioticType',
'note' : '',
'nullable':true,
'check':'CV9900275'},
{
'name' : 'MEDICATION_TYPE_CODE',
'displayName' : '药品类别代码',
'type' : 'varchar(20)',
'javaName' : 'medicationTypeCode',
'note' : '',
'nullable':true,
'check':'CV9900044'},
{
'name' : 'CN_MEDICATION_TYPE_CODE',
'displayName' : '中药类别代码',
'type' : 'varchar(20)',
'javaName' : 'cnMedicationTypeCode',
'note' : '',
'nullable':true,
'check':'CV0600101'},
{
'name' : 'DRUG_TYPE_CODE',
'displayName' : '药物类型代码',
'type' : 'varchar(20)',
'javaName' : 'drugTypeCode',
'note' : '',
'nullable':true,
'check':'CV0530106'},
{
'name' : 'DDD_VALUE',
'displayName' : 'DDD值/最小剂量',
'type' : 'number(8)',
'javaName' : 'dddValue',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRUG_ADVERSE_REACTION',
'displayName' : '药物不良反应情况',
'type' : 'varchar(200)',
'javaName' : 'drugAdverseReaction',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEDICATION_CATEGORY',
'displayName' : '医保报销标志',
'type' : 'varchar(20)',
'javaName' : 'medicationCategory',
'note' : '',
'nullable':true,
'check':'CV9900286'},
{
'name' : 'NCMS_MEDICATION_CATEGORY',
'displayName' : '农合报销标志',
'type' : 'varchar(20)',
'javaName' : 'ncmsMedicationCategory',
'note' : '',
'nullable':true,
'check':'CV9900373'}
];