var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'VITAL_SIGNS_MEASUREMENT_RECORD_ID',
'displayName' : '院内生命体征测量记录id',
'type' : 'varchar(40)',
'javaName' : 'vitalSignsMeasurementRecordId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CN_FOUR_RESULT',
'displayName' : '中医&quot;四诊&quot;观察结果',
'type' : 'varchar(200)',
'javaName' : 'cnFourResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IN_MODE_CODE',
'displayName' : '入院途径',
'type' : 'varchar(20)',
'javaName' : 'inModeCode',
'note' : '',
'nullable':true,
'check':'CV0900403'},
{
'name' : 'INHOSPITAL_REASON_CD',
'displayName' : '住院原因代码',
'type' : 'varchar(20)',
'javaName' : 'inhospitalReasonCd',
'note' : '',
'nullable':true,
'check':'CV0600212'},
{
'name' : 'INHOSPITAL_WAY',
'displayName' : '入病房方式',
'type' : 'varchar(40)',
'javaName' : 'inhospitalWay',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ACTUAL_HOSPITALIZATION_DAYS',
'displayName' : '实际住院天数',
'type' : 'number(8)',
'javaName' : 'actualHospitalizationDays',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESPONSIBILITY_NURSE_ID',
'displayName' : '责任护士id',
'type' : 'varchar(40)',
'javaName' : 'responsibilityNurseId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESPONSIBILITY_NURSE_NAME',
'displayName' : '责任护士姓名',
'type' : 'varchar(40)',
'javaName' : 'responsibilityNurseName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESPONSIBILITY_NURSE_DATE',
'displayName' : '责任护士签名日期',
'type' : 'date',
'javaName' : 'responsibilityNurseDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CN_SYM_DIAG_CODE',
'displayName' : '中医症候代码',
'type' : 'varchar(20)',
'javaName' : 'cnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'CN_DIS_DIAG_CODE',
'displayName' : '中医病名代码',
'type' : 'varchar(20)',
'javaName' : 'cnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'DIAG_CODE',
'displayName' : '诊断编码',
'type' : 'varchar(20)',
'javaName' : 'diagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'DIAG_NAME',
'displayName' : '诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'diagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIAG_DATE',
'displayName' : '诊断日期',
'type' : 'date',
'javaName' : 'diagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'POSTOPERATIVE_DAYS',
'displayName' : '手术或分娩后天数',
'type' : 'number(8)',
'javaName' : 'postoperativeDays',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CASE_NO',
'displayName' : '病案号',
'type' : 'varchar(40)',
'javaName' : 'caseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_TIMES',
'displayName' : '住院次数',
'type' : 'number(4)',
'javaName' : 'inpatTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PULSES',
'displayName' : '脉率（次/min）',
'type' : 'number(8)',
'javaName' : 'pulses',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BREATHING_RATE',
'displayName' : '呼吸频率（次/min）',
'type' : 'number(8)',
'javaName' : 'breathingRate',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PACEMAKER',
'displayName' : '起搏器心率（次/min）',
'type' : 'number(8)',
'javaName' : 'pacemaker',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BODY_TEMPERATURE',
'displayName' : '体温（℃）',
'type' : 'number(8)',
'javaName' : 'bodyTemperature',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SBP',
'displayName' : '收缩压（mmHg）',
'type' : 'number(8)',
'javaName' : 'sbp',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DBP',
'displayName' : '舒张压（mmHg）',
'type' : 'number(8)',
'javaName' : 'dbp',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ABDOMINAL_GIRTH',
'displayName' : '腹围（cm）',
'type' : 'number(8)',
'javaName' : 'abdominalGirth',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WEIGHT',
'displayName' : '体重',
'type' : 'number(8)',
'javaName' : 'weight',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'USE_VENTILATOR_SIGNS',
'displayName' : '使用呼吸机标志',
'type' : 'number(5)',
'javaName' : 'useVentilatorSigns',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'OBSERVATION_PROJECT_NAME',
'displayName' : '护理观察项目名称',
'type' : 'varchar(40)',
'javaName' : 'observationProjectName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OBSERVATION_RESULTS_DESCRIPTION',
'displayName' : '护理观察结果',
'type' : 'varchar(200)',
'javaName' : 'observationResultsDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];