var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'ADMISSIONAND_DEATH_RECORD_ID',
'displayName' : '院内24h内入院死亡记录id',
'type' : 'varchar(40)',
'javaName' : 'admissionandDeathRecordId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NATION_CD',
'displayName' : '民族代码',
'type' : 'varchar(20)',
'javaName' : 'nationCd',
'note' : '',
'nullable':true,
'check':'CV9900377'},
{
'name' : 'OCCUPATION_CD',
'displayName' : '职业代码',
'type' : 'varchar(20)',
'javaName' : 'occupationCd',
'note' : '',
'nullable':true,
'check':'GBT22614'},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_STATE',
'displayName' : '家庭住址-省（自治区、直辖市）代码',
'type' : 'varchar(10)',
'javaName' : 'homeState',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_CITY',
'displayName' : '家庭住址-市（地区）代码',
'type' : 'varchar(10)',
'javaName' : 'homeCity',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_DISTRICT',
'displayName' : '家庭住址-县（区）代码',
'type' : 'varchar(10)',
'javaName' : 'homeDistrict',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_LINE',
'displayName' : '家庭住址-乡（镇、街道办事处）',
'type' : 'varchar(100)',
'javaName' : 'homeLine',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_ROAD',
'displayName' : '家庭住址-村（街、路、弄等）',
'type' : 'varchar(100)',
'javaName' : 'homeRoad',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_HOUSE_NO',
'displayName' : '家庭住址-门牌号码',
'type' : 'varchar(50)',
'javaName' : 'homeHouseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_TEXT',
'displayName' : '家庭住址-详细信息',
'type' : 'varchar(500)',
'javaName' : 'homeText',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MARITALSTATUS',
'displayName' : '婚姻状况代码',
'type' : 'varchar(20)',
'javaName' : 'maritalstatus',
'note' : '',
'nullable':false,
'check':'GBT22612'},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CN_FOUR_RESULT',
'displayName' : '中医&quot;四诊&quot;观察结果',
'type' : 'varchar(200)',
'javaName' : 'cnFourResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RECEIVE_EMPLOYEE_ID',
'displayName' : '接诊医生id',
'type' : 'varchar(40)',
'javaName' : 'receiveEmployeeId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RECEIVE_EMPLOYEE_NAME',
'displayName' : '接诊医生姓名',
'type' : 'varchar(40)',
'javaName' : 'receiveEmployeeName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RECEIVE_EMPLOYEE_POST_CD',
'displayName' : '接诊医生专业技术职务代码',
'type' : 'varchar(20)',
'javaName' : 'receiveEmployeePostCd',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'CASE_NO',
'displayName' : '病案号',
'type' : 'varchar(20)',
'javaName' : 'caseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_TIMES',
'displayName' : '住院次数',
'type' : 'number(8)',
'javaName' : 'inpatTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REMARKS',
'displayName' : '备注',
'type' : 'text',
'javaName' : 'remarks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUDITOR_ID',
'displayName' : '最终审核者者id',
'type' : 'varchar(40)',
'javaName' : 'auditorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUDITOR_NAME',
'displayName' : '最终审核者姓名',
'type' : 'varchar(40)',
'javaName' : 'auditorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUDITOR_DATE',
'displayName' : '最终审核者签名日期',
'type' : 'date',
'javaName' : 'auditorDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AUDITOR_POST',
'displayName' : '最终审核者专业技术职务代码',
'type' : 'varchar(20)',
'javaName' : 'auditorPost',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'RESIDENT_DOCTOR_ID',
'displayName' : '住院医师id',
'type' : 'varchar(40)',
'javaName' : 'residentDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESIDENT_DOCTOR_NAME',
'displayName' : '住院医师姓名',
'type' : 'varchar(20)',
'javaName' : 'residentDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESIDENT_DOCTOR_SIGN_DATE',
'displayName' : '住院医师签名日期',
'type' : 'date',
'javaName' : 'residentDoctorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ATTENDING_DOCTOR_ID',
'displayName' : '主治医师id',
'type' : 'varchar(40)',
'javaName' : 'attendingDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ATTENDING_DOCTOR_NAME',
'displayName' : '主治医师姓名',
'type' : 'varchar(20)',
'javaName' : 'attendingDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ATTENDING_DOCTOR_SIGN_DATE',
'displayName' : '主治医师签名日期',
'type' : 'date',
'javaName' : 'attendingDoctorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CHIEF_PHYSICIAN_ID',
'displayName' : '主(副主)任医师id',
'type' : 'varchar(40)',
'javaName' : 'chiefPhysicianId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CHIEF_PHYSICIAN_NAME',
'displayName' : '主(副主)任医师姓名',
'type' : 'varchar(20)',
'javaName' : 'chiefPhysicianName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CHIEF_PHYSICIAN_SIGN_DATE',
'displayName' : '主(副主)任医师签名日期',
'type' : 'date',
'javaName' : 'chiefPhysicianSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CHIEF',
'displayName' : '主诉',
'type' : 'text',
'javaName' : 'chief',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'STATEMENTS_RELIABILITY',
'displayName' : '陈述内容可靠标志',
'type' : 'number(5)',
'javaName' : 'statementsReliability',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'INHOS_DIAG_ID',
'displayName' : '入院诊断-记录id',
'type' : 'varchar(40)',
'javaName' : 'inhosDiagId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INHOS_CN_SYM_DIAG_CODE',
'displayName' : '入院诊断-中医症候代码',
'type' : 'varchar(20)',
'javaName' : 'inhosCnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'INHOS_CN_DIS_DIAG_CODE',
'displayName' : '入院诊断-中医病名代码',
'type' : 'varchar(20)',
'javaName' : 'inhosCnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'INHOS_DIAG_CODE',
'displayName' : '入院诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'inhosDiagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'INHOS_DIAG_NAME',
'displayName' : '入院诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'inhosDiagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INHOS_DIAG_DATE',
'displayName' : '入院诊断-诊断日期',
'type' : 'date',
'javaName' : 'inhosDiagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'THERAPEUTIC_PRINCIPLES',
'displayName' : '治则治法代码',
'type' : 'varchar(10)',
'javaName' : 'therapeuticPrinciples',
'note' : '根据辨证结果采用的治则治法名称术语',
'nullable':true,
'check':'GBT167513'},
{
'name' : 'DEATH_DIAG_ID',
'displayName' : '死亡诊断-记录id',
'type' : 'varchar(40)',
'javaName' : 'deathDiagId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_DETAILS',
'displayName' : '入院情况',
'type' : 'varchar(200)',
'javaName' : 'inpatientDetails',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TREAT_RESCUE_COURSE',
'displayName' : '诊疗过程描述',
'type' : 'varchar(500)',
'javaName' : 'treatRescueCourse',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DEATH_TIME',
'displayName' : '死亡日期时间',
'type' : 'date',
'javaName' : 'deathTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DEATH_REASON_NAME',
'displayName' : '直接死亡原因名称',
'type' : 'varchar(40)',
'javaName' : 'deathReasonName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DEATH_CN_SYM_DIAG_CODE',
'displayName' : '死亡诊断-中医症候代码',
'type' : 'varchar(20)',
'javaName' : 'deathCnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'DEATH_CN_DIS_DIAG_CODE',
'displayName' : '死亡诊断-中医病名代码',
'type' : 'varchar(20)',
'javaName' : 'deathCnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'DEATH_DIAG_CODE',
'displayName' : '死亡诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'deathDiagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'DEATH_DIAG_NAME',
'displayName' : '死亡诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'deathDiagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DEATH_DIAG_DATE',
'displayName' : '死亡诊断-诊断日期',
'type' : 'date',
'javaName' : 'deathDiagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];