var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'NEONATAL_FAMILY_VISIT_ID',
'displayName' : '新生儿家庭访视id',
'type' : 'varchar(40)',
'javaName' : 'neonatalFamilyVisitId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'HOME_STATE',
'displayName' : '家庭住址-省（自治区、直辖市）代码',
'type' : 'varchar(10)',
'javaName' : 'homeState',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_CITY',
'displayName' : '家庭住址-市（地区）代码',
'type' : 'varchar(10)',
'javaName' : 'homeCity',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_DISTRICT',
'displayName' : '家庭住址-县（区）代码',
'type' : 'varchar(10)',
'javaName' : 'homeDistrict',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_LINE',
'displayName' : '家庭住址-乡（镇、街道办事处）',
'type' : 'varchar(100)',
'javaName' : 'homeLine',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_ROAD',
'displayName' : '家庭住址-村（街、路、弄等）',
'type' : 'varchar(100)',
'javaName' : 'homeRoad',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_HOUSE_NO',
'displayName' : '家庭住址-门牌号码',
'type' : 'varchar(50)',
'javaName' : 'homeHouseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_TEXT',
'displayName' : '家庭住址-详细信息',
'type' : 'varchar(500)',
'javaName' : 'homeText',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FATHER_NAME',
'displayName' : '父亲姓名',
'type' : 'varchar(20)',
'javaName' : 'fatherName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FATHER_OCCUPATION_CD',
'displayName' : '父亲-职业代码',
'type' : 'varchar(20)',
'javaName' : 'fatherOccupationCd',
'note' : '',
'nullable':true,
'check':'GBT22614'},
{
'name' : 'MOTHER_NAME',
'displayName' : '母亲姓名',
'type' : 'varchar(20)',
'javaName' : 'motherName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MOTHER_OCCUPATION_CD',
'displayName' : '母亲-职业代码',
'type' : 'varchar(20)',
'javaName' : 'motherOccupationCd',
'note' : '',
'nullable':true,
'check':'GBT22614'},
{
'name' : 'GESTATIONAL_WEEK',
'displayName' : '出生孕周',
'type' : 'number(8)',
'javaName' : 'gestationalWeek',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MIDWIFERY_ORGANIZATION_NAME',
'displayName' : '助产机构名称',
'type' : 'varchar(40)',
'javaName' : 'midwiferyOrganizationName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MATERNAL_PREGNANCY_COMPLICATIONS',
'displayName' : '母亲妊娠合并症',
'type' : 'varchar(40)',
'javaName' : 'maternalPregnancyComplications',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MODE_DELIVERY',
'displayName' : '分娩方式',
'type' : 'varchar(20)',
'javaName' : 'modeDelivery',
'note' : '',
'nullable':true,
'check':'CV0210003'},
{
'name' : 'ASPHYXIA_NEWBORN_MARK',
'displayName' : '新生儿窒息标志',
'type' : 'number(5)',
'javaName' : 'asphyxiaNewbornMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'APGAR_SCORE',
'displayName' : 'Apgar评分值',
'type' : 'number(8)',
'javaName' : 'apgarScore',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FEEDING_MODE',
'displayName' : '喂养方式',
'type' : 'varchar(20)',
'javaName' : 'feedingMode',
'note' : '',
'nullable':true,
'check':'CV9900005'},
{
'name' : 'AT_TIMES_DAY',
'displayName' : '每天吃奶次数',
'type' : 'number(8)',
'javaName' : 'atTimesDay',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DAILY_FEEDING_AMOUNT',
'displayName' : '每天吃奶量(ml)',
'type' : 'number(8)',
'javaName' : 'dailyFeedingAmount',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VOMITING_MARK',
'displayName' : '呕吐标志',
'type' : 'number(5)',
'javaName' : 'vomitingMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'CHILDREN_STOOL_CHARACTER_CODE',
'displayName' : '新生儿大便性状代码',
'type' : 'varchar(20)',
'javaName' : 'childrenStoolCharacterCode',
'note' : '',
'nullable':true,
'check':'CV0401012'},
{
'name' : 'STOOL_FREQUENCY',
'displayName' : '大便次数',
'type' : 'number(8)',
'javaName' : 'stoolFrequency',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EAR_APPEARANCE_ABNORMAL_SIGN',
'displayName' : '耳外观检查异常标志',
'type' : 'number(5)',
'javaName' : 'earAppearanceAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'EAR_APPEARANCE_RESULT',
'displayName' : '耳外观检查异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'earAppearanceResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NEONATAL_DISEASE_SCREENING_CODE',
'displayName' : '新生儿疾病筛查代码',
'type' : 'varchar(20)',
'javaName' : 'neonatalDiseaseScreeningCode',
'note' : '',
'nullable':true,
'check':'CV0450008'},
{
'name' : 'BODY_TEMPERATURE',
'displayName' : '体温（℃）',
'type' : 'number(8)',
'javaName' : 'bodyTemperature',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PULSES',
'displayName' : '脉率（次/min）',
'type' : 'number(8)',
'javaName' : 'pulses',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BREATHING_RATE',
'displayName' : '呼吸频率（次/min）',
'type' : 'number(8)',
'javaName' : 'breathingRate',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_LENGTH',
'displayName' : '身长（cm）',
'type' : 'number(8)',
'javaName' : 'birthLength',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_WEIGHT',
'displayName' : '体重（g）',
'type' : 'number(8)',
'javaName' : 'birthWeight',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NEWBORN_BIRTH_WEIGHT',
'displayName' : '新生儿出生体重（g）',
'type' : 'number(8)',
'javaName' : 'newbornBirthWeight',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NEWBORN_BIRTH_LENGTH',
'displayName' : '出生身长（cm）',
'type' : 'number(8)',
'javaName' : 'newbornBirthLength',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SKIN_TEST_RESULT_CODE',
'displayName' : '皮肤检查结果代码',
'type' : 'varchar(20)',
'javaName' : 'skinTestResultCode',
'note' : '',
'nullable':true,
'check':'CV0410004'},
{
'name' : 'AUNDICE_SITE_CODE',
'displayName' : '黄疸部位代码',
'type' : 'varchar(20)',
'javaName' : 'aundiceSiteCode',
'note' : '',
'nullable':true,
'check':'CV0410009'},
{
'name' : 'FACE_CODE',
'displayName' : '新生儿面色代码',
'type' : 'varchar(20)',
'javaName' : 'faceCode',
'note' : '',
'nullable':true,
'check':'CV0410008'},
{
'name' : 'NEONATAL_MALFORMATION',
'displayName' : '新生儿畸形标志',
'type' : 'number(5)',
'javaName' : 'neonatalMalformation',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'NEONATAL_MALFORMATION_DESCRIPTION',
'displayName' : '新生儿畸形描述',
'type' : 'varchar(40)',
'javaName' : 'neonatalMalformationDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANTERIOR_FONTANELLE_CLOSED_SIGN',
'displayName' : '前囟闭合标志',
'type' : 'number(5)',
'javaName' : 'anteriorFontanelleClosedSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'TRANSVERSE_DIAMETER_ANTERIOR_FONTANEL',
'displayName' : '前囟横径',
'type' : 'number(8)',
'javaName' : 'transverseDiameterAnteriorFontanel',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANTERIOR_LONGITUDINAL_DIAMETER',
'displayName' : '前囟纵径',
'type' : 'number(8)',
'javaName' : 'anteriorLongitudinalDiameter',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANTERIOR_FONTANEL_TENSION_CODE',
'displayName' : '前囟张力代码',
'type' : 'varchar(20)',
'javaName' : 'anteriorFontanelTensionCode',
'note' : '',
'nullable':true,
'check':'CV0410018'},
{
'name' : 'FAR_VISUAL_ACUITY',
'displayName' : '左眼裸眼远视力值',
'type' : 'number(8)',
'javaName' : 'farVisualAcuity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LEFT_CORRECTED_VISUAL_ACUITY',
'displayName' : '左眼矫正远视力值',
'type' : 'number(8)',
'javaName' : 'leftCorrectedVisualAcuity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RIGHT_CORRECTED_VISUAL_ACUITY',
'displayName' : '右眼矫正远视力值',
'type' : 'number(8)',
'javaName' : 'rightCorrectedVisualAcuity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EYE_APPEARANCE_CHECK',
'displayName' : '眼外观检查异常标志',
'type' : 'number(5)',
'javaName' : 'eyeAppearanceCheck',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'EYE_APPEARANCE_INSPECTION_RESULTS',
'displayName' : '眼外观检查异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'eyeAppearanceInspectionResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LIMB_ACTIVITY_ABNORMAL_SIGN',
'displayName' : '四肢活动度异常标志',
'type' : 'number(5)',
'javaName' : 'limbActivityAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'LIMB_MOBILITY_ABNORMAL_RESULTS',
'displayName' : '四肢活动度异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'limbMobilityAbnormalResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NECK_MASS',
'displayName' : '颈部包块标志',
'type' : 'number(5)',
'javaName' : 'neckMass',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'CERVICAL_MASS_EXAMINATION_RESULTS',
'displayName' : '颈部包块检查结果描述',
'type' : 'varchar(40)',
'javaName' : 'cervicalMassExaminationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NASAL_EXAMINATION_ABNORMAL_SIGNS',
'displayName' : '鼻检查异常标志',
'type' : 'number(5)',
'javaName' : 'nasalExaminationAbnormalSigns',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'NASAL_EXAMINATION_RESULTS',
'displayName' : '鼻检查异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'nasalExaminationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ORAL_EXAMINATION_ABNORMAL_SIGN',
'displayName' : '口腔检查异常标志',
'type' : 'number(5)',
'javaName' : 'oralExaminationAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ORAL_EXAMINATION_RESULTS',
'displayName' : '口腔检查异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'oralExaminationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANUS_ABNORMAL_SIGN',
'displayName' : '肛门检查异常标志',
'type' : 'number(5)',
'javaName' : 'anusAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ANUS_EXAMINATION_RESULTS',
'displayName' : '肛门检查异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'anusExaminationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CARDIAC_AUSCULTATION_ABNORMAL_SIGN',
'displayName' : '心脏听诊异常标志',
'type' : 'number(5)',
'javaName' : 'cardiacAuscultationAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'CARDIAC_AUSCULTATION_RESULTS',
'displayName' : '心脏听诊异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'cardiacAuscultationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LUNG_AUSCULTATION_ABNORMAL_SIGN',
'displayName' : '肺部听诊异常标志',
'type' : 'number(5)',
'javaName' : 'lungAuscultationAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'LUNG_AUSCULTATION_RESULTS',
'displayName' : '肺部听诊异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'lungAuscultationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EXTERNAL_GENITAL_ORGANS_ABNORMAL_SIGN',
'displayName' : '外生殖器检查异常标志',
'type' : 'number(5)',
'javaName' : 'externalGenitalOrgansAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'EXTERNAL_GENITAL_ORGANS_RESULTS',
'displayName' : '外生殖器检查异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'externalGenitalOrgansResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ABDOMINAL_PALPATION_ABNORMAL_SIGN',
'displayName' : '腹部触诊异常标志',
'type' : 'number(5)',
'javaName' : 'abdominalPalpationAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ABDOMINAL_PALPATION_RESULTS',
'displayName' : '腹部触诊异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'abdominalPalpationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UMBILICAL_CORD',
'displayName' : '脐带脱落标志',
'type' : 'number(5)',
'javaName' : 'umbilicalCord',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'UMBILICAL_CORD_EXAMINATION_RESULTS_CODE',
'displayName' : '脐带检查结果代码',
'type' : 'varchar(20)',
'javaName' : 'umbilicalCordExaminationResultsCode',
'note' : '',
'nullable':true,
'check':'CV0410019'},
{
'name' : 'SPINAL_EXAMINATION_ABNORMAL_SIGN',
'displayName' : '脊柱检查异常标志',
'type' : 'number(5)',
'javaName' : 'spinalExaminationAbnormalSign',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'SPINAL_EXAMINATION_RESULTS',
'displayName' : '脊柱检查异常结果描述',
'type' : 'varchar(40)',
'javaName' : 'spinalExaminationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_INSTRUCTION_CODE',
'displayName' : '健康指导代码',
'type' : 'varchar(20)',
'javaName' : 'healthInstructionCode',
'note' : '',
'nullable':true,
'check':'CV9900017'},
{
'name' : 'REFERRAL_MARK',
'displayName' : '转诊标志',
'type' : 'number(5)',
'javaName' : 'referralMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'REFERRAL_REASONS',
'displayName' : '转诊原因',
'type' : 'varchar(40)',
'javaName' : 'referralReasons',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REFERRAL_IN_ORG',
'displayName' : '转入机构的名称',
'type' : 'varchar(40)',
'javaName' : 'referralInOrg',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REFERRAL_IN_DEP',
'displayName' : '转入科室的名称',
'type' : 'varchar(40)',
'javaName' : 'referralInDep',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NEXT_FOLLOW_UP_DATE',
'displayName' : '下次随访日期',
'type' : 'date',
'javaName' : 'nextFollowUpDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'NEXT_VISIT_LOCATION',
'displayName' : '下次访视地点',
'type' : 'varchar(40)',
'javaName' : 'nextVisitLocation',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];