var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'TREATMENT_RECORD_ID',
'displayName' : '院内治疗记录id',
'type' : 'varchar(40)',
'javaName' : 'treatmentRecordId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'TELECOM',
'displayName' : '电话号码',
'type' : 'varchar(20)',
'javaName' : 'telecom',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_TYPE',
'displayName' : '患者类型',
'type' : 'varchar(20)',
'javaName' : 'patientType',
'note' : '',
'nullable':true,
'check':'CV0900404'},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISIT_MARK',
'displayName' : '门诊或住院标识',
'type' : 'varchar(10)',
'javaName' : 'visitMark',
'note' : '',
'nullable':false,
'check':'CUS00010'},
{
'name' : 'REGISTRATION_ID',
'displayName' : '就诊流水号',
'type' : 'varchar(40)',
'javaName' : 'registrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_TIME',
'displayName' : '就诊时间',
'type' : 'date',
'javaName' : 'visitingTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'VISITING_TYPE',
'displayName' : '就诊类型',
'type' : 'varchar(20)',
'javaName' : 'visitingType',
'note' : '',
'nullable':true,
'check':'CV9900340'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IF_INVASIVE_TREATMENT',
'displayName' : '有创诊疗操作标志',
'type' : 'number(5)',
'javaName' : 'ifInvasiveTreatment',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'IF_RRITABILITY',
'displayName' : '是否有过敏史',
'type' : 'number(5)',
'javaName' : 'ifRritability',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'RRITABILITY',
'displayName' : '过敏史其他描述',
'type' : 'text',
'javaName' : 'rritability',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WEIGHT',
'displayName' : '体重',
'type' : 'number(8)',
'javaName' : 'weight',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ADMISSION_DIAGNOSIS',
'displayName' : '入院诊断编码',
'type' : 'varchar(20)',
'javaName' : 'admissionDiagnosis',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'ADMISSION_DIAGNOSIS_NAME',
'displayName' : '入院诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'admissionDiagnosisName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ADMISSION_DIAGNOSIS_DATE',
'displayName' : '诊断日期',
'type' : 'date',
'javaName' : 'admissionDiagnosisDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'TREATMENT_GUIDANCE',
'displayName' : '处理及指导意见',
'type' : 'varchar(200)',
'javaName' : 'treatmentGuidance',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ORDERS_REMARKS',
'displayName' : '医嘱使用备注',
'type' : 'varchar(200)',
'javaName' : 'ordersRemarks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FUTURE_TREATMENT_OPTIONS',
'displayName' : '今后治疗方案',
'type' : 'varchar(500)',
'javaName' : 'futureTreatmentOptions',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISIT_WAY_CD',
'displayName' : '随访方式代码',
'type' : 'varchar(20)',
'javaName' : 'visitWayCd',
'note' : '',
'nullable':true,
'check':'CV0600207'},
{
'name' : 'FOLLOWUP_DATE',
'displayName' : '随访日期',
'type' : 'date',
'javaName' : 'followupDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'FOLLOWUP_PERIOD_CD',
'displayName' : '随访周期建议代码',
'type' : 'varchar(20)',
'javaName' : 'followupPeriodCd',
'note' : '',
'nullable':true,
'check':'CV0600208'},
{
'name' : 'INTERVENTION',
'displayName' : '介入物名称',
'type' : 'varchar(40)',
'javaName' : 'intervention',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_METHOD',
'displayName' : '操作方法',
'type' : 'varchar(40)',
'javaName' : 'operationMethod',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_TIMES',
'displayName' : '操作次数',
'type' : 'varchar(20)',
'javaName' : 'operationTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_CD',
'displayName' : '手术编码',
'type' : 'varchar(20)',
'javaName' : 'operationCd',
'note' : '',
'nullable':true,
'check':'CV990113'},
{
'name' : 'OPERATION_NAME',
'displayName' : '手术名称',
'type' : 'varchar(40)',
'javaName' : 'operationName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PART_CODE',
'displayName' : '手术操作目标部位代码',
'type' : 'varchar(20)',
'javaName' : 'partCode',
'note' : '',
'nullable':true,
'check':'CV0600227'},
{
'name' : 'PART_NAME',
'displayName' : '手术操作目标部位名称',
'type' : 'varchar(20)',
'javaName' : 'partName',
'note' : '',
'nullable':true,
'check':'CV0600227'},
{
'name' : 'DRUGS_USAGE',
'displayName' : '药物用法',
'type' : 'varchar(100)',
'javaName' : 'drugsUsage',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CN_MEDICATION_TYPE_CODE',
'displayName' : '中药使用类别代码',
'type' : 'varchar(20)',
'javaName' : 'cnMedicationTypeCode',
'note' : '',
'nullable':true,
'check':'CV0600101'},
{
'name' : 'FREQ_CODE',
'displayName' : '频率代码',
'type' : 'varchar(20)',
'javaName' : 'freqCode',
'note' : '',
'nullable':true,
'check':'CV9900341'},
{
'name' : 'DRUG_TOTAL_DOSE',
'displayName' : '药物使用总剂量',
'type' : 'number(8)',
'javaName' : 'drugTotalDose',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRUG_TOTAL_DOSE_UTIL',
'displayName' : '药物使用总剂量单位',
'type' : 'varchar(20)',
'javaName' : 'drugTotalDoseUtil',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PERFORMER_EMPID',
'displayName' : '执行医生id',
'type' : 'varchar(40)',
'javaName' : 'performerEmpid',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PERFORMER_EMP_NAME',
'displayName' : '执行医生姓名',
'type' : 'varchar(40)',
'javaName' : 'performerEmpName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PERFORM_TIME',
'displayName' : '执行时间',
'type' : 'date',
'javaName' : 'performTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DATEWRITTEN',
'displayName' : '开立时间',
'type' : 'date',
'javaName' : 'datewritten',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PRESCRIBER_ID',
'displayName' : '开立医生id',
'type' : 'varchar(40)',
'javaName' : 'prescriberId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PRESCRIBER_NAME',
'displayName' : '开立医生姓名',
'type' : 'varchar(40)',
'javaName' : 'prescriberName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ALIAS_NAME',
'displayName' : '商品名',
'type' : 'varchar(80)',
'javaName' : 'aliasName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SPEC',
'displayName' : '规格',
'type' : 'varchar(40)',
'javaName' : 'spec',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEDICATION_CD',
'displayName' : '院内药物编码',
'type' : 'varchar(20)',
'javaName' : 'medicationCd',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEDICATION_NAME',
'displayName' : '院内药物名称',
'type' : 'varchar(40)',
'javaName' : 'medicationName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRUG_DOSAGE_FORMS',
'displayName' : '药物剂型代码',
'type' : 'varchar(20)',
'javaName' : 'drugDosageForms',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRUG_DOSAGE_FORMS_NAME',
'displayName' : '药物剂型名称',
'type' : 'varchar(40)',
'javaName' : 'drugDosageFormsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOSAGE_CODE',
'displayName' : '用药途径代码',
'type' : 'varchar(20)',
'javaName' : 'dosageCode',
'note' : '',
'nullable':true,
'check':'CV0600102'},
{
'name' : 'ONCE_VALUE',
'displayName' : '用药次剂量',
'type' : 'number(8)',
'javaName' : 'onceValue',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ONCE_UNIT',
'displayName' : '用药次剂量单位',
'type' : 'varchar(20)',
'javaName' : 'onceUnit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];