var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'GENERAL_NURSING_RECORDS_ID',
'displayName' : '院内一般护理记录id',
'type' : 'varchar(40)',
'javaName' : 'generalNursingRecordsId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CASE_NO',
'displayName' : '病案号',
'type' : 'varchar(40)',
'javaName' : 'caseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_TIMES',
'displayName' : '住院次数',
'type' : 'number(3)',
'javaName' : 'inpatTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'TELECOM',
'displayName' : '电话号码',
'type' : 'varchar(20)',
'javaName' : 'telecom',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CN_FOUR_RESULT',
'displayName' : '中医&quot;四诊&quot;观察结果',
'type' : 'varchar(200)',
'javaName' : 'cnFourResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IN_MODE_CODE',
'displayName' : '入院途径',
'type' : 'varchar(20)',
'javaName' : 'inModeCode',
'note' : '',
'nullable':true,
'check':'CV0900403'},
{
'name' : 'INHOSPITAL_REASON_CD',
'displayName' : '住院原因代码',
'type' : 'varchar(20)',
'javaName' : 'inhospitalReasonCd',
'note' : '',
'nullable':true,
'check':'CV0600212'},
{
'name' : 'INHOSPITAL_WAY',
'displayName' : '入病房方式',
'type' : 'varchar(40)',
'javaName' : 'inhospitalWay',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RRITABILITY',
'displayName' : '过敏史描述',
'type' : 'varchar(40)',
'javaName' : 'rritability',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IF_RRITABILITY',
'displayName' : '是否有过敏史',
'type' : 'number(5)',
'javaName' : 'ifRritability',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'BODY_TEMPERATURE',
'displayName' : '体温（℃）',
'type' : 'number(8)',
'javaName' : 'bodyTemperature',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PULSES',
'displayName' : '脉率（次/min）',
'type' : 'number(8)',
'javaName' : 'pulses',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BREATHING_RATE',
'displayName' : '呼吸频率（次/min）',
'type' : 'number(8)',
'javaName' : 'breathingRate',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WEIGHT',
'displayName' : '体重(kg)',
'type' : 'number(8)',
'javaName' : 'weight',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SBP',
'displayName' : '收缩压（mmHg）',
'type' : 'number(8)',
'javaName' : 'sbp',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DBP',
'displayName' : '舒张压（mmHg）',
'type' : 'number(8)',
'javaName' : 'dbp',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'GLU',
'displayName' : '血糖检测值（mmol/L）',
'type' : 'number(8)',
'javaName' : 'glu',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SAO2',
'displayName' : '血氧饱和度（%）',
'type' : 'number(8)',
'javaName' : 'sao2',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DORSALIS_PEDIS_ARTERY_PULSE',
'displayName' : '足背动脉搏动标志',
'type' : 'number(5)',
'javaName' : 'dorsalisPedisArteryPulse',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'DIETARY_STATUS',
'displayName' : '饮食情况代码',
'type' : 'varchar(20)',
'javaName' : 'dietaryStatus',
'note' : '',
'nullable':true,
'check':'CV9900003'},
{
'name' : 'DIET_GUIDE',
'displayName' : '饮食指导代码',
'type' : 'varchar(20)',
'javaName' : 'dietGuide',
'note' : '',
'nullable':true,
'check':'CV9900333'},
{
'name' : 'NURSING_TYPE',
'displayName' : '护理等级代码',
'type' : 'varchar(20)',
'javaName' : 'nursingType',
'note' : '',
'nullable':true,
'check':'CV9900330'},
{
'name' : 'NURSING_GRADE',
'displayName' : '护理类型代码表',
'type' : 'varchar(20)',
'javaName' : 'nursingGrade',
'note' : '',
'nullable':true,
'check':'CV9900331'},
{
'name' : 'CATHETER_CARE_DESCRIPTION',
'displayName' : '导管护理',
'type' : 'varchar(200)',
'javaName' : 'catheterCareDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'POSITION_NURSE_DESCRIPTION',
'displayName' : '体位护理',
'type' : 'varchar(200)',
'javaName' : 'positionNurseDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SKIN_NURSE_DESCRIPTION',
'displayName' : '皮肤护理',
'type' : 'varchar(200)',
'javaName' : 'skinNurseDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NUTRITION_CARE_DESCRIPTION',
'displayName' : '营养护理',
'type' : 'varchar(200)',
'javaName' : 'nutritionCareDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRACHEA_NURSE_DESCRIPTION',
'displayName' : '气管护理代码',
'type' : 'varchar(20)',
'javaName' : 'tracheaNurseDescription',
'note' : '',
'nullable':true,
'check':'CV9900332'},
{
'name' : 'SECURITY_NURSE_DESCRIPTION',
'displayName' : '安全护理代码表',
'type' : 'varchar(20)',
'javaName' : 'securityNurseDescription',
'note' : '',
'nullable':true,
'check':'CV9900335'},
{
'name' : 'PSYCHOLOGICAL_NURSING',
'displayName' : '心理护理代码',
'type' : 'varchar(20)',
'javaName' : 'psychologicalNursing',
'note' : '',
'nullable':true,
'check':'CV9900334'},
{
'name' : 'BRIEF_ILLNESS_DESCRIPTION',
'displayName' : '简要病情',
'type' : 'varchar(200)',
'javaName' : 'briefIllnessDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OBSERVATION_PROJECT_NAME',
'displayName' : '护理观察项目名称',
'type' : 'varchar(200)',
'javaName' : 'observationProjectName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OBSERVATION_RESULTS_DESCRIPTION',
'displayName' : '护理观察结果',
'type' : 'varchar(200)',
'javaName' : 'observationResultsDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NURSING_NAME',
'displayName' : '护理操作名称',
'type' : 'varchar(40)',
'javaName' : 'nursingName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NURSING_ITEM_NAME',
'displayName' : '护理操作项目类目名称',
'type' : 'varchar(40)',
'javaName' : 'nursingItemName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NURSING_RESULT_DESCRIPTION',
'displayName' : '护理操作结果描述',
'type' : 'varchar(200)',
'javaName' : 'nursingResultDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BREATHING_MACHINE_MONITORING_DESCRIPTION',
'displayName' : '呼吸机监护项目',
'type' : 'varchar(40)',
'javaName' : 'breathingMachineMonitoringDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SURGICAL_SAFETY_CHECKLIST',
'displayName' : '发出手术安全核对表标志',
'type' : 'number(5)',
'javaName' : 'surgicalSafetyChecklist',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'RECOVER_SURGICAL_SAFETY_CHECKLIST',
'displayName' : '收回手术安全核对表标志',
'type' : 'number(5)',
'javaName' : 'recoverSurgicalSafetyChecklist',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'OPERATION_RISK_ASSESSMENT',
'displayName' : '发出手术风险评估表标志',
'type' : 'number(5)',
'javaName' : 'operationRiskAssessment',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'RECOVERY_OPERATION_RISK_ASSESSMENT',
'displayName' : '收回手术风险评估表标志',
'type' : 'number(5)',
'javaName' : 'recoveryOperationRiskAssessment',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ISOLATED_SIGNS',
'displayName' : '隔离标志',
'type' : 'number(5)',
'javaName' : 'isolatedSigns',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ISOLATION_TYPE',
'displayName' : '隔离种类代码',
'type' : 'varchar(20)',
'javaName' : 'isolationType',
'note' : '',
'nullable':true,
'check':'CV9900336'},
{
'name' : 'CN_SYM_DIAG_CODE',
'displayName' : '中医症候代码',
'type' : 'varchar(20)',
'javaName' : 'cnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'CN_DIS_DIAG_CODE',
'displayName' : '中医病名代码',
'type' : 'varchar(20)',
'javaName' : 'cnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'DIAG_CODE',
'displayName' : '诊断编码',
'type' : 'varchar(20)',
'javaName' : 'diagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'DIAG_NAME',
'displayName' : '诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'diagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIAG_DATE',
'displayName' : '诊断日期',
'type' : 'date',
'javaName' : 'diagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RESPONSIBILITY_NURSE_ID',
'displayName' : '责任护士id',
'type' : 'varchar(40)',
'javaName' : 'responsibilityNurseId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESPONSIBILITY_NURSE_NAME',
'displayName' : '责任护士姓名',
'type' : 'varchar(40)',
'javaName' : 'responsibilityNurseName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESPONSIBILITY_NURSE_DATE',
'displayName' : '责任护士签名日期',
'type' : 'date',
'javaName' : 'responsibilityNurseDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];