var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'HCR_PREOPERATIVE_SUMMARY_ID',
'displayName' : '术前小结id',
'type' : 'varchar(40)',
'javaName' : 'hcrPreoperativeSummaryId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'CASE_NO',
'displayName' : '病案号',
'type' : 'varchar(20)',
'javaName' : 'caseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_TIMES',
'displayName' : '住院次数',
'type' : 'number(8)',
'javaName' : 'inpatTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REMARKS',
'displayName' : '备注',
'type' : 'text',
'javaName' : 'remarks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':false,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOCTOR_ID',
'displayName' : '医师id',
'type' : 'varchar(40)',
'javaName' : 'doctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOCTOR_NAME',
'displayName' : '医师姓名',
'type' : 'varchar(20)',
'javaName' : 'doctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOCTOR_SIGN_DATE',
'displayName' : '医师签名日期',
'type' : 'date',
'javaName' : 'doctorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'CN_FOUR_RESULT',
'displayName' : '中医&quot;四诊&quot;观察结果',
'type' : 'varchar(100)',
'javaName' : 'cnFourResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CASE_ABSTRACT',
'displayName' : '病历摘要',
'type' : 'varchar(100)',
'javaName' : 'caseAbstract',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HIGHEST_DIAG_CD',
'displayName' : '术前诊断-诊断依据代码',
'type' : 'varchar(20)',
'javaName' : 'highestDiagCd',
'note' : '',
'nullable':false,
'check':'CV9900254'},
{
'name' : 'PREOPERATIVE_DIAGNOSIS',
'displayName' : '术前诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'preoperativeDiagnosis',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'PREOPERATIVE_DIAGNOSIS_NAME',
'displayName' : '术前诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'preoperativeDiagnosisName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PREOPERATIVE_DIAGNOSIS_DATE',
'displayName' : '术前诊断-诊断日期',
'type' : 'date',
'javaName' : 'preoperativeDiagnosisDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'IF_RRITABILITY',
'displayName' : '是否有过敏史',
'type' : 'number(5)',
'javaName' : 'ifRritability',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'RRITABILITY',
'displayName' : '过敏史其他描述',
'type' : 'text',
'javaName' : 'rritability',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUXILIARY_EXAMINATION_RESULTS',
'displayName' : '辅助检查结果',
'type' : 'varchar(200)',
'javaName' : 'auxiliaryExaminationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_ADAPTATION',
'displayName' : '手术适应证',
'type' : 'varchar(200)',
'javaName' : 'operationAdaptation',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_CONTRAINDICATION',
'displayName' : '手术禁忌症',
'type' : 'varchar(200)',
'javaName' : 'operationContraindication',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_INDICATION',
'displayName' : '手术指征',
'type' : 'varchar(200)',
'javaName' : 'operationIndication',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONSULTATION_OPINION',
'displayName' : '会诊意见',
'type' : 'varchar(200)',
'javaName' : 'consultationOpinion',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATIVE',
'displayName' : '手术者id',
'type' : 'varchar(40)',
'javaName' : 'operative',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATIVE_NAME',
'displayName' : '手术者姓名',
'type' : 'varchar(40)',
'javaName' : 'operativeName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATIVE_SIGN_DATE',
'displayName' : '手术者签名日期',
'type' : 'date',
'javaName' : 'operativeSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'OPERATIVE_POST',
'displayName' : '手术者专业技术职务代码',
'type' : 'varchar(20)',
'javaName' : 'operativePost',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'ANAESTHETIC',
'displayName' : '麻醉医师id',
'type' : 'varchar(40)',
'javaName' : 'anaesthetic',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANAESTHETIC_NAME',
'displayName' : '麻醉医师姓名',
'type' : 'varchar(20)',
'javaName' : 'anaestheticName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANAESTHETIC_SIGN_DATE',
'displayName' : '麻醉医师签名日期',
'type' : 'date',
'javaName' : 'anaestheticSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ANAESTHETIC_POST',
'displayName' : '麻醉医师专业技术职务代码',
'type' : 'varchar(20)',
'javaName' : 'anaestheticPost',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'OPERATION_COURSES',
'displayName' : '手术过程',
'type' : 'varchar(200)',
'javaName' : 'operationCourses',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_ID',
'displayName' : '手术单号',
'type' : 'varchar(20)',
'javaName' : 'operationId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANESTHESIA_CODE',
'displayName' : '麻醉方法代码',
'type' : 'varchar(20)',
'javaName' : 'anesthesiaCode',
'note' : '',
'nullable':true,
'check':'CV0600103'},
{
'name' : 'ANESTHESIA_WAY',
'displayName' : '麻醉方法',
'type' : 'varchar(100)',
'javaName' : 'anesthesiaWay',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_CD',
'displayName' : '手术编码',
'type' : 'varchar(20)',
'javaName' : 'operationCd',
'note' : '',
'nullable':true,
'check':'CV990113'},
{
'name' : 'OPERATION_NAME',
'displayName' : '手术名称',
'type' : 'varchar(40)',
'javaName' : 'operationName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PART_CODE',
'displayName' : '手术操作目标部位代码',
'type' : 'varchar(20)',
'javaName' : 'partCode',
'note' : '',
'nullable':true,
'check':'CV0600227'},
{
'name' : 'PART_NAME',
'displayName' : '手术操作目标部位名称',
'type' : 'varchar(20)',
'javaName' : 'partName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PROCEDURE_START',
'displayName' : '手术开始时间',
'type' : 'date',
'javaName' : 'procedureStart',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PROCEDURE_END',
'displayName' : '手术结束时间',
'type' : 'date',
'javaName' : 'procedureEnd',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'OPERATIVE_KEY_POINTS',
'displayName' : '手术要点',
'type' : 'varchar(100)',
'javaName' : 'operativeKeyPoints',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PRE_OPERATIVE_PREPARATION',
'displayName' : '术前准备',
'type' : 'varchar(100)',
'javaName' : 'preOperativePreparation',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MATTERS_NEEDING_ATTENTION',
'displayName' : '注意事项',
'type' : 'varchar(500)',
'javaName' : 'mattersNeedingAttention',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];