var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'ADMISSION_RECORD_ID',
'displayName' : '院内入院记录id',
'type' : 'varchar(40)',
'javaName' : 'admissionRecordId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NATION_CD',
'displayName' : '民族代码',
'type' : 'varchar(20)',
'javaName' : 'nationCd',
'note' : '',
'nullable':true,
'check':'CV9900377'},
{
'name' : 'OCCUPATION_CD',
'displayName' : '职业代码',
'type' : 'varchar(20)',
'javaName' : 'occupationCd',
'note' : '',
'nullable':true,
'check':'GBT22614'},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_STATE',
'displayName' : '家庭住址-省（自治区、直辖市）代码',
'type' : 'varchar(10)',
'javaName' : 'homeState',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_CITY',
'displayName' : '家庭住址-市（地区）代码',
'type' : 'varchar(10)',
'javaName' : 'homeCity',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_DISTRICT',
'displayName' : '家庭住址-县（区）代码',
'type' : 'varchar(10)',
'javaName' : 'homeDistrict',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_LINE',
'displayName' : '家庭住址-乡（镇、街道办事处）',
'type' : 'varchar(100)',
'javaName' : 'homeLine',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_ROAD',
'displayName' : '家庭住址-村（街、路、弄等）',
'type' : 'varchar(100)',
'javaName' : 'homeRoad',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_HOUSE_NO',
'displayName' : '家庭住址-门牌号码',
'type' : 'varchar(50)',
'javaName' : 'homeHouseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_TEXT',
'displayName' : '家庭住址-详细信息',
'type' : 'varchar(500)',
'javaName' : 'homeText',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MARITALSTATUS',
'displayName' : '婚姻状况代码',
'type' : 'varchar(20)',
'javaName' : 'maritalstatus',
'note' : '',
'nullable':false,
'check':'GBT22612'},
{
'name' : 'TEMP_STATE',
'displayName' : '现居住住址-省（自治区、直辖市）代码',
'type' : 'varchar(10)',
'javaName' : 'tempState',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'TEMP_CITY',
'displayName' : '现居住住址-市（地区）代码',
'type' : 'varchar(10)',
'javaName' : 'tempCity',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'TEMP_DISTRICT',
'displayName' : '现居住住址-县（区）代码',
'type' : 'varchar(10)',
'javaName' : 'tempDistrict',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'TEMP_LINE',
'displayName' : '现居住住址-乡（镇、街道办事处）',
'type' : 'varchar(100)',
'javaName' : 'tempLine',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TEMP_ROAD',
'displayName' : '现居住住址-村（街、路、弄等）',
'type' : 'varchar(100)',
'javaName' : 'tempRoad',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TEMP_HOUSE_NO',
'displayName' : '现居住住址-门牌号码',
'type' : 'varchar(50)',
'javaName' : 'tempHouseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TEMP_POST_CD',
'displayName' : '现居住地址-邮政编码',
'type' : 'varchar(50)',
'javaName' : 'tempPostCd',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TEMP_TEXT',
'displayName' : '现居住地址-详细信息',
'type' : 'varchar(500)',
'javaName' : 'tempText',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_PRO_CODE',
'displayName' : '出生地住址-省（自治区、直辖市）代码',
'type' : 'varchar(10)',
'javaName' : 'birthProCode',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'BIRTH_CITY_CODE',
'displayName' : '出生地住址-市（地区）代码',
'type' : 'varchar(10)',
'javaName' : 'birthCityCode',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'BIRTH_COU_CODE',
'displayName' : '出生地住址-县（区）代码',
'type' : 'varchar(10)',
'javaName' : 'birthCouCode',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'BIRTH_ADDRESS_VILLAGE',
'displayName' : '出生地住址-村（街、路、弄等）',
'type' : 'varchar(100)',
'javaName' : 'birthAddressVillage',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WORK_UNIT',
'displayName' : '工作单位',
'type' : 'varchar(100)',
'javaName' : 'workUnit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CN_FOUR_RESULT',
'displayName' : '中医&quot;四诊&quot;观察结果',
'type' : 'varchar(100)',
'javaName' : 'cnFourResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUT_DEPT_ID',
'displayName' : '出院科室id',
'type' : 'varchar(40)',
'javaName' : 'outDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUT_DEPT_NAME',
'displayName' : '出院科室名称',
'type' : 'varchar(40)',
'javaName' : 'outDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUT_DEPT_CD',
'displayName' : '出院科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'outDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'INPATIENT_DAYS',
'displayName' : '住院天数',
'type' : 'number(8)',
'javaName' : 'inpatientDays',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DEATH_TIME',
'displayName' : '死亡时间',
'type' : 'date',
'javaName' : 'deathTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'OUTPAT_WARD_NO',
'displayName' : '出院病房',
'type' : 'varchar(40)',
'javaName' : 'outpatWardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DEATH_CAUSE',
'displayName' : '死亡原因描述',
'type' : 'varchar(200)',
'javaName' : 'deathCause',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DEATH_DIAGNOSTIC_CODE',
'displayName' : '死亡诊断代码',
'type' : 'varchar(20)',
'javaName' : 'deathDiagnosticCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'TREATMENT_RESULT_CODE',
'displayName' : '治疗结果代码',
'type' : 'varchar(20)',
'javaName' : 'treatmentResultCode',
'note' : '',
'nullable':true,
'check':'CV0510010'},
{
'name' : 'DISCHARGE_ORDER',
'displayName' : '出院医嘱',
'type' : 'varchar(200)',
'javaName' : 'dischargeOrder',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PRESENTATION_TIME',
'displayName' : '病历陈述时间',
'type' : 'date',
'javaName' : 'presentationTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ADMISSION_RECORD_TYPE_CODE',
'displayName' : '入院记录类型代码',
'type' : 'varchar(20)',
'javaName' : 'admissionRecordTypeCode',
'note' : '',
'nullable':true,
'check':'CV990107'},
{
'name' : 'NURSING_DEPT_ID',
'displayName' : '护理科室id',
'type' : 'varchar(40)',
'javaName' : 'nursingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NURSING_DEPT_NAME',
'displayName' : '护理科室名称',
'type' : 'varchar(40)',
'javaName' : 'nursingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NURSING_DEPT_CD',
'displayName' : '护理科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'nursingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'AUDITOR_ID',
'displayName' : '最终审核者者id',
'type' : 'varchar(40)',
'javaName' : 'auditorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUDITOR_NAME',
'displayName' : '最终审核者姓名',
'type' : 'varchar(40)',
'javaName' : 'auditorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUDITOR_DATE',
'displayName' : '最终审核者签名日期',
'type' : 'date',
'javaName' : 'auditorDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AUDITOR_POST',
'displayName' : '最终审核者专业技术职务代码',
'type' : 'varchar(20)',
'javaName' : 'auditorPost',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'RESIDENT_DOCTOR_ID',
'displayName' : '住院医师id',
'type' : 'varchar(40)',
'javaName' : 'residentDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESIDENT_DOCTOR_NAME',
'displayName' : '住院医师姓名',
'type' : 'varchar(20)',
'javaName' : 'residentDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESIDENT_DOCTOR_SIGN_DATE',
'displayName' : '住院医师签名日期',
'type' : 'date',
'javaName' : 'residentDoctorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ATTENDING_DOCTOR_ID',
'displayName' : '主治医师id',
'type' : 'varchar(40)',
'javaName' : 'attendingDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ATTENDING_DOCTOR_NAME',
'displayName' : '主治医师姓名',
'type' : 'varchar(20)',
'javaName' : 'attendingDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ATTENDING_DOCTOR_SIGN_DATE',
'displayName' : '主治医师签名日期',
'type' : 'date',
'javaName' : 'attendingDoctorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RECORDER_ID',
'displayName' : '记录者id',
'type' : 'varchar(40)',
'javaName' : 'recorderId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RECORDER_NAME',
'displayName' : '记录者姓名',
'type' : 'varchar(20)',
'javaName' : 'recorderName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RECORDER_SIGN_DATE',
'displayName' : '记录者签名日期',
'type' : 'date',
'javaName' : 'recorderSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RECEIVE_EMPLOYEE_ID',
'displayName' : '接诊医师id',
'type' : 'varchar(40)',
'javaName' : 'receiveEmployeeId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RECEIVE_EMPLOYEE_NAME',
'displayName' : '接诊医师姓名',
'type' : 'varchar(40)',
'javaName' : 'receiveEmployeeName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RECEIVE_EMPLOYEE_DATE',
'displayName' : '接诊医师签名日期',
'type' : 'date',
'javaName' : 'receiveEmployeeDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RECEIVE_EMPLOYEE_POST',
'displayName' : '接诊医师专业技术职务代码',
'type' : 'varchar(20)',
'javaName' : 'receiveEmployeePost',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'CHARGE_NURSE_ID',
'displayName' : '主管护士id',
'type' : 'varchar(40)',
'javaName' : 'chargeNurseId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CHARGE_NURSE_NAME',
'displayName' : '主管护士姓名',
'type' : 'varchar(40)',
'javaName' : 'chargeNurseName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CHARGE_NURSE_DATE',
'displayName' : '主管护士签名日期',
'type' : 'date',
'javaName' : 'chargeNurseDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CHIEF',
'displayName' : '主诉',
'type' : 'text',
'javaName' : 'chief',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ILLNESS',
'displayName' : '现病史',
'type' : 'text',
'javaName' : 'illness',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HISTORY',
'displayName' : '既往史',
'type' : 'text',
'javaName' : 'history',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_MARK',
'displayName' : '健康状况标志',
'type' : 'number(5)',
'javaName' : 'healthMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'HISTORY_OF_DISEASE',
'displayName' : '疾病史（含外伤）',
'type' : 'text',
'javaName' : 'historyOfDisease',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INFECTIOUS_MARK',
'displayName' : '传染性标志',
'type' : 'number(5)',
'javaName' : 'infectiousMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'INFECTION_HISTORY',
'displayName' : '传染病史',
'type' : 'text',
'javaName' : 'infectionHistory',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OBSTETRICAL_HISTORY',
'displayName' : '婚育史',
'type' : 'text',
'javaName' : 'obstetricalHistory',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RRITABILITY',
'displayName' : '过敏史描述',
'type' : 'text',
'javaName' : 'rritability',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OP_HIS',
'displayName' : '手术史',
'type' : 'text',
'javaName' : 'opHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACC_HIS',
'displayName' : '预防接种史描述',
'type' : 'text',
'javaName' : 'vaccHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRANSFUSION_HIS',
'displayName' : '输血史描述',
'type' : 'text',
'javaName' : 'transfusionHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PER_HISTORY',
'displayName' : '个人史',
'type' : 'text',
'javaName' : 'perHistory',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MENSES_HIS',
'displayName' : '月经史',
'type' : 'text',
'javaName' : 'mensesHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FAM_HISTORY',
'displayName' : '家族史',
'type' : 'text',
'javaName' : 'famHistory',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BODY_TEMPERATURE',
'displayName' : '体格检查：体温',
'type' : 'number(8)',
'javaName' : 'bodyTemperature',
'note' : '(体温的测量值，计量单位为℃)',
'nullable':true,
'check':''},
{
'name' : 'PR_FREQ',
'displayName' : '体格检查：脉搏',
'type' : 'number(4)',
'javaName' : 'prFreq',
'note' : '(患者每分钟脉搏次数的测量值，计量单位为次/min)',
'nullable':true,
'check':''},
{
'name' : 'BREATHE_FREQ',
'displayName' : '体格检查：呼吸',
'type' : 'number(4)',
'javaName' : 'breatheFreq',
'note' : '(患者每分钟呼吸次数的测量值，计量单位为次/min)',
'nullable':true,
'check':''},
{
'name' : 'SBP',
'displayName' : '体格检查：收缩压',
'type' : 'number(4)',
'javaName' : 'sbp',
'note' : '(收缩压的测量值，计量单位为mmHg)',
'nullable':true,
'check':''},
{
'name' : 'DBP',
'displayName' : '体格检查：舒张压',
'type' : 'number(4)',
'javaName' : 'dbp',
'note' : '(舒张压的测量值，计量单位为mmHg)',
'nullable':true,
'check':''},
{
'name' : 'BODY_HEIGHT',
'displayName' : '体格检查：身高',
'type' : 'number(8)',
'javaName' : 'bodyHeight',
'note' : '(患者身高的测量值，计量单位为cm)',
'nullable':true,
'check':''},
{
'name' : 'BODY_WEIGHT',
'displayName' : '体格检查：体重',
'type' : 'number(8)',
'javaName' : 'bodyWeight',
'note' : '(患者体重的测量值，计量单位为kg)',
'nullable':true,
'check':''},
{
'name' : 'GENERAL_SITU_EXAM_RESULT',
'displayName' : '体格检查：一般状况',
'type' : 'varchar(200)',
'javaName' : 'generalSituExamResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SKIN',
'displayName' : '体格检查：皮肤粘膜',
'type' : 'varchar(200)',
'javaName' : 'skin',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LN',
'displayName' : '体格检查：淋巴结',
'type' : 'varchar(200)',
'javaName' : 'ln',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEAD',
'displayName' : '体格检查：头部',
'type' : 'varchar(200)',
'javaName' : 'head',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NECK',
'displayName' : '体格检查：颈部',
'type' : 'varchar(200)',
'javaName' : 'neck',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CHEST',
'displayName' : '体格检查：胸部',
'type' : 'varchar(200)',
'javaName' : 'chest',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BELLY',
'displayName' : '体格检查：腹部',
'type' : 'varchar(200)',
'javaName' : 'belly',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRE_RESULT_DESCR',
'displayName' : '体格检查：肛门直肠',
'type' : 'varchar(200)',
'javaName' : 'dreResultDescr',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANUS_PUDENDUM',
'displayName' : '体格检查：生殖器',
'type' : 'varchar(200)',
'javaName' : 'anusPudendum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SPINE',
'displayName' : '体格检查：脊椎',
'type' : 'varchar(200)',
'javaName' : 'spine',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LIMBS',
'displayName' : '体格检查：四肢',
'type' : 'varchar(200)',
'javaName' : 'limbs',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MENTAL',
'displayName' : '体格检查：神经系统',
'type' : 'varchar(200)',
'javaName' : 'mental',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SPECIALIST_CHECKS',
'displayName' : '专科情况检查',
'type' : 'varchar(200)',
'javaName' : 'specialistChecks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LUNG',
'displayName' : '体格检查：肺',
'type' : 'varchar(200)',
'javaName' : 'lung',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEART',
'displayName' : '体格检查：心',
'type' : 'varchar(200)',
'javaName' : 'heart',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PERIPHERAL_VESSELS',
'displayName' : '体格检查：周围血管',
'type' : 'varchar(200)',
'javaName' : 'peripheralVessels',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUXILIARY_EXAMINATION_RESULTS',
'displayName' : '辅助检查结果',
'type' : 'varchar(200)',
'javaName' : 'auxiliaryExaminationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'STATEMENTS_RELIABILITY',
'displayName' : '陈述内容可靠标志',
'type' : 'number(5)',
'javaName' : 'statementsReliability',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'THERAPEUTIC_PRINCIPLES',
'displayName' : '治则治法',
'type' : 'varchar(20)',
'javaName' : 'therapeuticPrinciples',
'note' : '',
'nullable':true,
'check':'GBT167513'},
{
'name' : 'TREAT_RESCUE_COURSE',
'displayName' : '诊疗过程描述',
'type' : 'varchar(500)',
'javaName' : 'treatRescueCourse',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PRELIMINARY_DIAG_ID',
'displayName' : '初步诊断-记录id',
'type' : 'varchar(40)',
'javaName' : 'preliminaryDiagId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PRELIMINARY_CN_SYM_DIAG_CODE',
'displayName' : '初步诊断-中医症候代码',
'type' : 'varchar(20)',
'javaName' : 'preliminaryCnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'PRELIMINARY_CN_DIS_DIAG_CODE',
'displayName' : '初步诊断-中医病名代码',
'type' : 'varchar(20)',
'javaName' : 'preliminaryCnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'PRELIMINARY_ADMIT_DIAG',
'displayName' : '初步诊断-西医诊断顺位',
'type' : 'number(8)',
'javaName' : 'preliminaryAdmitDiag',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PRELIMINARY_TCM_ADMIT_DIAG',
'displayName' : '初步诊断-中医诊断顺位',
'type' : 'number(8)',
'javaName' : 'preliminaryTcmAdmitDiag',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PRELIMINARY_DIAG_CODE',
'displayName' : '初步诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'preliminaryDiagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'PRELIMINARY_DIAG_NAME',
'displayName' : '初步诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'preliminaryDiagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PRELIMINARY_DIAG_DATE',
'displayName' : '初步诊断-诊断日期',
'type' : 'date',
'javaName' : 'preliminaryDiagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CORRECT_DIAG_ID',
'displayName' : '修正诊断-记录id',
'type' : 'varchar(40)',
'javaName' : 'correctDiagId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CORRECT_CN_SYM_DIAG_CODE',
'displayName' : '修正诊断-中医症候代码',
'type' : 'varchar(20)',
'javaName' : 'correctCnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'CORRECT_CN_DIS_DIAG_CODE',
'displayName' : '修正诊断-中医病名代码',
'type' : 'varchar(20)',
'javaName' : 'correctCnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'CORRECT_ADMIT_DIAG',
'displayName' : '修正诊断-西医诊断顺位',
'type' : 'number(8)',
'javaName' : 'correctAdmitDiag',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CORRECT_TCM_ADMIT_DIAG',
'displayName' : '修正诊断-中医诊断顺位',
'type' : 'number(8)',
'javaName' : 'correctTcmAdmitDiag',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CORRECT_DIAG_CODE',
'displayName' : '修正诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'correctDiagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'CORRECT_DIAG_NAME',
'displayName' : '修正诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'correctDiagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CORRECT_DIAG_DATE',
'displayName' : '修正诊断-诊断日期',
'type' : 'date',
'javaName' : 'correctDiagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DETERMINE_DIAG_ID',
'displayName' : '确定诊断-记录id',
'type' : 'varchar(40)',
'javaName' : 'determineDiagId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DETERMINE_CN_SYM_DIAG_CODE',
'displayName' : '确定诊断-中医症候代码',
'type' : 'varchar(20)',
'javaName' : 'determineCnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'DETERMINE_CN_DIS_DIAG_CODE',
'displayName' : '确定诊断-中医病名代码',
'type' : 'varchar(20)',
'javaName' : 'determineCnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'DETERMINE_ADMIT_DIAG',
'displayName' : '确定诊断-西医诊断顺位',
'type' : 'number(8)',
'javaName' : 'determineAdmitDiag',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DETERMINE_TCM_ADMIT_DIAG',
'displayName' : '确定诊断-中医诊断顺位',
'type' : 'number(8)',
'javaName' : 'determineTcmAdmitDiag',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DETERMINE_DIAG_CODE',
'displayName' : '确定诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'determineDiagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'DETERMINE_DIAG_NAME',
'displayName' : '确定诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'determineDiagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DETERMINE_DIAG_DATE',
'displayName' : '确定诊断-诊断日期',
'type' : 'date',
'javaName' : 'determineDiagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'SUPPLEMENT_DIAG_ID',
'displayName' : '补充诊断-记录id',
'type' : 'varchar(40)',
'javaName' : 'supplementDiagId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SUPPLEMENT_CN_SYM_DIAG_CODE',
'displayName' : '补充诊断-中医症候代码',
'type' : 'varchar(20)',
'javaName' : 'supplementCnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'SUPPLEMENT_CN_DIS_DIAG_CODE',
'displayName' : '补充诊断-中医病名代码',
'type' : 'varchar(20)',
'javaName' : 'supplementCnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'SUPPLEMENT_ADMIT_DIAG',
'displayName' : '补充诊断-西医诊断顺位',
'type' : 'number(8)',
'javaName' : 'supplementAdmitDiag',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SUPPLEMENT_TCM_ADMIT_DIAG',
'displayName' : '补充诊断-中医诊断顺位',
'type' : 'number(8)',
'javaName' : 'supplementTcmAdmitDiag',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SUPPLEMENT_DIAG_CODE',
'displayName' : '补充诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'supplementDiagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'SUPPLEMENT_DIAG_NAME',
'displayName' : '补充诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'supplementDiagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SUPPLEMENT_DIAG_DATE',
'displayName' : '补充诊断-诊断日期',
'type' : 'date',
'javaName' : 'supplementDiagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INHOS_DIAG_ID',
'displayName' : '入院诊断-记录id',
'type' : 'varchar(40)',
'javaName' : 'inhosDiagId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_DETAILS',
'displayName' : '入院情况',
'type' : 'varchar(200)',
'javaName' : 'inpatientDetails',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INHOS_CN_SYM_DIAG_CODE',
'displayName' : '入院诊断-中医症候代码',
'type' : 'varchar(20)',
'javaName' : 'inhosCnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'INHOS_CN_DIS_DIAG_CODE',
'displayName' : '入院诊断-中医病名代码',
'type' : 'varchar(20)',
'javaName' : 'inhosCnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'INHOS_ADMIT_DIAG',
'displayName' : '入院诊断-西医诊断顺位',
'type' : 'number(8)',
'javaName' : 'inhosAdmitDiag',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INHOS_TCM_ADMIT_DIAG',
'displayName' : '入院诊断-中医诊断顺位',
'type' : 'number(8)',
'javaName' : 'inhosTcmAdmitDiag',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INHOS_DIAG_CODE',
'displayName' : '入院诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'inhosDiagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'INHOS_DIAG_NAME',
'displayName' : '入院诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'inhosDiagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INHOS_DIAG_DATE',
'displayName' : '入院诊断-诊断日期',
'type' : 'date',
'javaName' : 'inhosDiagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'OUTHOS_DIAG_ID',
'displayName' : '出院诊断-记录id',
'type' : 'varchar(40)',
'javaName' : 'outhosDiagId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUTPATIENT_DETAILS',
'displayName' : '出院情况',
'type' : 'varchar(200)',
'javaName' : 'outpatientDetails',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUTHOS_DIAG_CODE',
'displayName' : '出院诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'outhosDiagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'OUTHOS_DIAG_NAME',
'displayName' : '出院诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'outhosDiagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUTHOS_DIAG_DATE',
'displayName' : '出院诊断-诊断日期',
'type' : 'date',
'javaName' : 'outhosDiagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];