var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'ADMISSION_ASSESSMENT_RECORDS_ID',
'displayName' : '院内入院评估记录id',
'type' : 'varchar(40)',
'javaName' : 'admissionAssessmentRecordsId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'MARITALSTATUS',
'displayName' : '婚姻状况代码',
'type' : 'varchar(20)',
'javaName' : 'maritalstatus',
'note' : '',
'nullable':true,
'check':'GBT22612'},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TELECOM',
'displayName' : '电话号码',
'type' : 'varchar(20)',
'javaName' : 'telecom',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WORK_PHONE',
'displayName' : '工作单位电话号码',
'type' : 'varchar(20)',
'javaName' : 'workPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EMAIL',
'displayName' : '电子邮箱地址',
'type' : 'varchar(40)',
'javaName' : 'email',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NATION_CD',
'displayName' : '民族代码',
'type' : 'varchar(20)',
'javaName' : 'nationCd',
'note' : '',
'nullable':true,
'check':'CV9900377'},
{
'name' : 'OCCUPATION_CD',
'displayName' : '职业代码',
'type' : 'varchar(20)',
'javaName' : 'occupationCd',
'note' : '',
'nullable':true,
'check':'GBT22614'},
{
'name' : 'EDUCATION_CD',
'displayName' : '学历代码',
'type' : 'varchar(20)',
'javaName' : 'educationCd',
'note' : '',
'nullable':true,
'check':'GBT4658'},
{
'name' : 'NATIONALITY_CODE',
'displayName' : '国籍代码',
'type' : 'varchar(20)',
'javaName' : 'nationalityCode',
'note' : '',
'nullable':true,
'check':'GBT2659'},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISIT_MARK',
'displayName' : '门诊或住院标识',
'type' : 'varchar(10)',
'javaName' : 'visitMark',
'note' : '',
'nullable':false,
'check':'CUS00010'},
{
'name' : 'REGISTRATION_ID',
'displayName' : '就诊流水号',
'type' : 'varchar(40)',
'javaName' : 'registrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_TIME',
'displayName' : '就诊时间',
'type' : 'date',
'javaName' : 'visitingTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CN_FOUR_RESULT',
'displayName' : '中医&quot;四诊&quot;观察结果',
'type' : 'varchar(200)',
'javaName' : 'cnFourResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IN_MODE_CODE',
'displayName' : '入院途径',
'type' : 'varchar(20)',
'javaName' : 'inModeCode',
'note' : '',
'nullable':true,
'check':'CV0900403'},
{
'name' : 'INHOSPITAL_REASON_CD',
'displayName' : '住院原因代码',
'type' : 'varchar(20)',
'javaName' : 'inhospitalReasonCd',
'note' : '',
'nullable':true,
'check':'CV0600212'},
{
'name' : 'INHOSPITAL_WAY',
'displayName' : '入病房方式',
'type' : 'varchar(40)',
'javaName' : 'inhospitalWay',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CASE_NO',
'displayName' : '病案号',
'type' : 'varchar(40)',
'javaName' : 'caseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_TIMES',
'displayName' : '住院次数',
'type' : 'number(3)',
'javaName' : 'inpatTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REMARKS',
'displayName' : '备注',
'type' : 'text',
'javaName' : 'remarks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOCUMENT_MANAGER_ID',
'displayName' : '文档管理者id',
'type' : 'varchar(40)',
'javaName' : 'documentManagerId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOCUMENT_MANAGER_NAME',
'displayName' : '文档管理者姓名',
'type' : 'varchar(40)',
'javaName' : 'documentManagerName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOCUMENT_MANAGER_DATE',
'displayName' : '文档管理者签名日期',
'type' : 'date',
'javaName' : 'documentManagerDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DOCUMENT_VERIFIER_SIGN_DATE',
'displayName' : '文档审核者签名日期',
'type' : 'date',
'javaName' : 'documentVerifierSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DOCUMENT_VERIFIER_ID',
'displayName' : '文档审核者id',
'type' : 'varchar(40)',
'javaName' : 'documentVerifierId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOCUMENT_VERIFIER_NAME',
'displayName' : '文档审核者姓名',
'type' : 'varchar(20)',
'javaName' : 'documentVerifierName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESPONSIBILITY_NURSE_ID',
'displayName' : '责任护士id',
'type' : 'varchar(40)',
'javaName' : 'responsibilityNurseId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESPONSIBILITY_NURSE_NAME',
'displayName' : '责任护士姓名',
'type' : 'varchar(40)',
'javaName' : 'responsibilityNurseName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESPONSIBILITY_NURSE_DATE',
'displayName' : '责任护士签名日期',
'type' : 'date',
'javaName' : 'responsibilityNurseDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'TREATMENT_NURSE_ID',
'displayName' : '接诊护士id',
'type' : 'varchar(40)',
'javaName' : 'treatmentNurseId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TREATMENT_NURSE_NAME',
'displayName' : '接诊护士姓名',
'type' : 'varchar(40)',
'javaName' : 'treatmentNurseName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TREATMENT_NURSE_DATE',
'displayName' : '接诊护士签名日期',
'type' : 'date',
'javaName' : 'treatmentNurseDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'MAIN_SYMPTOMS_NAME',
'displayName' : '主要症状名称',
'type' : 'varchar(40)',
'javaName' : 'mainSymptomsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MAIN_SYMPTOMS_DESCRIBED',
'displayName' : '主要症状描述',
'type' : 'varchar(40)',
'javaName' : 'mainSymptomsDescribed',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WEIGHT',
'displayName' : '体重',
'type' : 'number(8)',
'javaName' : 'weight',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BODY_TEMPERATURE',
'displayName' : '体格检查：体温',
'type' : 'number(8)',
'javaName' : 'bodyTemperature',
'note' : '(体温的测量值，计量单位为℃)',
'nullable':true,
'check':''},
{
'name' : 'PR_FREQ',
'displayName' : '体格检查：脉率',
'type' : 'number(4)',
'javaName' : 'prFreq',
'note' : '(患者每分钟脉搏次数的测量值，计量单位为次/min)',
'nullable':true,
'check':''},
{
'name' : 'BREATHE_FREQ',
'displayName' : '体格检查：呼吸频率',
'type' : 'number(4)',
'javaName' : 'breatheFreq',
'note' : '（次/min）',
'nullable':true,
'check':''},
{
'name' : 'SBP',
'displayName' : '体格检查：收缩压',
'type' : 'number(4)',
'javaName' : 'sbp',
'note' : '(收缩压的测量值，计量单位为mmHg)',
'nullable':true,
'check':''},
{
'name' : 'DBP',
'displayName' : '体格检查：舒张压',
'type' : 'number(4)',
'javaName' : 'dbp',
'note' : '(舒张压的测量值，计量单位为mmHg)',
'nullable':true,
'check':''},
{
'name' : 'BODY_HEIGHT',
'displayName' : '体格检查：身高',
'type' : 'number(8)',
'javaName' : 'bodyHeight',
'note' : '(患者身高的测量值，计量单位为cm)',
'nullable':true,
'check':''},
{
'name' : 'BODY_WEIGHT',
'displayName' : '体格检查：体重',
'type' : 'number(8)',
'javaName' : 'bodyWeight',
'note' : '(患者体重的测量值，计量单位为kg)',
'nullable':true,
'check':''},
{
'name' : 'HISTORY_OF_DISEASE',
'displayName' : '疾病史（含外伤）',
'type' : 'text',
'javaName' : 'historyOfDisease',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INFECTION_HISTORY',
'displayName' : '传染病史',
'type' : 'text',
'javaName' : 'infectionHistory',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACC_HIS',
'displayName' : '预防接种史描述',
'type' : 'text',
'javaName' : 'vaccHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OP_HIS',
'displayName' : '手术史',
'type' : 'text',
'javaName' : 'opHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRANSFUSION_HIS',
'displayName' : '输血史描述',
'type' : 'text',
'javaName' : 'transfusionHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OBSTETRICAL_HISTORY',
'displayName' : '婚育史',
'type' : 'text',
'javaName' : 'obstetricalHistory',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_MARK',
'displayName' : '一般健康状况标志',
'type' : 'number(5)',
'javaName' : 'healthMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'INFECTIOUS_MARK',
'displayName' : '患者传染性标志',
'type' : 'number(5)',
'javaName' : 'infectiousMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'RRITABILITY',
'displayName' : '过敏史描述',
'type' : 'text',
'javaName' : 'rritability',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FAM_HISTORY',
'displayName' : '家族史',
'type' : 'text',
'javaName' : 'famHistory',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'APGAR_SCORE',
'displayName' : 'Apgar评分值',
'type' : 'number(8)',
'javaName' : 'apgarScore',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DEVELOPMENT_DEGREE',
'displayName' : '发育程度代码',
'type' : 'varchar(20)',
'javaName' : 'developmentDegree',
'note' : '',
'nullable':true,
'check':'CV9900337'},
{
'name' : 'SPIRIT_NORMAL_STATUS',
'displayName' : '精神状态正常标志',
'type' : 'number(5)',
'javaName' : 'spiritNormalStatus',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'SLEEP_STATUS',
'displayName' : '睡眠状况',
'type' : 'varchar(100)',
'javaName' : 'sleepStatus',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EXCEPTIONAL_CASE',
'displayName' : '特殊情况',
'type' : 'varchar(100)',
'javaName' : 'exceptionalCase',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MENTAL_STATE',
'displayName' : '心理状态代码',
'type' : 'varchar(20)',
'javaName' : 'mentalState',
'note' : '',
'nullable':true,
'check':'CV0510002'},
{
'name' : 'NUTRITIONAL_STATUS',
'displayName' : '营养状态代码',
'type' : 'varchar(20)',
'javaName' : 'nutritionalStatus',
'note' : '',
'nullable':true,
'check':'CV9900338'},
{
'name' : 'OF_DAILY',
'displayName' : '自理能力代码',
'type' : 'varchar(20)',
'javaName' : 'ofDaily',
'note' : '',
'nullable':true,
'check':'CV9900339'},
{
'name' : 'IF_SMOKING',
'displayName' : '吸烟标志',
'type' : 'number(5)',
'javaName' : 'ifSmoking',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'SMOKING_STATE',
'displayName' : '吸烟状况代码',
'type' : 'varchar(20)',
'javaName' : 'smokingState',
'note' : '',
'nullable':true,
'check':'CV0300101'},
{
'name' : 'SMOKING_PER_DAY',
'displayName' : '日吸烟量(支)',
'type' : 'number(8)',
'javaName' : 'smokingPerDay',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'STOP_SMOKING_DAYS',
'displayName' : '停止吸烟天数',
'type' : 'number(8)',
'javaName' : 'stopSmokingDays',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IF_DRINKING',
'displayName' : '饮酒标志',
'type' : 'number(5)',
'javaName' : 'ifDrinking',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'DRINKING_FREQUENCY',
'displayName' : '饮酒频率代码',
'type' : 'varchar(20)',
'javaName' : 'drinkingFrequency',
'note' : '',
'nullable':true,
'check':'CV0300104'},
{
'name' : 'DRINKING_PER_DAY',
'displayName' : '日饮酒量（mL）',
'type' : 'number(8)',
'javaName' : 'drinkingPerDay',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIETARY_STATUS',
'displayName' : '饮食情况代码',
'type' : 'varchar(20)',
'javaName' : 'dietaryStatus',
'note' : '',
'nullable':true,
'check':'CV9900003'},
{
'name' : 'OBSERVATION_PROJECT_NAME',
'displayName' : '护理观察项目名称',
'type' : 'varchar(40)',
'javaName' : 'observationProjectName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OBSERVATION_RESULTS_DESCRIPTION',
'displayName' : '护理观察结果',
'type' : 'varchar(100)',
'javaName' : 'observationResultsDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IF_NOTIFY_PHYSICIAN',
'displayName' : '通知医师标志',
'type' : 'number(5)',
'javaName' : 'ifNotifyPhysician',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'NOTIFY_PHYSICIAN_TIME',
'displayName' : '通知医师日期时间',
'type' : 'date',
'javaName' : 'notifyPhysicianTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ASSESSMENT_TIME',
'displayName' : '评估日期时间',
'type' : 'date',
'javaName' : 'assessmentTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CN_SYM_DIAG_CODE',
'displayName' : '中医症候代码',
'type' : 'varchar(20)',
'javaName' : 'cnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'CN_DIS_DIAG_CODE',
'displayName' : '中医病名代码',
'type' : 'varchar(20)',
'javaName' : 'cnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'DIAG_CODE',
'displayName' : '诊断编码',
'type' : 'varchar(20)',
'javaName' : 'diagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'DIAG_NAME',
'displayName' : '诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'diagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIAG_DATE',
'displayName' : '诊断日期',
'type' : 'date',
'javaName' : 'diagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];