var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'PREOPERATIVE_INTERVIEW_RECORD_ID',
'displayName' : '院内麻醉术前访视记录id',
'type' : 'varchar(40)',
'javaName' : 'preoperativeInterviewRecordId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'TELECOM',
'displayName' : '电话号码',
'type' : 'varchar(20)',
'javaName' : 'telecom',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_TYPE',
'displayName' : '患者类型',
'type' : 'varchar(20)',
'javaName' : 'patientType',
'note' : '',
'nullable':true,
'check':'CV0900404'},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISIT_MARK',
'displayName' : '门诊或住院标识',
'type' : 'varchar(10)',
'javaName' : 'visitMark',
'note' : '',
'nullable':false,
'check':'CUS00010'},
{
'name' : 'REGISTRATION_ID',
'displayName' : '就诊流水号',
'type' : 'varchar(40)',
'javaName' : 'registrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_TIME',
'displayName' : '就诊时间',
'type' : 'date',
'javaName' : 'visitingTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'VISITING_TYPE',
'displayName' : '就诊类型',
'type' : 'varchar(20)',
'javaName' : 'visitingType',
'note' : '',
'nullable':true,
'check':'CV9900340'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANAESTHETIC',
'displayName' : '麻醉医师id',
'type' : 'varchar(40)',
'javaName' : 'anaesthetic',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANAESTHETIC_NAME',
'displayName' : '麻醉医师姓名',
'type' : 'varchar(20)',
'javaName' : 'anaestheticName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANAESTHETIC_SIGN_DATE',
'displayName' : '麻醉医师签名日期',
'type' : 'date',
'javaName' : 'anaestheticSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DISEASE_BEFORE_OPERATION',
'displayName' : '术前合并疾病',
'type' : 'varchar(200)',
'javaName' : 'diseaseBeforeOperation',
'note' : '患者在接受手术前，除与手术相关的诊断外，同时合并的其他疾病',
'nullable':true,
'check':''},
{
'name' : 'PREOPERATIVE_DIAGNOSIS',
'displayName' : '术前诊断-诊断编码',
'type' : 'varchar(20)',
'javaName' : 'preoperativeDiagnosis',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'PREOPERATIVE_DIAGNOSIS_NAME',
'displayName' : '术前诊断-诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'preoperativeDiagnosisName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PREOPERATIVE_DIAGNOSIS_DATE',
'displayName' : '术前诊断-诊断日期',
'type' : 'date',
'javaName' : 'preoperativeDiagnosisDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ILLNESS',
'displayName' : '现病史',
'type' : 'text',
'javaName' : 'illness',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RRITABILITY',
'displayName' : '过敏史描述',
'type' : 'text',
'javaName' : 'rritability',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BODY_WEIGHT',
'displayName' : '体重',
'type' : 'number(8)',
'javaName' : 'bodyWeight',
'note' : '患者体重的测量值，计量单位为kg',
'nullable':true,
'check':''},
{
'name' : 'GENERAL_SITU_EXAM_RESULT',
'displayName' : '一般状况',
'type' : 'text',
'javaName' : 'generalSituExamResult',
'note' : '对患者一般状况检查结果的详细描述，包括其发育状况、营养状况、体味、步态、面容与表情、意识，检查能否合作等等',
'nullable':true,
'check':''},
{
'name' : 'SPIRIT_NORMAL_STATUS',
'displayName' : '精神状态正常标志',
'type' : 'number(5)',
'javaName' : 'spiritNormalStatus',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'CARDIAC_AUSCULTATION_RESULT',
'displayName' : '心脏听诊结果',
'type' : 'varchar(200)',
'javaName' : 'cardiacAuscultationResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LUNG_AUSCULTATION_RESULT',
'displayName' : '肺部听诊结果',
'type' : 'varchar(200)',
'javaName' : 'lungAuscultationResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LIMBS',
'displayName' : '四肢检查结果',
'type' : 'varchar(200)',
'javaName' : 'limbs',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SPINE',
'displayName' : '脊柱检查结果',
'type' : 'varchar(200)',
'javaName' : 'spine',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BELLY',
'displayName' : '腹部检查结果',
'type' : 'varchar(200)',
'javaName' : 'belly',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRACHEA',
'displayName' : '气管检查结果',
'type' : 'varchar(200)',
'javaName' : 'trachea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DENTAL_EXAMINATION_RESULT',
'displayName' : '牙齿检查结果',
'type' : 'varchar(200)',
'javaName' : 'dentalExaminationResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ABO_CD',
'displayName' : 'ABO血型代码',
'type' : 'varchar(20)',
'javaName' : 'aboCd',
'note' : '',
'nullable':true,
'check':'CV0450005'},
{
'name' : 'RH_CD',
'displayName' : 'RH血型代码',
'type' : 'varchar(20)',
'javaName' : 'rhCd',
'note' : '',
'nullable':true,
'check':'CV0450020'},
{
'name' : 'ECG_RESULT',
'displayName' : '心电图检查结果',
'type' : 'varchar(200)',
'javaName' : 'ecgResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'XRAY_EXAM_RESULT',
'displayName' : '胸部X线检查结果',
'type' : 'varchar(200)',
'javaName' : 'xrayExamResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CT_EXAM_RESULT',
'displayName' : 'CT检查结果',
'type' : 'varchar(200)',
'javaName' : 'ctExamResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BSCAN_RESULT_DESCR',
'displayName' : 'B超检查结果',
'type' : 'varchar(200)',
'javaName' : 'bscanResultDescr',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MRI_EXAM_RESULT',
'displayName' : 'MRI超检查结果',
'type' : 'varchar(200)',
'javaName' : 'mriExamResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PULMONARY_EXAM_RESULT',
'displayName' : '肺功能检查结果',
'type' : 'varchar(200)',
'javaName' : 'pulmonaryExamResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ROUTINE_TEST_RESULT',
'displayName' : '血常规检查结果',
'type' : 'varchar(200)',
'javaName' : 'routineTestResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'URINE_TEST_RESULT',
'displayName' : '尿常规检查结果',
'type' : 'varchar(200)',
'javaName' : 'urineTestResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BLOOD_COAGULA_TEST_RESULT',
'displayName' : '凝血功能检查结果',
'type' : 'varchar(200)',
'javaName' : 'bloodCoagulaTestResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LIVER_TEST_RESULT',
'displayName' : '肝功能检查结果',
'type' : 'varchar(200)',
'javaName' : 'liverTestResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BLOOD_GAS_TEST_RESULT',
'displayName' : '血气分析检查结果',
'type' : 'varchar(200)',
'javaName' : 'bloodGasTestResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_CD',
'displayName' : '手术编码',
'type' : 'varchar(20)',
'javaName' : 'operationCd',
'note' : '',
'nullable':true,
'check':'CV990113'},
{
'name' : 'OP_ROOM',
'displayName' : '手术间编号',
'type' : 'varchar(20)',
'javaName' : 'opRoom',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PROPOSED_ANESTHESIA_METHOD',
'displayName' : '拟实施麻醉方法代码',
'type' : 'varchar(20)',
'javaName' : 'proposedAnesthesiaMethod',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OP_PRE_ANES_ORDER',
'displayName' : '术前麻醉医嘱',
'type' : 'varchar(100)',
'javaName' : 'opPreAnesOrder',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANES_INDICATION',
'displayName' : '麻醉适应证',
'type' : 'varchar(100)',
'javaName' : 'anesIndication',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MATTERS_NEEDING_ATTENTION',
'displayName' : '注意事项',
'type' : 'varchar(200)',
'javaName' : 'mattersNeedingAttention',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REMARKS',
'displayName' : '备注',
'type' : 'text',
'javaName' : 'remarks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];