var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'INFORMING_INFORMATION_ID',
'displayName' : '院内入院评估记录id',
'type' : 'varchar(40)',
'javaName' : 'informingInformationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TELECOM',
'displayName' : '电话号码',
'type' : 'varchar(20)',
'javaName' : 'telecom',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NATION_CD',
'displayName' : '民族代码',
'type' : 'varchar(20)',
'javaName' : 'nationCd',
'note' : '',
'nullable':true,
'check':'CV9900377'},
{
'name' : 'OCCUPATION_CD',
'displayName' : '职业代码',
'type' : 'varchar(20)',
'javaName' : 'occupationCd',
'note' : '',
'nullable':true,
'check':'GBT22614'},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISIT_MARK',
'displayName' : '门诊或住院标识',
'type' : 'varchar(10)',
'javaName' : 'visitMark',
'note' : '',
'nullable':false,
'check':'CUS00010'},
{
'name' : 'REGISTRATION_ID',
'displayName' : '就诊流水号',
'type' : 'varchar(40)',
'javaName' : 'registrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_TIME',
'displayName' : '就诊时间',
'type' : 'date',
'javaName' : 'visitingTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CN_FOUR_RESULT',
'displayName' : '中医&quot;四诊&quot;观察结果',
'type' : 'varchar(200)',
'javaName' : 'cnFourResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_TYPE',
'displayName' : '就诊类型',
'type' : 'varchar(20)',
'javaName' : 'visitingType',
'note' : '',
'nullable':true,
'check':'CV9900340'},
{
'name' : 'CHIEF',
'displayName' : '主诉',
'type' : 'text',
'javaName' : 'chief',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_AGENT_SIGN_DATE',
'displayName' : '患者签名日期时间',
'type' : 'date',
'javaName' : 'patientAgentSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AGENT_SIGN_DATE',
'displayName' : '法定代理人签名日期时间',
'type' : 'date',
'javaName' : 'agentSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'REMARKS',
'displayName' : '备注',
'type' : 'varchar(40)',
'javaName' : 'remarks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CERTIFIED_PHYSICIAN_ID',
'displayName' : '经治医师id',
'type' : 'varchar(40)',
'javaName' : 'certifiedPhysicianId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CERTIFIED_PHYSICIAN_NAME',
'displayName' : '经治医师姓名',
'type' : 'varchar(40)',
'javaName' : 'certifiedPhysicianName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CERTIFIED_PHYSICIAN_DATE',
'displayName' : '经治医师签名日期',
'type' : 'date',
'javaName' : 'certifiedPhysicianDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DIAG_CODE',
'displayName' : '诊断编码',
'type' : 'varchar(20)',
'javaName' : 'diagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'DIAG_NAME',
'displayName' : '诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'diagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIAG_DATE',
'displayName' : '诊断日期',
'type' : 'date',
'javaName' : 'diagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PRE_OPERATIVE_PREPARATION',
'displayName' : '术前准备',
'type' : 'varchar(200)',
'javaName' : 'preOperativePreparation',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_CONTRAINDICATION',
'displayName' : '手术禁忌症',
'type' : 'varchar(200)',
'javaName' : 'operationContraindication',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_INDICATION',
'displayName' : '手术指征',
'type' : 'varchar(200)',
'javaName' : 'operationIndication',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ALTERNATIVE_SOLUTION',
'displayName' : '替代方案',
'type' : 'varchar(500)',
'javaName' : 'alternativeSolution',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOSPITAL_ADVICE',
'displayName' : '医疗机构的意见',
'type' : 'varchar(200)',
'javaName' : 'hospitalAdvice',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_ADVICE',
'displayName' : '患者的意见',
'type' : 'varchar(200)',
'javaName' : 'patientAdvice',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_POSSIBLE_ACCIDENT',
'displayName' : '手术中可能出现的意外',
'type' : 'varchar(200)',
'javaName' : 'operationPossibleAccident',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'POSTOPERATIVE_POSSIBLE_ACCIDENT',
'displayName' : '手术后可能出现的意外',
'type' : 'varchar(200)',
'javaName' : 'postoperativePossibleAccident',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INCISION_TYPE_CODE',
'displayName' : '切口类别代码',
'type' : 'varchar(20)',
'javaName' : 'incisionTypeCode',
'note' : '',
'nullable':true,
'check':'CV0510022'},
{
'name' : 'INCISION_HEALING_RANK_CODE',
'displayName' : '切口愈合级别代码',
'type' : 'varchar(20)',
'javaName' : 'incisionHealingRankCode',
'note' : '',
'nullable':true,
'check':'CV550114'},
{
'name' : 'OPERATION_ID',
'displayName' : '手术单号',
'type' : 'varchar(20)',
'javaName' : 'operationId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_COURSE',
'displayName' : '手术方式描述',
'type' : 'varchar(200)',
'javaName' : 'operationCourse',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANESTHESIA_CODE',
'displayName' : '麻醉方法代码',
'type' : 'varchar(20)',
'javaName' : 'anesthesiaCode',
'note' : '',
'nullable':true,
'check':'CV0600103'},
{
'name' : 'ANESTHESIA_WAY',
'displayName' : '麻醉方法',
'type' : 'varchar(100)',
'javaName' : 'anesthesiaWay',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_CD',
'displayName' : '手术编码',
'type' : 'varchar(20)',
'javaName' : 'operationCd',
'note' : '',
'nullable':true,
'check':'CV990113'},
{
'name' : 'OPERATION_NAME',
'displayName' : '手术名称',
'type' : 'varchar(40)',
'javaName' : 'operationName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATIVE',
'displayName' : '手术者id',
'type' : 'varchar(40)',
'javaName' : 'operative',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATIVE_NAME',
'displayName' : '手术者姓名',
'type' : 'varchar(40)',
'javaName' : 'operativeName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PROCEDURE_START',
'displayName' : '手术开始时间',
'type' : 'date',
'javaName' : 'procedureStart',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PROCEDURE_END',
'displayName' : '手术结束时间',
'type' : 'date',
'javaName' : 'procedureEnd',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];