var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'INSPECTION_RESULT_ID',
'displayName' : '院内检查报告单id',
'type' : 'varchar(40)',
'javaName' : 'inspectionResultId',
'note' : '检查报告单在院内系统中的唯一标识',
'nullable':false,
'check':''},
{
'name' : 'STATUS',
'displayName' : '报告状态',
'type' : 'varchar(20)',
'javaName' : 'status',
'note' : '',
'nullable':false,
'check':'CUS00012'},
{
'name' : 'REPORT_ITEM_CODE',
'displayName' : '报告项目代码',
'type' : 'varchar(20)',
'javaName' : 'reportItemCode',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'REPORT_ITEM_NAME',
'displayName' : '报告项目名称',
'type' : 'varchar(40)',
'javaName' : 'reportItemName',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'PATIENT_ID',
'displayName' : '患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '引用患者信息表T_PATIENT院内患者id',
'nullable':false,
'check':''},
{
'name' : 'PATIENT_NAME',
'displayName' : '患者姓名',
'type' : 'varchar(40)',
'javaName' : 'patientName',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'VISIT_MARK',
'displayName' : '门诊或住院标识',
'type' : 'varchar(10)',
'javaName' : 'visitMark',
'note' : '',
'nullable':false,
'check':'CUS00010'},
{
'name' : 'REGISTRATION_ID',
'displayName' : '就诊流水号',
'type' : 'varchar(40)',
'javaName' : 'registrationId',
'note' : '引用门诊接诊表T_OUTPATIENT_REGISTRATION院内门诊流水号或引用住院接诊表T_INPATIENT_REGISTRATION院内住院流水号',
'nullable':false,
'check':''},
{
'name' : 'INSPECTION_TYPE',
'displayName' : '检查类别代码',
'type' : 'varchar(20)',
'javaName' : 'inspectionType',
'note' : '',
'nullable':true,
'check':'CV9900391'},
{
'name' : 'INSPECTION_TYPE_NAME',
'displayName' : '检查类别名称',
'type' : 'varchar(40)',
'javaName' : 'inspectionTypeName',
'note' : '',
'nullable':true,
'check':'CV9900391'},
{
'name' : 'EFFECTIVEDATETIME',
'displayName' : '标本采集时间',
'type' : 'date',
'javaName' : 'effectivedatetime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ISSUED',
'displayName' : '报告时间',
'type' : 'date',
'javaName' : 'issued',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PERFORMER_EMPLOYEE_ID',
'displayName' : '执行报告的医生id',
'type' : 'varchar(40)',
'javaName' : 'performerEmployeeId',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':false,
'check':''},
{
'name' : 'INSPECTION_ORDER_ID',
'displayName' : '检查申请单ID',
'type' : 'varchar(40)',
'javaName' : 'inspectionOrderId',
'note' : '引用检查申请表T_INSPECT_ORDER院内检查申请单id',
'nullable':false,
'check':''},
{
'name' : 'CONCLUSION',
'displayName' : '报告结论',
'type' : 'varchar(200)',
'javaName' : 'conclusion',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REPORT_ENGLISH',
'displayName' : '报告项目英文描述',
'type' : 'varchar(200)',
'javaName' : 'reportEnglish',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EQUIPMENT',
'displayName' : '检查设备名称',
'type' : 'varchar(50)',
'javaName' : 'equipment',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FINDINGS',
'displayName' : '检查所见',
'type' : 'varchar(200)',
'javaName' : 'findings',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TEST_RESULT_CD',
'displayName' : '检查结果代码',
'type' : 'varchar(20)',
'javaName' : 'testResultCd',
'note' : '',
'nullable':true,
'check':'CV9900012'},
{
'name' : 'REPORT_DESCRIPTION',
'displayName' : '检查结果的客观说明',
'type' : 'varchar(200)',
'javaName' : 'reportDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REPORT_IMPRESSION',
'displayName' : '检查结果的主观说明',
'type' : 'varchar(200)',
'javaName' : 'reportImpression',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INSPECT_ISSUED',
'displayName' : '检查时间',
'type' : 'date',
'javaName' : 'inspectIssued',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INSPECT_EMPLOYEE_ID',
'displayName' : '检查医生id',
'type' : 'varchar(40)',
'javaName' : 'inspectEmployeeId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VALUE',
'displayName' : '结果值',
'type' : 'number(8)',
'javaName' : 'value',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UNIT',
'displayName' : '结果单位',
'type' : 'varchar(20)',
'javaName' : 'unit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'METHOD',
'displayName' : '检查方法',
'type' : 'varchar(50)',
'javaName' : 'method',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LOW_VALUE',
'displayName' : '正常参考值下限',
'type' : 'number(8)',
'javaName' : 'lowValue',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LOW_UNIT',
'displayName' : '正常参考值下限单位',
'type' : 'varchar(20)',
'javaName' : 'lowUnit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HIGH_VALUE',
'displayName' : '正常参考值上限',
'type' : 'number(8)',
'javaName' : 'highValue',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HIGH_UNIT',
'displayName' : '正常参考值上限单位',
'type' : 'varchar(20)',
'javaName' : 'highUnit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REFERENCERANGE',
'displayName' : '正常参考值范围',
'type' : 'varchar(40)',
'javaName' : 'referencerange',
'note' : '比如：135g/l-180g/l',
'nullable':true,
'check':''},
{
'name' : 'ABNORMAL',
'displayName' : '异常标志',
'type' : 'varchar(20)',
'javaName' : 'abnormal',
'note' : '',
'nullable':true,
'check':'CV9900012'},
{
'name' : 'REPORT_NO',
'displayName' : '序号',
'type' : 'varchar(40)',
'javaName' : 'reportNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUDIT_ID',
'displayName' : '报告审核者ID',
'type' : 'varchar(40)',
'javaName' : 'auditId',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'AUDIT_DATE',
'displayName' : '报告审核时间',
'type' : 'date',
'javaName' : 'auditDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'EFFECTIVE_DTIME',
'displayName' : '文档创建时间',
'type' : 'date',
'javaName' : 'effectiveDtime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CONFIDENTIALITY',
'displayName' : '保密级别',
'type' : 'varchar(40)',
'javaName' : 'confidentiality',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RECOGNITION_CD',
'displayName' : '可互认标志',
'type' : 'number(5)',
'javaName' : 'recognitionCd',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'REPORT_REMARK',
'displayName' : '报告备注',
'type' : 'varchar(200)',
'javaName' : 'reportRemark',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PRINT_TIME',
'displayName' : '打印时间',
'type' : 'date',
'javaName' : 'printTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
}
];