var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'PATHOLOGICAL_REPORT_ID',
'displayName' : '病理号',
'type' : 'varchar(20)',
'javaName' : 'pathologicalReportId',
'note' : '病理报告在院内系统中的唯一标识',
'nullable':false,
'check':''},
{
'name' : 'RECORD_DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'recordDate',
'note' : '出门（急）诊病历报告的日期时间',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '引用患者信息表T_PATIENT院内患者id',
'nullable':false,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(3)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'VISIT_MARK',
'displayName' : '门诊或住院标识',
'type' : 'varchar(10)',
'javaName' : 'visitMark',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'REGISTRATION_ID',
'displayName' : '就诊流水号',
'type' : 'varchar(40)',
'javaName' : 'registrationId',
'note' : '引用门诊接诊表T_OUTPATIENT_REGISTRATION院内门诊流水号或引用住院接诊表T_INPATIENT_REGISTRATION院内住院流水号',
'nullable':false,
'check':''},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INSPECTION_DATE',
'displayName' : '送检日期',
'type' : 'date',
'javaName' : 'inspectionDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INSPECTION_UNIT',
'displayName' : '送检单位',
'type' : 'varchar(20)',
'javaName' : 'inspectionUnit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CLINICAL_DIAGNOSIS',
'displayName' : '临床诊断',
'type' : 'varchar(50)',
'javaName' : 'clinicalDiagnosis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INSPECTION_MATERIALS_PARTS',
'displayName' : '送检材料/部位',
'type' : 'varchar(50)',
'javaName' : 'inspectionMaterialsParts',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAKED_EYE_EXAMINATION',
'displayName' : '肉眼检查',
'type' : 'varchar(200)',
'javaName' : 'nakedEyeExamination',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IMAGE',
'displayName' : '图像（base64Binary）',
'type' : 'text',
'javaName' : 'image',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATHOLOGIC_DIAGNOSIS',
'displayName' : '病理诊断',
'type' : 'varchar(200)',
'javaName' : 'pathologicDiagnosis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIAGNOSIS_DATE',
'displayName' : '诊断日期',
'type' : 'date',
'javaName' : 'diagnosisDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'REVISIT_DOCTOR',
'displayName' : '复诊医师',
'type' : 'varchar(20)',
'javaName' : 'revisitDoctor',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PRIMARY_DOCTOR',
'displayName' : '初诊医师',
'type' : 'varchar(20)',
'javaName' : 'primaryDoctor',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '医疗机构在爱心医疗云平台中的唯一编码',
'nullable':false,
'check':''}
];