var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'VACCINATION_REPORT_ID',
'displayName' : '预防接种报告id',
'type' : 'varchar(40)',
'javaName' : 'vaccinationReportId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RPR_ADDR_PROVINCE',
'displayName' : '户籍登记所在地址的省、自治区或直辖市名称',
'type' : 'varchar(40)',
'javaName' : 'rprAddrProvince',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RPR_ADDR_CITY',
'displayName' : '户籍登记所在地址的市、地区或州的名称',
'type' : 'varchar(40)',
'javaName' : 'rprAddrCity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RPR_ADDR_AREA',
'displayName' : '户籍登记所在地址的县（区）的名称',
'type' : 'varchar(40)',
'javaName' : 'rprAddrArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RPR_ADDR_STREET',
'displayName' : '户籍登记所在地址的乡、镇或城市的街道办事处名称',
'type' : 'varchar(40)',
'javaName' : 'rprAddrStreet',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RPR_ADDR_VILLAGE',
'displayName' : '户籍登记所在地址的村或城市的街、路、里、弄等名称',
'type' : 'varchar(40)',
'javaName' : 'rprAddrVillage',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RPR_ADDR_HOUSE',
'displayName' : '户籍登记所在地址的门牌号码',
'type' : 'varchar(40)',
'javaName' : 'rprAddrHouse',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_STATE',
'displayName' : '家庭住址-省（自治区、直辖市）代码',
'type' : 'varchar(10)',
'javaName' : 'homeState',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_CITY',
'displayName' : '家庭住址-市（地区）代码',
'type' : 'varchar(10)',
'javaName' : 'homeCity',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_DISTRICT',
'displayName' : '家庭住址-县（区）代码',
'type' : 'varchar(10)',
'javaName' : 'homeDistrict',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'HOME_LINE',
'displayName' : '家庭住址-乡（镇、街道办事处）',
'type' : 'varchar(100)',
'javaName' : 'homeLine',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_ROAD',
'displayName' : '家庭住址-村（街、路、弄等）',
'type' : 'varchar(100)',
'javaName' : 'homeRoad',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_HOUSE_NO',
'displayName' : '家庭住址-门牌号码',
'type' : 'varchar(50)',
'javaName' : 'homeHouseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HOME_TEXT',
'displayName' : '家庭住址-详细信息',
'type' : 'varchar(500)',
'javaName' : 'homeText',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MIGRATION_TIME',
'displayName' : '迁入时间',
'type' : 'date',
'javaName' : 'migrationTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'MOVEOUT_TIME',
'displayName' : '迁出时间',
'type' : 'date',
'javaName' : 'moveoutTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'REASON_FOR_REMOVAL',
'displayName' : '搬迁原因',
'type' : 'varchar(200)',
'javaName' : 'reasonForRemoval',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INFECTIOUS_NAME_DISEASE',
'displayName' : '既往所患传染病名称描述',
'type' : 'varchar(200)',
'javaName' : 'infectiousNameDisease',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACCINATION_DATE',
'displayName' : '接种日期',
'type' : 'date',
'javaName' : 'vaccinationDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INOCULUM_DOSE',
'displayName' : '接种剂次',
'type' : 'number(8)',
'javaName' : 'inoculumDose',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INOCULATION_SITE',
'displayName' : '接种部位',
'type' : 'varchar(200)',
'javaName' : 'inoculationSite',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACCINATION_DOCTOR_NUMBER',
'displayName' : '接种医生编号',
'type' : 'varchar(40)',
'javaName' : 'vaccinationDoctorNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACCINATION_DOCTOR_NAME',
'displayName' : '接种医生名称',
'type' : 'varchar(40)',
'javaName' : 'vaccinationDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACCINATION_ORG_NUMBER',
'displayName' : '接种机构编号',
'type' : 'varchar(40)',
'javaName' : 'vaccinationOrgNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACCINATION_ORG_NAME',
'displayName' : '接种机构名称',
'type' : 'varchar(40)',
'javaName' : 'vaccinationOrgName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REACTIONS_ABNORMAL_DESCRIPTION_HISTORY',
'displayName' : '疫苗异常反应史',
'type' : 'varchar(1000)',
'javaName' : 'reactionsAbnormalDescriptionHistory',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACCINATION_TABOO',
'displayName' : '接种禁忌',
'type' : 'varchar(200)',
'javaName' : 'vaccinationTaboo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACCINE_VALIDITY',
'displayName' : '疫苗有效期',
'type' : 'date',
'javaName' : 'vaccineValidity',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'VACCINE_LOT',
'displayName' : '疫苗批号',
'type' : 'varchar(40)',
'javaName' : 'vaccineLot',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACCINE_NAME',
'displayName' : '疫苗名称',
'type' : 'varchar(40)',
'javaName' : 'vaccineName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACCINE_ORG_NUMBER',
'displayName' : '疫苗生产厂商编号',
'type' : 'varchar(40)',
'javaName' : 'vaccineOrgNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACCINE_ORG_NAME',
'displayName' : '疫苗生产厂商名称',
'type' : 'varchar(80)',
'javaName' : 'vaccineOrgName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VACCINE_NAME_CODE',
'displayName' : '引起不良反应的可疑疫苗名称代码',
'type' : 'varchar(20)',
'javaName' : 'vaccineNameCode',
'note' : '',
'nullable':true,
'check':'CV0850001'},
{
'name' : 'ADVERSE_REACTIONS_SUSPECT_VACCINE_NAME_CODE',
'displayName' : '预防接种后不良反应临床诊断代码',
'type' : 'varchar(20)',
'javaName' : 'adverseReactionsSuspectVaccineNameCode',
'note' : '',
'nullable':true,
'check':'CV0501032'},
{
'name' : 'ADVERSE_REACTIONS_OCCURRENCE_DATE',
'displayName' : '不良反应发生日期',
'type' : 'date',
'javaName' : 'adverseReactionsOccurrenceDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ADVERSE_DRUG_REACTION',
'displayName' : '不良反应处理结果',
'type' : 'varchar(200)',
'javaName' : 'adverseDrugReaction',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];