var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'HCR_CONSULTATION_NOTE_ID',
'displayName' : '会诊记录id',
'type' : 'varchar(40)',
'javaName' : 'hcrConsultationNoteId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'CONSULTATION_REQUEST_DEPT_ID',
'displayName' : '会诊申请科室id',
'type' : 'varchar(40)',
'javaName' : 'consultationRequestDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONSULTATION_REQUEST_DEPT_NAME',
'displayName' : '会诊申请科室名称',
'type' : 'varchar(40)',
'javaName' : 'consultationRequestDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONSULTATION_REQUEST_DEPT_CD',
'displayName' : '会诊申请科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'consultationRequestDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'CONSULTATION_DEPT_ID',
'displayName' : '会诊科室id',
'type' : 'varchar(40)',
'javaName' : 'consultationDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONSULTATION_DEPT_NAME',
'displayName' : '会诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'consultationDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONSULTATION_DEPT_CD',
'displayName' : '会诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'consultationDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IF_RRITABILITY',
'displayName' : '是否有过敏史',
'type' : 'number(5)',
'javaName' : 'ifRritability',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'RRITABILITY',
'displayName' : '过敏史其他描述',
'type' : 'text',
'javaName' : 'rritability',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONSULTATION_REQUEST_DOCTOR_ID',
'displayName' : '会诊申请医师id',
'type' : 'varchar(40)',
'javaName' : 'consultationRequestDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONSULTATION_REQUEST_DOCTOR_NAME',
'displayName' : '会诊申请医师姓名',
'type' : 'varchar(20)',
'javaName' : 'consultationRequestDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONSULTATION_DOCTOR_ID',
'displayName' : '会诊医师id',
'type' : 'varchar(40)',
'javaName' : 'consultationDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONSULTATION_DOCTOR_NAME',
'displayName' : '会诊医师姓名',
'type' : 'varchar(20)',
'javaName' : 'consultationDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONSULTATION_DATE',
'displayName' : '会诊日期',
'type' : 'date',
'javaName' : 'consultationDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CN_FOUR_RESULT',
'displayName' : '中医&quot;四诊&quot;观察结果',
'type' : 'varchar(100)',
'javaName' : 'cnFourResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CASE_ABSTRACT',
'displayName' : '病历摘要',
'type' : 'varchar(100)',
'javaName' : 'caseAbstract',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CN_SYM_DIAG_CODE',
'displayName' : '中医症候代码',
'type' : 'varchar(20)',
'javaName' : 'cnSymDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'CN_DIS_DIAG_CODE',
'displayName' : '中医病名代码',
'type' : 'varchar(20)',
'javaName' : 'cnDisDiagCode',
'note' : '',
'nullable':true,
'check':'CV9900357'},
{
'name' : 'DIAG_CODE',
'displayName' : '诊断编码',
'type' : 'varchar(20)',
'javaName' : 'diagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'DIAG_NAME',
'displayName' : '诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'diagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIAG_DATE',
'displayName' : '诊断日期',
'type' : 'date',
'javaName' : 'diagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AUXILIARY_EXAMINATION_RESULTS',
'displayName' : '辅助检查结果',
'type' : 'varchar(200)',
'javaName' : 'auxiliaryExaminationResults',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'THERAPEUTIC_PRINCIPLES',
'displayName' : '治则治法代码',
'type' : 'varchar(10)',
'javaName' : 'therapeuticPrinciples',
'note' : '根据辨证结果采用的治则治法名称术语',
'nullable':true,
'check':'GBT167513'},
{
'name' : 'TREAT_COURSE_NAME',
'displayName' : '诊疗过程名称',
'type' : 'varchar(200)',
'javaName' : 'treatCourseName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONSULTATION_PURPOSES',
'displayName' : '会诊目的',
'type' : 'varchar(200)',
'javaName' : 'consultationPurposes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONSULTATION_TYPE',
'displayName' : '会诊类型',
'type' : 'varchar(200)',
'javaName' : 'consultationType',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONSULTATION_REASON',
'displayName' : '会诊原因',
'type' : 'varchar(200)',
'javaName' : 'consultationReason',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONSULTATION_OPINION',
'displayName' : '会诊意见',
'type' : 'varchar(100)',
'javaName' : 'consultationOpinion',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TREAT_RESCUE_COURSE',
'displayName' : '诊疗过程描述',
'type' : 'varchar(500)',
'javaName' : 'treatRescueCourse',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];