var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'EXPECTANT_RECORD_ID',
'displayName' : '院内待产记录id',
'type' : 'varchar(40)',
'javaName' : 'expectantRecordId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CASE_NO',
'displayName' : '病案号',
'type' : 'varchar(40)',
'javaName' : 'caseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_TIMES',
'displayName' : '住院次数',
'type' : 'number(3)',
'javaName' : 'inpatTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REMARKS',
'displayName' : '备注',
'type' : 'varchar(200)',
'javaName' : 'remarks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'TELECOM',
'displayName' : '电话号码',
'type' : 'varchar(20)',
'javaName' : 'telecom',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_TYPE',
'displayName' : '患者类型',
'type' : 'varchar(20)',
'javaName' : 'patientType',
'note' : '',
'nullable':true,
'check':'CV0900404'},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_CONTROL_EXAMINER_ID',
'displayName' : '产程检查者id',
'type' : 'varchar(40)',
'javaName' : 'birthControlExaminerId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_CONTROL_EXAMINER_NAME',
'displayName' : '产程检查者姓名',
'type' : 'varchar(40)',
'javaName' : 'birthControlExaminerName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_CONTROL_EXAMINER_DATE',
'displayName' : '产程检查者签名日期',
'type' : 'date',
'javaName' : 'birthControlExaminerDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RECORDER_ID',
'displayName' : '记录人id',
'type' : 'varchar(40)',
'javaName' : 'recorderId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RECORDER_NAME',
'displayName' : '记录人姓名',
'type' : 'varchar(40)',
'javaName' : 'recorderName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RECORDER_DATE',
'displayName' : '记录人签名日期',
'type' : 'date',
'javaName' : 'recorderDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DELIVERY_TIME',
'displayName' : '待产日期时间',
'type' : 'date',
'javaName' : 'deliveryTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'GRAVIDITY',
'displayName' : '孕次',
'type' : 'number(8)',
'javaName' : 'gravidity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PARITY',
'displayName' : '产次',
'type' : 'number(8)',
'javaName' : 'parity',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MENSES_LAST_DATE',
'displayName' : '末次月经日期',
'type' : 'date',
'javaName' : 'mensesLastDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CONCEPTION_FORM_CD',
'displayName' : '受孕形式代码',
'type' : 'varchar(20)',
'javaName' : 'conceptionFormCd',
'note' : '',
'nullable':true,
'check':'CV9900344'},
{
'name' : 'EXPECTED_CHILDBIRTH_DATE',
'displayName' : '预产期',
'type' : 'date',
'javaName' : 'expectedChildbirthDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PREGNANCY_EXAMINE_CD',
'displayName' : '产前检查标志',
'type' : 'number(5)',
'javaName' : 'pregnancyExamineCd',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'ANTENATAL_EXAM_ABNORMAL',
'displayName' : '产前检查异常情况',
'type' : 'varchar(100)',
'javaName' : 'antenatalExamAbnormal',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PREGNANCY_SPECIAL_CIRCUMSTANCES',
'displayName' : '此次妊娠特殊情况',
'type' : 'varchar(100)',
'javaName' : 'pregnancySpecialCircumstances',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PREPREGNANCY_WEIGHT',
'displayName' : '孕前体重',
'type' : 'number(8)',
'javaName' : 'prepregnancyWeight',
'note' : 'kg',
'nullable':true,
'check':''},
{
'name' : 'PRENATAL_HEIGHT',
'displayName' : '身高',
'type' : 'number(8)',
'javaName' : 'prenatalHeight',
'note' : 'cm',
'nullable':true,
'check':''},
{
'name' : 'PRENATAL_WEIGHT',
'displayName' : '产前体重',
'type' : 'number(8)',
'javaName' : 'prenatalWeight',
'note' : 'kg',
'nullable':true,
'check':''},
{
'name' : 'SBP',
'displayName' : '收缩压',
'type' : 'number(8)',
'javaName' : 'sbp',
'note' : 'mmHg',
'nullable':true,
'check':''},
{
'name' : 'DBP',
'displayName' : '舒张压',
'type' : 'number(8)',
'javaName' : 'dbp',
'note' : 'mmHg',
'nullable':true,
'check':''},
{
'name' : 'BODY_TEMPERATURE',
'displayName' : '体温',
'type' : 'number(8)',
'javaName' : 'bodyTemperature',
'note' : '℃',
'nullable':true,
'check':''},
{
'name' : 'PULSES',
'displayName' : '脉率',
'type' : 'number(8)',
'javaName' : 'pulses',
'note' : '次/min',
'nullable':true,
'check':''},
{
'name' : 'BREATHING_RATE',
'displayName' : '呼吸频率',
'type' : 'number(8)',
'javaName' : 'breathingRate',
'note' : '次/min',
'nullable':true,
'check':''},
{
'name' : 'HISTORY',
'displayName' : '既往史',
'type' : 'text',
'javaName' : 'history',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OP_HIS',
'displayName' : '手术史',
'type' : 'text',
'javaName' : 'opHis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MATERNAL_HISTORY',
'displayName' : '既往孕产史',
'type' : 'text',
'javaName' : 'maternalHistory',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UTERUS_HEIGHT',
'displayName' : '宫底高度',
'type' : 'number(8)',
'javaName' : 'uterusHeight',
'note' : 'cm',
'nullable':true,
'check':''},
{
'name' : 'ABDOMINAL_GIRTH',
'displayName' : '腹围',
'type' : 'number(8)',
'javaName' : 'abdominalGirth',
'note' : 'cm',
'nullable':true,
'check':''},
{
'name' : 'FETUS_POSITION_CD',
'displayName' : '胎方位代码',
'type' : 'varchar(20)',
'javaName' : 'fetusPositionCd',
'note' : '',
'nullable':true,
'check':'CV0501007'},
{
'name' : 'FETAL_HEART_RATE',
'displayName' : '胎心率',
'type' : 'number(8)',
'javaName' : 'fetalHeartRate',
'note' : '次/min',
'nullable':true,
'check':''},
{
'name' : 'HEAD_DIFFER_SITUATION_EVA',
'displayName' : '头位难产情况的评估',
'type' : 'varchar(100)',
'javaName' : 'headDifferSituationEva',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRANSVERSE_OUTLET',
'displayName' : '出口横径',
'type' : 'number(8)',
'javaName' : 'transverseOutlet',
'note' : 'cm',
'nullable':true,
'check':''},
{
'name' : 'EXTERNAL_CONJUGATE',
'displayName' : '骶耻外径',
'type' : 'number(8)',
'javaName' : 'externalConjugate',
'note' : 'cm',
'nullable':true,
'check':''},
{
'name' : 'BIISCHIAL_DIAMETER',
'displayName' : '坐骨结节间径',
'type' : 'number(8)',
'javaName' : 'biischialDiameter',
'note' : 'cm',
'nullable':true,
'check':''},
{
'name' : 'CONTRACTION_STATE',
'displayName' : '宫缩情况',
'type' : 'varchar(100)',
'javaName' : 'contractionState',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CERVICAL_THICKNESS',
'displayName' : '宫颈厚度',
'type' : 'varchar(100)',
'javaName' : 'cervicalThickness',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PALACE_MOUTH_STATE',
'displayName' : '宫口情况',
'type' : 'varchar(100)',
'javaName' : 'palaceMouthState',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEMBRANE_CD',
'displayName' : '胎膜是否破',
'type' : 'number(5)',
'javaName' : 'membraneCd',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'PROM_CODE',
'displayName' : '胎膜情况代码',
'type' : 'varchar(20)',
'javaName' : 'promCode',
'note' : '',
'nullable':true,
'check':'CV9900345'},
{
'name' : 'RUPTURE_WAY_CD',
'displayName' : '破膜方式代码',
'type' : 'varchar(20)',
'javaName' : 'ruptureWayCd',
'note' : '',
'nullable':true,
'check':'CV9900397'},
{
'name' : 'PRE_PART_STATION',
'displayName' : '先露位置',
'type' : 'varchar(100)',
'javaName' : 'prePartStation',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AMNIOTIC_FLUID_STATE',
'displayName' : '羊水情况',
'type' : 'varchar(100)',
'javaName' : 'amnioticFluidState',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FILLING_BLADDER_CD',
'displayName' : '膀胱充盈标志',
'type' : 'number(5)',
'javaName' : 'fillingBladderCd',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'INTESTINAL_INFLATION_CD',
'displayName' : '肠胀气标志',
'type' : 'number(5)',
'javaName' : 'intestinalInflationCd',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'EXAM_METHOD_CD',
'displayName' : '检查方式代码',
'type' : 'varchar(20)',
'javaName' : 'examMethodCd',
'note' : '',
'nullable':true,
'check':'CV9900346'},
{
'name' : 'TREATMENT_PLAN',
'displayName' : '处置计划',
'type' : 'varchar(200)',
'javaName' : 'treatmentPlan',
'note' : '对产妇情况进行综合评估的基础上，为其制定的处置计划的详细描述',
'nullable':true,
'check':''},
{
'name' : 'PLAN_DELIVERY_METHOD',
'displayName' : '计划选取的分娩方式',
'type' : 'varchar(100)',
'javaName' : 'planDeliveryMethod',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LABOR_RECORD_TIME',
'displayName' : '产程记录日期时间',
'type' : 'date',
'javaName' : 'laborRecordTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'LABOR_COURSE',
'displayName' : '产程经过',
'type' : 'varchar(500)',
'javaName' : 'laborCourse',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];