var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'ITEM_CODE',
'displayName' : '院内收费项目编码',
'type' : 'varchar(40)',
'javaName' : 'itemCode',
'note' : '收费项目在院内系统中的唯一标识',
'nullable':false,
'check':''},
{
'name' : 'ITEM_NAME',
'displayName' : '收费项目名称',
'type' : 'varchar(40)',
'javaName' : 'itemName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUTP_FEE_TYPE_CODE',
'displayName' : '门诊费用类型代码',
'type' : 'varchar(20)',
'javaName' : 'outpFeeTypeCode',
'note' : '',
'nullable':false,
'check':'CV9900326'},
{
'name' : 'HOSP_FEE_TYPE_CODE',
'displayName' : '住院费用类型代码',
'type' : 'varchar(20)',
'javaName' : 'hospFeeTypeCode',
'note' : '',
'nullable':false,
'check':'CV9900326'},
{
'name' : 'ITEM_SPEC',
'displayName' : '项目规格',
'type' : 'varchar(40)',
'javaName' : 'itemSpec',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ITEM_UNIT',
'displayName' : '单位',
'type' : 'varchar(40)',
'javaName' : 'itemUnit',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'ITEM_PRICE',
'displayName' : '单价',
'type' : 'number(8)',
'javaName' : 'itemPrice',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'NCMS_MEDICATION',
'displayName' : '对应农合编码',
'type' : 'varchar(20)',
'javaName' : 'ncmsMedication',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEDICAL_INSURANCE',
'displayName' : '对应医保编码',
'type' : 'varchar(20)',
'javaName' : 'medicalInsurance',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FEE_BASIS',
'displayName' : '收费依据',
'type' : 'varchar(1000)',
'javaName' : 'feeBasis',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEDICATION_CATEGORY',
'displayName' : '医保报销标志',
'type' : 'varchar(20)',
'javaName' : 'medicationCategory',
'note' : '',
'nullable':true,
'check':'CV9900286'},
{
'name' : 'NCMS_MEDICATION_CATEGORY',
'displayName' : '农合报销标志',
'type' : 'varchar(20)',
'javaName' : 'ncmsMedicationCategory',
'note' : '',
'nullable':true,
'check':'CV9900373'},
{
'name' : 'ITEM_STD_CODE',
'displayName' : '收费项目标准编码',
'type' : 'varchar(40)',
'javaName' : 'itemStdCode',
'note' : '',
'nullable':true,
'check':'CV990112'}
];