var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'IPN_SAVE_RECORD_ID',
'displayName' : '抢救记录id',
'type' : 'varchar(40)',
'javaName' : 'ipnSaveRecordId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'CASE_NO',
'displayName' : '病案号',
'type' : 'varchar(20)',
'javaName' : 'caseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_TIMES',
'displayName' : '住院次数',
'type' : 'number(8)',
'javaName' : 'inpatTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REMARKS',
'displayName' : '备注',
'type' : 'text',
'javaName' : 'remarks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'IF_RRITABILITY',
'displayName' : '是否有过敏史',
'type' : 'number(5)',
'javaName' : 'ifRritability',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'RRITABILITY',
'displayName' : '过敏史其他描述',
'type' : 'text',
'javaName' : 'rritability',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SIGN_DOCTOR_ID',
'displayName' : '签名医师id',
'type' : 'varchar(40)',
'javaName' : 'signDoctorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SIGN_DOCTOR_NAME',
'displayName' : '签名医师姓名',
'type' : 'varchar(20)',
'javaName' : 'signDoctorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SIGN_DOCTOR_SIGN_DATE',
'displayName' : '医师签名日期',
'type' : 'date',
'javaName' : 'signDoctorSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'SIGN_DOCTOR_POST',
'displayName' : '签名医师专业技术职务代码',
'type' : 'varchar(20)',
'javaName' : 'signDoctorPost',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'DISCUSSION_ONE_ID',
'displayName' : '讨论成员1id',
'type' : 'varchar(40)',
'javaName' : 'discussionOneId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCUSSION_ONE_NAME',
'displayName' : '讨论成员1姓名',
'type' : 'varchar(20)',
'javaName' : 'discussionOneName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCUSSION_TWO_ID',
'displayName' : '讨论成员2id',
'type' : 'varchar(40)',
'javaName' : 'discussionTwoId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCUSSION_TWO_NAME',
'displayName' : '讨论成员2姓名',
'type' : 'varchar(20)',
'javaName' : 'discussionTwoName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCUSSION_THREE_ID',
'displayName' : '讨论成员3id',
'type' : 'varchar(40)',
'javaName' : 'discussionThreeId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISCUSSION_THREE_NAME',
'displayName' : '讨论成员3姓名',
'type' : 'varchar(20)',
'javaName' : 'discussionThreeName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'CN_FOUR_RESULT',
'displayName' : '中医&quot;四诊&quot;观察结果',
'type' : 'varchar(200)',
'javaName' : 'cnFourResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONDITION_CHANGES',
'displayName' : '病情变化情况',
'type' : 'varchar(100)',
'javaName' : 'conditionChanges',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIAG_CODE',
'displayName' : '诊断编码',
'type' : 'varchar(20)',
'javaName' : 'diagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'DIAG_NAME',
'displayName' : '诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'diagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIAGNOSIS_DATE',
'displayName' : '诊断日期',
'type' : 'date',
'javaName' : 'diagnosisDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INTERVENTION',
'displayName' : '介入物名称',
'type' : 'varchar(100)',
'javaName' : 'intervention',
'note' : '实施手术操作时使用/放置的材料/药物的名称',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_METHOD',
'displayName' : '操作方法',
'type' : 'varchar(40)',
'javaName' : 'operationMethod',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_TIMES',
'displayName' : '操作次数',
'type' : 'varchar(20)',
'javaName' : 'operationTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESCUE_MEASURES',
'displayName' : '抢救措施',
'type' : 'varchar(40)',
'javaName' : 'rescueMeasures',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_ID',
'displayName' : '手术单id',
'type' : 'varchar(40)',
'javaName' : 'operationId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANESTHESIA_METHOD_CD',
'displayName' : '麻醉方法代码',
'type' : 'varchar(20)',
'javaName' : 'anesthesiaMethodCd',
'note' : '',
'nullable':true,
'check':'CV0600103'},
{
'name' : 'ANESTHESIA_METHOD_NAME',
'displayName' : '麻醉方法名称',
'type' : 'varchar(40)',
'javaName' : 'anesthesiaMethodName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_CD',
'displayName' : '手术编码',
'type' : 'varchar(20)',
'javaName' : 'operationCd',
'note' : '',
'nullable':true,
'check':'CV990113'},
{
'name' : 'OPERATION_NAME',
'displayName' : '手术名称',
'type' : 'varchar(40)',
'javaName' : 'operationName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PART_CODE',
'displayName' : '手术操作目标部位代码',
'type' : 'varchar(20)',
'javaName' : 'partCode',
'note' : '',
'nullable':true,
'check':'CV0600227'},
{
'name' : 'PART_NAME',
'displayName' : '手术操作目标部位名称',
'type' : 'varchar(20)',
'javaName' : 'partName',
'note' : '',
'nullable':true,
'check':'CV0600227'},
{
'name' : 'SAVE_START_DATE',
'displayName' : '抢救开始日期时间',
'type' : 'date',
'javaName' : 'saveStartDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'SAVE_END_DATE',
'displayName' : '抢救结束日期时间',
'type' : 'date',
'javaName' : 'saveEndDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'MATTERS_NEEDING_ATTENTION',
'displayName' : '注意事项',
'type' : 'varchar(500)',
'javaName' : 'mattersNeedingAttention',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TEST_RESULT_CD',
'displayName' : '检查结果代码',
'type' : 'varchar(20)',
'javaName' : 'testResultCd',
'note' : '',
'nullable':true,
'check':'CV9900012'},
{
'name' : 'RESULT_INTERPRE',
'displayName' : '结果值的解释',
'type' : 'varchar(200)',
'javaName' : 'resultInterpre',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TEST_TYPE_CD',
'displayName' : '结果类型代码',
'type' : 'varchar(20)',
'javaName' : 'testTypeCd',
'note' : '',
'nullable':true,
'check':'CV9900325'},
{
'name' : 'REPORT_DESCRIPTION',
'displayName' : '检查结果的客观说明',
'type' : 'varchar(200)',
'javaName' : 'reportDescription',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REPORT_IMPRESSION',
'displayName' : '检查结果的主观说明',
'type' : 'varchar(200)',
'javaName' : 'reportImpression',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EXAMINATION_OBSERVATION_ID',
'displayName' : '原系统检验/检查报告观察ID',
'type' : 'varchar(40)',
'javaName' : 'examinationObservationId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REPORT_ITEM_CODE',
'displayName' : '报告项目代码',
'type' : 'varchar(20)',
'javaName' : 'reportItemCode',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REPORT_ITEM_NAME',
'displayName' : '报告项目名称',
'type' : 'varchar(40)',
'javaName' : 'reportItemName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VALUE',
'displayName' : '结果值',
'type' : 'number(8)',
'javaName' : 'value',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UNIT',
'displayName' : '结果单位',
'type' : 'varchar(20)',
'javaName' : 'unit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EFFECTIVEDATETIME',
'displayName' : '标本采集时间',
'type' : 'date',
'javaName' : 'effectivedatetime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ISSUED',
'displayName' : '报告时间',
'type' : 'date',
'javaName' : 'issued',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];