var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'CESAREAN_SECTION_RECORD_ID',
'displayName' : '院内剖宫产记录id',
'type' : 'varchar(40)',
'javaName' : 'cesareanSectionRecordId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CASE_NO',
'displayName' : '病案号',
'type' : 'varchar(40)',
'javaName' : 'caseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_TIMES',
'displayName' : '住院次数',
'type' : 'number(3)',
'javaName' : 'inpatTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REMARKS',
'displayName' : '备注',
'type' : 'varchar(200)',
'javaName' : 'remarks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'TELECOM',
'displayName' : '电话号码',
'type' : 'varchar(20)',
'javaName' : 'telecom',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_TYPE',
'displayName' : '患者类型',
'type' : 'varchar(20)',
'javaName' : 'patientType',
'note' : '',
'nullable':true,
'check':'CV0900404'},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PROTECT_BABY_ID',
'displayName' : '护婴者id',
'type' : 'varchar(40)',
'javaName' : 'protectBabyId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PROTECT_BABY_NAME',
'displayName' : '护婴者姓名',
'type' : 'varchar(40)',
'javaName' : 'protectBabyName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PROTECT_BABY_DATE',
'displayName' : '护婴者签名日期',
'type' : 'date',
'javaName' : 'protectBabyDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INSTRUCTOR_ID',
'displayName' : '指导者id',
'type' : 'varchar(40)',
'javaName' : 'instructorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INSTRUCTOR_NAME',
'displayName' : '指导者姓名',
'type' : 'varchar(40)',
'javaName' : 'instructorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INSTRUCTOR_DATE',
'displayName' : '指导者签名日期',
'type' : 'date',
'javaName' : 'instructorDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AMNIOTIC_COMPLETE_MARK',
'displayName' : '胎膜完整情况标志',
'type' : 'number(5)',
'javaName' : 'amnioticCompleteMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'CHORDA_UMBILICALIS_LENGTH',
'displayName' : '脐带长度',
'type' : 'number(8)',
'javaName' : 'chordaUmbilicalisLength',
'note' : 'cm',
'nullable':true,
'check':''},
{
'name' : 'RAOGENG_BODY',
'displayName' : '绕颈身',
'type' : 'number(8)',
'javaName' : 'raogengBody',
'note' : '周',
'nullable':true,
'check':''},
{
'name' : 'PRENATAL_DIAG_NAME',
'displayName' : '产前诊断',
'type' : 'varchar(40)',
'javaName' : 'prenatalDiagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_INDICATION',
'displayName' : '手术指征',
'type' : 'varchar(100)',
'javaName' : 'operationIndication',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_DESCRIBE',
'displayName' : '剖宫产手术过程',
'type' : 'varchar(200)',
'javaName' : 'operationDescribe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UTERINE_CONDITIONS',
'displayName' : '子宫情况',
'type' : 'varchar(200)',
'javaName' : 'uterineConditions',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FETUS_POSITION_CD',
'displayName' : '胎方位代码',
'type' : 'varchar(20)',
'javaName' : 'fetusPositionCd',
'note' : '',
'nullable':true,
'check':'CV0501007'},
{
'name' : 'DELIVERY_BABY_METHOD',
'displayName' : '胎儿娩出方式',
'type' : 'varchar(100)',
'javaName' : 'deliveryBabyMethod',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PLACENTA_YELLOW',
'displayName' : '胎盘黄染',
'type' : 'varchar(100)',
'javaName' : 'placentaYellow',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEMBRANE_YELLOW',
'displayName' : '胎膜黄染',
'type' : 'varchar(100)',
'javaName' : 'membraneYellow',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CORD_ENTANGLEMENT_STATE',
'displayName' : '脐带缠绕情况',
'type' : 'varchar(200)',
'javaName' : 'cordEntanglementState',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UMBILICAL_CORD_TORSION',
'displayName' : '脐带扭转（周）',
'type' : 'number(8)',
'javaName' : 'umbilicalCordTorsion',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SAVE_CORD_BLOOD_CD',
'displayName' : '留存脐带血情况标志',
'type' : 'number(5)',
'javaName' : 'saveCordBloodCd',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'UTERINE_SUTURE_STATE',
'displayName' : '子宫壁缝合情况',
'type' : 'varchar(200)',
'javaName' : 'uterineSutureState',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UTEROTONIC_NAME',
'displayName' : '宫缩剂名称',
'type' : 'varchar(100)',
'javaName' : 'uterotonicName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UTEROTONIC_USE_WAY',
'displayName' : '宫缩剂使用方法',
'type' : 'varchar(100)',
'javaName' : 'uterotonicUseWay',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_DRUG',
'displayName' : '手术用药',
'type' : 'varchar(100)',
'javaName' : 'operationDrug',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_DRUG_AMOUNT',
'displayName' : '手术用药量',
'type' : 'varchar(100)',
'javaName' : 'operationDrugAmount',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EXPLORATION_UTERUS',
'displayName' : '腹腔探查子宫',
'type' : 'varchar(100)',
'javaName' : 'explorationUterus',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EXPLORATION_ADNEXA',
'displayName' : '腹腔探查附件',
'type' : 'varchar(100)',
'javaName' : 'explorationAdnexa',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UTEROTONIC_YC_CD',
'displayName' : '宫腔探查异常情况标志',
'type' : 'number(5)',
'javaName' : 'uterotonicYcCd',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'UTEROTONIC_JL_CD',
'displayName' : '宫腔探查肌瘤标志',
'type' : 'number(5)',
'javaName' : 'uterotonicJlCd',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'UTERINE_PROBE',
'displayName' : '宫腔探查处理情况',
'type' : 'varchar(200)',
'javaName' : 'uterineProbe',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_MATERNAL_STATE',
'displayName' : '手术时产妇情况',
'type' : 'varchar(200)',
'javaName' : 'operationMaternalState',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRANSFUSION_COMPONENT',
'displayName' : '输血成分',
'type' : 'varchar(100)',
'javaName' : 'transfusionComponent',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OTHER_DRUG',
'displayName' : '其他用药',
'type' : 'varchar(100)',
'javaName' : 'otherDrug',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OTHER_STATE',
'displayName' : '其他情况',
'type' : 'varchar(100)',
'javaName' : 'otherState',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_WHOLE_TIME',
'displayName' : '手术全程时间（min）',
'type' : 'number(8)',
'javaName' : 'operationWholeTime',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANES_POSITION',
'displayName' : '麻醉体位',
'type' : 'varchar(40)',
'javaName' : 'anesPosition',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANES_EFFECT',
'displayName' : '麻醉效果',
'type' : 'varchar(40)',
'javaName' : 'anesEffect',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LOSSBLOOD_AMOUNT',
'displayName' : '出血量（mL）',
'type' : 'number(8)',
'javaName' : 'lossbloodAmount',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TRANSFUSION_ITEM_AMOUNT',
'displayName' : '输血量',
'type' : 'number(8)',
'javaName' : 'transfusionItemAmount',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INFUSION_AMOUNT',
'displayName' : '输液量',
'type' : 'number(8)',
'javaName' : 'infusionAmount',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OXYGEN_TIME',
'displayName' : '供氧时间（min）',
'type' : 'number(8)',
'javaName' : 'oxygenTime',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_ID',
'displayName' : '手术单id号',
'type' : 'varchar(40)',
'javaName' : 'operationId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EXPECTANT_TIME',
'displayName' : '待产日期时间',
'type' : 'date',
'javaName' : 'expectantTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ANESTHESIA_METHOD_CD',
'displayName' : '麻醉方法代码',
'type' : 'varchar(20)',
'javaName' : 'anesthesiaMethodCd',
'note' : '',
'nullable':true,
'check':'CV0600103'},
{
'name' : 'ANESTHESIA_METHOD_NAME',
'displayName' : '麻醉方法名称',
'type' : 'varchar(40)',
'javaName' : 'anesthesiaMethodName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATION_CD',
'displayName' : '手术编码',
'type' : 'varchar(20)',
'javaName' : 'operationCd',
'note' : '',
'nullable':true,
'check':'CV990113'},
{
'name' : 'OPERATION_NAME',
'displayName' : '手术名称',
'type' : 'varchar(40)',
'javaName' : 'operationName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PART_CODE',
'displayName' : '手术操作目标部位代码',
'type' : 'varchar(20)',
'javaName' : 'partCode',
'note' : '',
'nullable':true,
'check':'CV0600227'},
{
'name' : 'PART_NAME',
'displayName' : '手术操作目标部位名称',
'type' : 'varchar(20)',
'javaName' : 'partName',
'note' : '',
'nullable':true,
'check':'CV0600227'},
{
'name' : 'OPERATIVE',
'displayName' : '手术者id',
'type' : 'varchar(40)',
'javaName' : 'operative',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OPERATIVE_NAME',
'displayName' : '手术者姓名',
'type' : 'varchar(40)',
'javaName' : 'operativeName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FIRST_ASSISTANT',
'displayName' : 'I助id',
'type' : 'varchar(40)',
'javaName' : 'firstAssistant',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FIRST_ASSISTANT_NAME',
'displayName' : 'I助姓名',
'type' : 'varchar(40)',
'javaName' : 'firstAssistantName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EQUIPMENT_MANAGER',
'displayName' : '器材管理者id',
'type' : 'varchar(40)',
'javaName' : 'equipmentManager',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'EQUIPMENT_MANAGER_NAME',
'displayName' : '器材管理者姓名',
'type' : 'varchar(40)',
'javaName' : 'equipmentManagerName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANAESTHETIC',
'displayName' : '麻醉者id',
'type' : 'varchar(40)',
'javaName' : 'anaesthetic',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ANAESTHETIC_NAME',
'displayName' : '麻醉者姓名',
'type' : 'varchar(40)',
'javaName' : 'anaestheticName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PROCEDURE_START',
'displayName' : '手术开始时间',
'type' : 'date',
'javaName' : 'procedureStart',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PROCEDURE_END',
'displayName' : '手术结束时间',
'type' : 'date',
'javaName' : 'procedureEnd',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'OP_POST_DIAG',
'displayName' : '产后诊断',
'type' : 'varchar(40)',
'javaName' : 'opPostDiag',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'POSTPARTUM_OBS_TIME',
'displayName' : '产后观察日期时间',
'type' : 'date',
'javaName' : 'postpartumObsTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'POSTPARTUM_EXAMINATION_TIME',
'displayName' : '产后检查时间（min）',
'type' : 'number(8)',
'javaName' : 'postpartumExaminationTime',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SBP',
'displayName' : '收缩压（mmHg）',
'type' : 'number(8)',
'javaName' : 'sbp',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DBP',
'displayName' : '舒张压（mmHg）',
'type' : 'number(8)',
'javaName' : 'dbp',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PULSES',
'displayName' : '脉搏（次/min）',
'type' : 'number(8)',
'javaName' : 'pulses',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'POSTPARTUM_HEART_RATE',
'displayName' : '产后心率（次/min）',
'type' : 'number(8)',
'javaName' : 'postpartumHeartRate',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'POSTPARTUM_LOSSBLOOD_AMOUNT',
'displayName' : '产后出血量（mL）',
'type' : 'number(8)',
'javaName' : 'postpartumLossbloodAmount',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'POSTPARTUM_UC',
'displayName' : '产后宫缩',
'type' : 'number(8)',
'javaName' : 'postpartumUc',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'POSTPARTUM_FUNDUS_HEIGHT',
'displayName' : '产后宫底高度（cm）',
'type' : 'number(8)',
'javaName' : 'postpartumFundusHeight',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'GENDER_CODE',
'displayName' : '性别代码',
'type' : 'varchar(20)',
'javaName' : 'genderCode',
'note' : '',
'nullable':true,
'check':'GBT22611'},
{
'name' : 'BIRTH_WEIGHT',
'displayName' : '新生儿出生体重（g）',
'type' : 'number(8)',
'javaName' : 'birthWeight',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BIRTH_LENGTH',
'displayName' : '新生儿出生身长（cm）',
'type' : 'number(8)',
'javaName' : 'birthLength',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TUMOR_SIZE',
'displayName' : '产瘤大小',
'type' : 'varchar(40)',
'javaName' : 'tumorSize',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TUMOR_PART',
'displayName' : '产瘤部位',
'type' : 'varchar(40)',
'javaName' : 'tumorPart',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'APGAR_SCORE_INTERVAL_CD',
'displayName' : 'Apgar评分间隔时间代码',
'type' : 'varchar(20)',
'javaName' : 'apgarScoreIntervalCd',
'note' : '',
'nullable':true,
'check':'CV9900342'},
{
'name' : 'APGAR_SCORE',
'displayName' : 'Apgar评分值',
'type' : 'number(8)',
'javaName' : 'apgarScore',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DELIVERY_OUTCOME_CD',
'displayName' : '分娩结局代码',
'type' : 'varchar(20)',
'javaName' : 'deliveryOutcomeCd',
'note' : '',
'nullable':true,
'check':'CV9900306'},
{
'name' : 'NEWBORN_ABNORMAL_CD',
'displayName' : '新生儿异常情况代码',
'type' : 'varchar(20)',
'javaName' : 'newbornAbnormalCd',
'note' : '',
'nullable':true,
'check':'CV9900343'},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];