var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '引用住院接诊表T_INPATIENT_REGISTRATION院内住院流水号INPATIENT_REGISTRATION_ID',
'nullable':false,
'check':''},
{
'name' : 'ADVICE_SEQUENCE',
'displayName' : '医嘱序号',
'type' : 'varchar(40)',
'javaName' : 'adviceSequence',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'ADVICE_SUB_SEQUENCE',
'displayName' : '医嘱子序号',
'type' : 'varchar(40)',
'javaName' : 'adviceSubSequence',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'STATUS',
'displayName' : '状态',
'type' : 'varchar(20)',
'javaName' : 'status',
'note' : '',
'nullable':true,
'check':'CUS00008'},
{
'name' : 'PATIENT_ID',
'displayName' : '患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '引用患者信息表T_PATIENT院内患者id',
'nullable':false,
'check':''},
{
'name' : 'PATIENT_NAME',
'displayName' : '患者姓名',
'type' : 'varchar(40)',
'javaName' : 'patientName',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATEWRITTEN',
'displayName' : '开立时间',
'type' : 'date',
'javaName' : 'datewritten',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PRESCRIBER',
'displayName' : '开立医生ID',
'type' : 'varchar(40)',
'javaName' : 'prescriber',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'ORDER_DPID',
'displayName' : '开立科室',
'type' : 'varchar(40)',
'javaName' : 'orderDpid',
'note' : '引用科室信息表T_DEPARTMENT院内科室id',
'nullable':true,
'check':''},
{
'name' : 'DATEENDED',
'displayName' : '停止时间',
'type' : 'date',
'javaName' : 'dateended',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'STOP_DOCTORID',
'displayName' : '停止医生',
'type' : 'varchar(40)',
'javaName' : 'stopDoctorid',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'ORDER_STOP_NURSE_CD',
'displayName' : '停止护士',
'type' : 'varchar(40)',
'javaName' : 'orderStopNurseCd',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'CHECK_DATE',
'displayName' : '校对时间',
'type' : 'date',
'javaName' : 'checkDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CHECK_NURID',
'displayName' : '校对护士',
'type' : 'varchar(40)',
'javaName' : 'checkNurid',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'ORDER_AUDITOR_DATE',
'displayName' : '审核时间',
'type' : 'date',
'javaName' : 'orderAuditorDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ORDER_AUDITOR',
'displayName' : '审核人',
'type' : 'varchar(40)',
'javaName' : 'orderAuditor',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'ORDER_CHECK_TIME',
'displayName' : '医嘱核对日期时间',
'type' : 'date',
'javaName' : 'orderCheckTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PERFORM_TIME',
'displayName' : '执行时间',
'type' : 'date',
'javaName' : 'performTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PERFORM_DEPT_CD',
'displayName' : '执行科室',
'type' : 'varchar(40)',
'javaName' : 'performDeptCd',
'note' : '引用科室信息表T_DEPARTMENT院内科室id',
'nullable':true,
'check':''},
{
'name' : 'PERFORMER_CD',
'displayName' : '执行医生',
'type' : 'varchar(40)',
'javaName' : 'performerCd',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'NOTE',
'displayName' : '备注',
'type' : 'varchar(500)',
'javaName' : 'note',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TEXT',
'displayName' : '医嘱正文',
'type' : 'varchar(200)',
'javaName' : 'text',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'START',
'displayName' : '医嘱开始时间',
'type' : 'date',
'javaName' : 'start',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'END',
'displayName' : '用药停止日期时间',
'type' : 'date',
'javaName' : 'end',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DURATION',
'displayName' : '执行天数',
'type' : 'number(8)',
'javaName' : 'duration',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOSAGE_CODE',
'displayName' : '用药途径代码',
'type' : 'varchar(20)',
'javaName' : 'dosageCode',
'note' : '',
'nullable':true,
'check':'CV0600102'},
{
'name' : 'C_MED_CODE',
'displayName' : '特殊用法代码',
'type' : 'varchar(20)',
'javaName' : 'cMedCode',
'note' : '',
'nullable':true,
'check':'CV9900285'},
{
'name' : 'ONCE_VALUE',
'displayName' : '用药次剂量',
'type' : 'number(8)',
'javaName' : 'onceValue',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ONCE_UNIT',
'displayName' : '用药次剂量单位',
'type' : 'varchar(20)',
'javaName' : 'onceUnit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRUG_TOTAL_DOSE',
'displayName' : '用药总剂量',
'type' : 'number(8)',
'javaName' : 'drugTotalDose',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DRUG_TOTAL_DOSE_UTIL',
'displayName' : '用药总剂量单位',
'type' : 'varchar(20)',
'javaName' : 'drugTotalDoseUtil',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FEE_CODE',
'displayName' : '医疗付费方式代码',
'type' : 'varchar(20)',
'javaName' : 'feeCode',
'note' : '',
'nullable':true,
'check':'CV9900376'},
{
'name' : 'ORDER_TYPE_CODE',
'displayName' : '医嘱类型代码',
'type' : 'varchar(20)',
'javaName' : 'orderTypeCode',
'note' : '',
'nullable':false,
'check':'CV9900229'},
{
'name' : 'ST_MARK',
'displayName' : '是否需要皮试',
'type' : 'number(5)',
'javaName' : 'stMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'SKINTEST_TYPE',
'displayName' : '皮试类型标志',
'type' : 'varchar(20)',
'javaName' : 'skintestType',
'note' : '',
'nullable':true,
'check':'CV9900287'},
{
'name' : 'SKINTEST_RESULT',
'displayName' : '皮试结果',
'type' : 'varchar(100)',
'javaName' : 'skintestResult',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SKINTEST_NURID',
'displayName' : '皮试护士',
'type' : 'varchar(40)',
'javaName' : 'skintestNurid',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'SKINTEST_SENURID',
'displayName' : '第二皮试护士',
'type' : 'varchar(40)',
'javaName' : 'skintestSenurid',
'note' : '引用医务人员信息表T_EMPLOYEE院内人员id',
'nullable':true,
'check':''},
{
'name' : 'ITEM_SPEC',
'displayName' : '项目规格',
'type' : 'varchar(40)',
'javaName' : 'itemSpec',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FREQ_CODE',
'displayName' : '医嘱频率代码',
'type' : 'varchar(20)',
'javaName' : 'freqCode',
'note' : '',
'nullable':true,
'check':'CV9900341'},
{
'name' : 'PRESCRIPTION_ITEM_CODE',
'displayName' : '医嘱项目',
'type' : 'varchar(40)',
'javaName' : 'prescriptionItemCode',
'note' : '引用药品信息表T_MEDICATION院内药品编码或引用收费项目信息表T_CHARGING_ITEM院内收费项目编码',
'nullable':true,
'check':''},
{
'name' : 'ITEM_NUMBER',
'displayName' : '数量',
'type' : 'number(8)',
'javaName' : 'itemNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ITEM_UNIT',
'displayName' : '项目单位',
'type' : 'varchar(20)',
'javaName' : 'itemUnit',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ITEM_AMOUNT',
'displayName' : '金额',
'type' : 'number(8)',
'javaName' : 'itemAmount',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ITEM_PRICE',
'displayName' : '单价',
'type' : 'number(8)',
'javaName' : 'itemPrice',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DISPENSING_DTIME',
'displayName' : '发药时间',
'type' : 'date',
'javaName' : 'dispensingDtime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'GROUP_NO',
'displayName' : '成组号',
'type' : 'varchar(40)',
'javaName' : 'groupNo',
'note' : '患者用药时，某些药物是一组,药物搭配用',
'nullable':true,
'check':''},
{
'name' : 'ORDER_PLAN_ST_DATE',
'displayName' : '医嘱计划开始日期时间',
'type' : 'date',
'javaName' : 'orderPlanStDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'ORDER_PLAN_END_DATE',
'displayName' : '医嘱计划结束日期时间',
'type' : 'date',
'javaName' : 'orderPlanEndDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'CRUCIAL_DRUG_NAME',
'displayName' : '关键药物名称',
'type' : 'varchar(40)',
'javaName' : 'crucialDrugName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CRUCIAL_DRUG_USAGE',
'displayName' : '关键药物用法',
'type' : 'varchar(40)',
'javaName' : 'crucialDrugUsage',
'note' : '',
'nullable':true,
'check':''}
];