var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'DISCHARGE_ASSESSMENT_GUIDANCE_RECORDS_ID',
'displayName' : '院内出院评估与指导id',
'type' : 'varchar(40)',
'javaName' : 'dischargeAssessmentGuidanceRecordsId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AGE',
'displayName' : '年龄',
'type' : 'number(8)',
'javaName' : 'age',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NATION_CD',
'displayName' : '民族代码',
'type' : 'varchar(20)',
'javaName' : 'nationCd',
'note' : '',
'nullable':true,
'check':'CV9900377'},
{
'name' : 'OCCUPATION_CD',
'displayName' : '职业代码',
'type' : 'varchar(20)',
'javaName' : 'occupationCd',
'note' : '',
'nullable':true,
'check':'GBT22614'},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPATIENT_REGISTRATION_ID',
'displayName' : '住院流水号',
'type' : 'varchar(40)',
'javaName' : 'inpatientRegistrationId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'START_TIME',
'displayName' : '入院时间',
'type' : 'date',
'javaName' : 'startTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'END_TIME',
'displayName' : '出院时间',
'type' : 'date',
'javaName' : 'endTime',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'INH_ID',
'displayName' : '住院号',
'type' : 'varchar(40)',
'javaName' : 'inhId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_ID',
'displayName' : '就诊科室id',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_NAME',
'displayName' : '就诊科室名称',
'type' : 'varchar(40)',
'javaName' : 'visitingDeptName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISITING_DEPT_CD',
'displayName' : '就诊科室标准编码',
'type' : 'varchar(20)',
'javaName' : 'visitingDeptCd',
'note' : '',
'nullable':true,
'check':'CV9900051'},
{
'name' : 'TREATMENT_NURSE_ID',
'displayName' : '接诊护士id',
'type' : 'varchar(40)',
'javaName' : 'treatmentNurseId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TREATMENT_NURSE_NAME',
'displayName' : '接诊护士姓名',
'type' : 'varchar(40)',
'javaName' : 'treatmentNurseName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TREATMENT_NURSE_POST_CD',
'displayName' : '接诊护士专业技术职务代码',
'type' : 'varchar(20)',
'javaName' : 'treatmentNursePostCd',
'note' : '',
'nullable':true,
'check':'CV9900374'},
{
'name' : 'WARD_NO',
'displayName' : '病房号',
'type' : 'varchar(20)',
'javaName' : 'wardNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'WARD_AREA',
'displayName' : '病区',
'type' : 'varchar(40)',
'javaName' : 'wardArea',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'BED_NUM',
'displayName' : '床位号',
'type' : 'varchar(20)',
'javaName' : 'bedNum',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CASE_NO',
'displayName' : '病案号',
'type' : 'varchar(40)',
'javaName' : 'caseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INPAT_TIMES',
'displayName' : '住院次数',
'type' : 'number(3)',
'javaName' : 'inpatTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'REMARKS',
'displayName' : '备注',
'type' : 'text',
'javaName' : 'remarks',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOCUMENT_MANAGER_ID',
'displayName' : '文档管理者id',
'type' : 'varchar(40)',
'javaName' : 'documentManagerId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOCUMENT_MANAGER_NAME',
'displayName' : '文档管理者姓名',
'type' : 'varchar(40)',
'javaName' : 'documentManagerName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOCUMENT_MANAGER_DATE',
'displayName' : '文档管理者签名日期',
'type' : 'date',
'javaName' : 'documentManagerDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DOCUMENT_VERIFIER_SIGN_DATE',
'displayName' : '文档审核者签名日期',
'type' : 'date',
'javaName' : 'documentVerifierSignDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DOCUMENT_VERIFIER_ID',
'displayName' : '文档审核者id',
'type' : 'varchar(40)',
'javaName' : 'documentVerifierId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DOCUMENT_VERIFIER_NAME',
'displayName' : '文档审核者姓名',
'type' : 'varchar(20)',
'javaName' : 'documentVerifierName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESPONSIBILITY_NURSE_ID',
'displayName' : '责任护士id',
'type' : 'varchar(40)',
'javaName' : 'responsibilityNurseId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESPONSIBILITY_NURSE_NAME',
'displayName' : '责任护士姓名',
'type' : 'varchar(40)',
'javaName' : 'responsibilityNurseName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'RESPONSIBILITY_NURSE_DATE',
'displayName' : '责任护士签名日期',
'type' : 'date',
'javaName' : 'responsibilityNurseDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'DIAG_CODE',
'displayName' : '诊断编码',
'type' : 'varchar(20)',
'javaName' : 'diagCode',
'note' : '',
'nullable':true,
'check':'CV990111'},
{
'name' : 'DIAG_NAME',
'displayName' : '诊断编码名称',
'type' : 'varchar(40)',
'javaName' : 'diagName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'DIAG_DATE',
'displayName' : '诊断日期',
'type' : 'date',
'javaName' : 'diagDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'OUTPATIENT_DETAILS',
'displayName' : '出院情况',
'type' : 'varchar(200)',
'javaName' : 'outpatientDetails',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OUT_MODE_CODE',
'displayName' : '离院方式',
'type' : 'varchar(20)',
'javaName' : 'outModeCode',
'note' : '',
'nullable':true,
'check':'CV0600226'},
{
'name' : 'DIET_GUIDE',
'displayName' : '饮食指导代码',
'type' : 'varchar(20)',
'javaName' : 'dietGuide',
'note' : '',
'nullable':true,
'check':'CV9900333'},
{
'name' : 'LIFESTYLE_GUIDANCE',
'displayName' : '生活方式指导',
'type' : 'varchar(1000)',
'javaName' : 'lifestyleGuidance',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PROPAGANDA_CONTENT',
'displayName' : '宣教内容',
'type' : 'varchar(1000)',
'javaName' : 'propagandaContent',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'VISIT_THE_GUIDE',
'displayName' : '复诊指导',
'type' : 'varchar(200)',
'javaName' : 'visitTheGuide',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MEDICATION_GUIDE',
'displayName' : '用药指导',
'type' : 'varchar(200)',
'javaName' : 'medicationGuide',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'OF_DAILY',
'displayName' : '自理能力代码',
'type' : 'varchar(20)',
'javaName' : 'ofDaily',
'note' : '',
'nullable':true,
'check':'CV9900339'},
{
'name' : 'DIETARY_STATUS',
'displayName' : '饮食情况代码',
'type' : 'varchar(20)',
'javaName' : 'dietaryStatus',
'note' : '',
'nullable':true,
'check':'CV9900003'},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];