var datetimeValueHandler = function(value){
	var date = new Date(value);
	return date.format('yyyy-MM-dd hh:mm:ss');
};
var fieldModels = [ 
{
'name' : 'SMIPIR_ID',
'displayName' : '重性精神疾病患者个人信息登记id',
'type' : 'varchar(40)',
'javaName' : 'smipirId',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'DATE',
'displayName' : '记录日期',
'type' : 'date',
'javaName' : 'date',
'note' : '',
'nullable':false,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'AUTHOR_ID',
'displayName' : '文档创建者id',
'type' : 'varchar(40)',
'javaName' : 'authorId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'AUTHOR_NAME',
'displayName' : '文档创建者姓名',
'type' : 'varchar(20)',
'javaName' : 'authorName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'PATIENT_ID',
'displayName' : '院内患者ID',
'type' : 'varchar(40)',
'javaName' : 'patientId',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'ID_CARD',
'displayName' : '身份证号',
'type' : 'varchar(40)',
'javaName' : 'idCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_FILE_NUMBER',
'displayName' : '城乡居民健康档案编号',
'type' : 'varchar(40)',
'javaName' : 'healthFileNumber',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'HEALTH_CARD',
'displayName' : '健康卡号',
'type' : 'varchar(40)',
'javaName' : 'healthCard',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'NAME',
'displayName' : '姓名',
'type' : 'varchar(20)',
'javaName' : 'name',
'note' : '',
'nullable':false,
'check':''},
{
'name' : 'GENDER',
'displayName' : '性别',
'type' : 'varchar(10)',
'javaName' : 'gender',
'note' : '',
'nullable':false,
'check':'GBT22611'},
{
'name' : 'BIRTHDATE',
'displayName' : '出生日期',
'type' : 'date',
'javaName' : 'birthdate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'RELATIONSHIP',
'displayName' : '联系人关系代码',
'type' : 'varchar(20)',
'javaName' : 'relationship',
'note' : '',
'nullable':true,
'check':'GBT4761'},
{
'name' : 'CONTACTS_NAME',
'displayName' : '联系人姓名',
'type' : 'varchar(20)',
'javaName' : 'contactsName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_PHONE',
'displayName' : '联系人电话号码',
'type' : 'varchar(20)',
'javaName' : 'contactsPhone',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_HOME_STATE',
'displayName' : '联系人-家庭住址-省（自治区、直辖市）代码',
'type' : 'varchar(10)',
'javaName' : 'contactsHomeState',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'CONTACTS_HOME_CITY',
'displayName' : '联系人-家庭住址-市（地区）代码',
'type' : 'varchar(10)',
'javaName' : 'contactsHomeCity',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'CONTACTS_HOME_DISTRICT',
'displayName' : '联系人-家庭住址-县（区）代码',
'type' : 'varchar(10)',
'javaName' : 'contactsHomeDistrict',
'note' : '',
'nullable':true,
'check':'GBT2260'},
{
'name' : 'CONTACTS_HOME_LINE',
'displayName' : '联系人-家庭住址-乡（镇、街道办事处）',
'type' : 'varchar(100)',
'javaName' : 'contactsHomeLine',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_HOME_ROAD',
'displayName' : '联系人-家庭住址-村（街、路、弄等）',
'type' : 'varchar(100)',
'javaName' : 'contactsHomeRoad',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_HOME_HOUSE_NO',
'displayName' : '联系人-家庭住址-门牌号码',
'type' : 'varchar(50)',
'javaName' : 'contactsHomeHouseNo',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'CONTACTS_HOME_TEXT',
'displayName' : '联系人-家庭住址-详细信息',
'type' : 'varchar(500)',
'javaName' : 'contactsHomeText',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INFORMED_CONSENT_MANAGEMENT_MARK',
'displayName' : '知情同意管理标志',
'type' : 'number(5)',
'javaName' : 'informedConsentManagementMark',
'note' : '',
'nullable':true,
'check':'CUS00004'},
{
'name' : 'INFORMED_CONSENT_SIGNATURE',
'displayName' : '知情同意签字人姓名',
'type' : 'varchar(40)',
'javaName' : 'informedConsentSignature',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'INFORMED_CONSENT_SIGNATURE_DATE',
'displayName' : '知情同意签字日期',
'type' : 'date',
'javaName' : 'informedConsentSignatureDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'SEVERE_MENTAL_ILLNESS_PATIENTS_FIRST_ONSET_AGE',
'displayName' : '重性精神疾病患者首次发病年龄（岁）',
'type' : 'number(8)',
'javaName' : 'severeMentalIllnessPatientsFirstOnsetAge',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'MENTAL_SYMPTOM_CODE',
'displayName' : '精神症状代码',
'type' : 'varchar(20)',
'javaName' : 'mentalSymptomCode',
'note' : '',
'nullable':true,
'check':'CV0401009'},
{
'name' : 'PREVIOUS_OUTPATIENT_TREATMENT_CODE',
'displayName' : '既往门诊治疗情况代码',
'type' : 'varchar(20)',
'javaName' : 'previousOutpatientTreatmentCode',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'FIRST_TREATMENT_ANTIPSYCHOTIC_DATE',
'displayName' : '首次抗精神神病治疗日期',
'type' : 'date',
'javaName' : 'firstTreatmentAntipsychoticDate',
'note' : '',
'nullable':true,
'check':'',
'valueHandler':datetimeValueHandler
},
{
'name' : 'PAST_PSYCHIATRIC_HOSPITAL_TIMES',
'displayName' : '既往精神专科住院次数',
'type' : 'number(4)',
'javaName' : 'pastPsychiatricHospitalTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'TREATMENT_RESULT_CODE',
'displayName' : '疾病转归代码',
'type' : 'varchar(20)',
'javaName' : 'treatmentResultCode',
'note' : '',
'nullable':true,
'check':'CV0510010'},
{
'name' : 'MENTAL_ILLNESS_ON_FAMILY_SOCIETY_IMPACT',
'displayName' : '患重性精神疾病对家庭社会的影响代码',
'type' : 'varchar(20)',
'javaName' : 'mentalIllnessOnFamilySocietyImpact',
'note' : '',
'nullable':true,
'check':'CV0300112'},
{
'name' : 'ILLNESS_ON_FAMILY_SOCIETY_INFLUENCE_TIMES',
'displayName' : '患病对家庭社会的影响次数',
'type' : 'number(4)',
'javaName' : 'illnessOnFamilySocietyInfluenceTimes',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'LOCK_CASE_CODE',
'displayName' : '关锁情况代码',
'type' : 'varchar(20)',
'javaName' : 'lockCaseCode',
'note' : '',
'nullable':true,
'check':'CV9900020'},
{
'name' : 'ECONOMIC_CODE',
'displayName' : '经济情况代码',
'type' : 'varchar(20)',
'javaName' : 'economicCode',
'note' : '',
'nullable':true,
'check':'CV9900069'},
{
'name' : 'SEVERE_MENTAL_ILLNESS_NAME_CODE',
'displayName' : '重性精神疾病名称代码',
'type' : 'varchar(20)',
'javaName' : 'severeMentalIllnessNameCode',
'note' : '',
'nullable':true,
'check':'CV0501036'},
{
'name' : 'DIAGNOSTIC_MEDICAL_INSTITUTION_NAME',
'displayName' : '确诊医疗机构名称',
'type' : 'varchar(40)',
'javaName' : 'diagnosticMedicalInstitutionName',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'SPECIALIST_ADVICE',
'displayName' : '专科医生意见',
'type' : 'varchar(200)',
'javaName' : 'specialistAdvice',
'note' : '',
'nullable':true,
'check':''},
{
'name' : 'UP_HOSPITAL_NAME',
'displayName' : '上传机构名称',
'type' : 'varchar(40)',
'javaName' : 'upHospitalName',
'note' : '上传数据医疗机构在市平台的机构代码',
'nullable':false,
'check':''}
];